#!/bin/bash
cd -- "$(dirname "$0")" #changes the terminal's directory to the directory where the script was launched
echo "Copying Colosseum Tool Assets. This may take a while..."
mkdir ./out/Assets
mkdir ./out/Assets/Colosseum
mkdir ./out/Assets/Colosseum/wiimm
cp ../images/PokeBody/body_334.png ./out/Assets/Colosseum/body_334.png
cp ../images/PokeBody/body_211.png ./out/Assets/Colosseum/body_211.png
cp ../images/PokeBody/body_202.png ./out/Assets/Colosseum/body_202.png
cp ../images/PokeBody/body_330.png ./out/Assets/Colosseum/body_330.png
cp ../images/PokeFace/face_412.png ./out/Assets/Colosseum/face_412.png
cp ../images/PokeBody/body_331.png ./out/Assets/Colosseum/body_331.png
cp ../images/PokeFace/face_008.png ./out/Assets/Colosseum/face_008.png
cp ../images/PokeBody/body_188.png ./out/Assets/Colosseum/body_188.png
cp ../images/PokeFace/face_202.png ./out/Assets/Colosseum/face_202.png
cp ../images/PokeBody/body_184.png ./out/Assets/Colosseum/body_184.png
cp ../images/PokeBody/body_375.png ./out/Assets/Colosseum/body_375.png
cp ../images/PokeBody/body_381.png ./out/Assets/Colosseum/body_381.png
cp ../images/PokeFace/face_098.png ./out/Assets/Colosseum/face_098.png
cp ../images/PokeBody/body_335.png ./out/Assets/Colosseum/body_335.png
cp ../images/PokeFace/face_033.png ./out/Assets/Colosseum/face_033.png
cp ../images/PokeBody/body_122.png ./out/Assets/Colosseum/body_122.png
cp ../images/PokeBody/body_103.png ./out/Assets/Colosseum/body_103.png
cp ../images/PokeBody/body_253.png ./out/Assets/Colosseum/body_253.png
cp ../images/PokeFace/face_018.png ./out/Assets/Colosseum/face_018.png
cp ../images/PokeFace/face_320.png ./out/Assets/Colosseum/face_320.png
cp ../images/PokeBody/body_318.png ./out/Assets/Colosseum/body_318.png
cp ../images/PokeBody/body_360.png ./out/Assets/Colosseum/body_360.png
cp ../images/PokeBody/body_284.png ./out/Assets/Colosseum/body_284.png
cp ../images/ColoTrainers/colo_trainer_17.png ./out/Assets/Colosseum/colo_trainer_17.png
cp ../images/PokeBody/body_192.png ./out/Assets/Colosseum/body_192.png
cp ../images/PokeBody/body_286.png ./out/Assets/Colosseum/body_286.png
cp ../images/PokeBody/body_031.png ./out/Assets/Colosseum/body_031.png
cp ../images/PokeBody/body_283.png ./out/Assets/Colosseum/body_283.png
cp ../images/PokeFace/face_314.png ./out/Assets/Colosseum/face_314.png
cp ../images/PokeFace/face_071.png ./out/Assets/Colosseum/face_071.png
cp ../images/PokeFace/face_214.png ./out/Assets/Colosseum/face_214.png
cp ../images/PokeBody/body_305.png ./out/Assets/Colosseum/body_305.png
cp ../images/PokeBody/body_159.png ./out/Assets/Colosseum/body_159.png
cp ../images/PokeBody/body_069.png ./out/Assets/Colosseum/body_069.png
cp ../images/PokeFace/face_005.png ./out/Assets/Colosseum/face_005.png
cp ../images/PokeFace/face_201.png ./out/Assets/Colosseum/face_201.png
cp ../images/PokeBody/body_372.png ./out/Assets/Colosseum/body_372.png
cp ../images/PokeFace/face_221.png ./out/Assets/Colosseum/face_221.png
cp ../images/Types/type_11.png ./out/Assets/Colosseum/type_11.png
cp ../images/PokeBody/body_028.png ./out/Assets/Colosseum/body_028.png
cp ../images/PokeBody/body_134.png ./out/Assets/Colosseum/body_134.png
cp ../images/PokeBody/body_087.png ./out/Assets/Colosseum/body_087.png
cp ../images/PokeBody/body_400.png ./out/Assets/Colosseum/body_400.png
cp ../images/PokeFace/face_379.png ./out/Assets/Colosseum/face_379.png
cp ../images/PokeFace/face_290.png ./out/Assets/Colosseum/face_290.png
cp ../images/PokeFace/face_359.png ./out/Assets/Colosseum/face_359.png
cp ../images/PokeFace/face_227.png ./out/Assets/Colosseum/face_227.png
cp ../images/Types/type_10.png ./out/Assets/Colosseum/type_10.png
cp ../images/PokeFace/face_095.png ./out/Assets/Colosseum/face_095.png
cp ../images/PokeBody/body_308.png ./out/Assets/Colosseum/body_308.png
cp ../images/PokeFace/face_283.png ./out/Assets/Colosseum/face_283.png
cp ../images/PokeBody/body_155.png ./out/Assets/Colosseum/body_155.png
cp ../images/PokeBody/body_399.png ./out/Assets/Colosseum/body_399.png
cp ../images/PokeFace/face_181.png ./out/Assets/Colosseum/face_181.png
cp ../images/PokeBody/body_373.png ./out/Assets/Colosseum/body_373.png
cp ../images/PokeFace/face_024.png ./out/Assets/Colosseum/face_024.png
cp ../images/PokeBody/body_153.png ./out/Assets/Colosseum/body_153.png
cp ../images/PokeBody/body_241.png ./out/Assets/Colosseum/body_241.png
cp ../images/PokeBody/body_411.png ./out/Assets/Colosseum/body_411.png
cp ../images/PokeBody/body_050.png ./out/Assets/Colosseum/body_050.png
cp ../images/PokeFace/face_399.png ./out/Assets/Colosseum/face_399.png
cp ../images/PokeFace/face_121.png ./out/Assets/Colosseum/face_121.png
cp ../images/PokeBody/body_412.png ./out/Assets/Colosseum/body_412.png
cp ../images/PokeBody/body_022.png ./out/Assets/Colosseum/body_022.png
cp ../images/PokeFace/face_279.png ./out/Assets/Colosseum/face_279.png
cp ../images/Types/type_13.png ./out/Assets/Colosseum/type_13.png
cp ../images/PokeFace/face_138.png ./out/Assets/Colosseum/face_138.png
cp ../images/PokeBody/body_230.png ./out/Assets/Colosseum/body_230.png
cp ../images/PokeFace/face_052.png ./out/Assets/Colosseum/face_052.png
cp ../images/PokeFace/face_312.png ./out/Assets/Colosseum/face_312.png
cp ../images/PokeFace/face_272.png ./out/Assets/Colosseum/face_272.png
cp ../images/PokeFace/face_053.png ./out/Assets/Colosseum/face_053.png
cp ../images/Table\ View\ Cells/Item\ Cell.png ./out/Assets/Colosseum/Item\ Cell.png
cp ../images/PokeBody/body_257.png ./out/Assets/Colosseum/body_257.png
cp ../images/PokeFace/face_099.png ./out/Assets/Colosseum/face_099.png
cp ../images/PokeFace/face_170.png ./out/Assets/Colosseum/face_170.png
cp ../images/ColoTrainers/colo_trainer_54.png ./out/Assets/Colosseum/colo_trainer_54.png
cp ../images/PokeBody/body_197.png ./out/Assets/Colosseum/body_197.png
cp ../images/PokeFace/face_373.png ./out/Assets/Colosseum/face_373.png
cp ../images/ColoTrainers/colo_trainer_42.png ./out/Assets/Colosseum/colo_trainer_42.png
cp ../images/PokeBody/body_160.png ./out/Assets/Colosseum/body_160.png
cp ../images/PokeBody/body_139.png ./out/Assets/Colosseum/body_139.png
cp ../images/ColoTrainers/colo_trainer_11.png ./out/Assets/Colosseum/colo_trainer_11.png
cp ../JSON/XD/Moves\ raw.json ./out/Assets/Colosseum/Moves\ raw.json
cp ../images/PokeBody/body_304.png ./out/Assets/Colosseum/body_304.png
cp ../images/PokeBody/body_292.png ./out/Assets/Colosseum/body_292.png
cp ../images/PokeBody/body_114.png ./out/Assets/Colosseum/body_114.png
cp ../images/PokeBody/body_091.png ./out/Assets/Colosseum/body_091.png
cp ../images/PokeFace/face_409.png ./out/Assets/Colosseum/face_409.png
cp ../images/PokeBody/body_348.png ./out/Assets/Colosseum/body_348.png
cp ../images/PokeBody/body_198.png ./out/Assets/Colosseum/body_198.png
cp ../images/PokeBody/body_401.png ./out/Assets/Colosseum/body_401.png
cp ../images/PokeFace/face_215.png ./out/Assets/Colosseum/face_215.png
cp ../images/PokeFace/face_123.png ./out/Assets/Colosseum/face_123.png
cp ../images/PokeBody/body_265.png ./out/Assets/Colosseum/body_265.png
cp ../images/PokeBody/body_043.png ./out/Assets/Colosseum/body_043.png
cp ../images/PokeBody/body_276.png ./out/Assets/Colosseum/body_276.png
cp ../images/PokeBody/body_315.png ./out/Assets/Colosseum/body_315.png
cp ../images/PokeBody/body_303.png ./out/Assets/Colosseum/body_303.png
cp ../images/PokeFace/face_231.png ./out/Assets/Colosseum/face_231.png
cp ../images/PokeFace/face_152.png ./out/Assets/Colosseum/face_152.png
cp ../images/PokeBody/body_374.png ./out/Assets/Colosseum/body_374.png
cp ../images/PokeBody/body_096.png ./out/Assets/Colosseum/body_096.png
cp ../images/Types/type_2.png ./out/Assets/Colosseum/type_2.png
cp ../images/ColoTrainers/colo_trainer_16.png ./out/Assets/Colosseum/colo_trainer_16.png
cp ../images/PokeFace/face_392.png ./out/Assets/Colosseum/face_392.png
cp ../images/ColoTrainers/colo_trainer_73.png ./out/Assets/Colosseum/colo_trainer_73.png
cp ../images/PokeFace/face_164.png ./out/Assets/Colosseum/face_164.png
cp ../images/PokeFace/face_256.png ./out/Assets/Colosseum/face_256.png
cp ../images/PokeBody/body_337.png ./out/Assets/Colosseum/body_337.png
cp ../images/PokeBody/body_271.png ./out/Assets/Colosseum/body_271.png
cp ../images/PokeFace/face_271.png ./out/Assets/Colosseum/face_271.png
cp ../images/ColoTrainers/colo_trainer_19.png ./out/Assets/Colosseum/colo_trainer_19.png
cp ../images/PokeFace/face_335.png ./out/Assets/Colosseum/face_335.png
cp ../images/PokeBody/body_176.png ./out/Assets/Colosseum/body_176.png
cp ../images/PokeFace/face_311.png ./out/Assets/Colosseum/face_311.png
cp ../images/PokeBody/body_206.png ./out/Assets/Colosseum/body_206.png
cp ../images/PokeBody/body_214.png ./out/Assets/Colosseum/body_214.png
cp ../images/ColoTrainers/colo_trainer_25.png ./out/Assets/Colosseum/colo_trainer_25.png
cp ../images/PokeFace/face_305.png ./out/Assets/Colosseum/face_305.png
cp ../images/PokeFace/face_356.png ./out/Assets/Colosseum/face_356.png
cp ../JSON/XD/Pokemon\ Stats\ raw.json ./out/Assets/Colosseum/Pokemon\ Stats\ raw.json
cp ../images/PokeBody/body_260.png ./out/Assets/Colosseum/body_260.png
cp ../images/PokeBody/body_389.png ./out/Assets/Colosseum/body_389.png
cp ../images/PokeFace/face_151.png ./out/Assets/Colosseum/face_151.png
cp ../images/PokeBody/body_297.png ./out/Assets/Colosseum/body_297.png
cp ../images/PokeFace/face_278.png ./out/Assets/Colosseum/face_278.png
cp ../images/PokeBody/body_320.png ./out/Assets/Colosseum/body_320.png
cp ../images/PokeFace/face_049.png ./out/Assets/Colosseum/face_049.png
cp ../images/PokeBody/body_293.png ./out/Assets/Colosseum/body_293.png
cp ../images/PokeBody/body_090.png ./out/Assets/Colosseum/body_090.png
cp ../images/PokeBody/body_183.png ./out/Assets/Colosseum/body_183.png
cp ../images/PokeBody/body_392.png ./out/Assets/Colosseum/body_392.png
cp ../images/ColoTrainers/colo_trainer_38.png ./out/Assets/Colosseum/colo_trainer_38.png
cp ../images/PokeBody/body_013.png ./out/Assets/Colosseum/body_013.png
cp ../images/PokeFace/face_289.png ./out/Assets/Colosseum/face_289.png
cp ../images/ColoTrainers/colo_trainer_74.png ./out/Assets/Colosseum/colo_trainer_74.png
cp ../images/PokeBody/body_080.png ./out/Assets/Colosseum/body_080.png
cp ../images/PokeFace/face_019.png ./out/Assets/Colosseum/face_019.png
cp ../images/PokeBody/body_404.png ./out/Assets/Colosseum/body_404.png
cp ../images/PokeFace/face_075.png ./out/Assets/Colosseum/face_075.png
cp ../images/PokeBody/body_150.png ./out/Assets/Colosseum/body_150.png
cp ../images/PokeBody/body_098.png ./out/Assets/Colosseum/body_098.png
cp ../images/PokeBody/body_251.png ./out/Assets/Colosseum/body_251.png
cp ../images/ColoTrainers/colo_trainer_15.png ./out/Assets/Colosseum/colo_trainer_15.png
cp ../images/PokeBody/body_275.png ./out/Assets/Colosseum/body_275.png
cp ../images/ColoTrainers/colo_trainer_13.png ./out/Assets/Colosseum/colo_trainer_13.png
cp ../images/PokeFace/face_366.png ./out/Assets/Colosseum/face_366.png
cp ../images/PokeBody/body_358.png ./out/Assets/Colosseum/body_358.png
cp ../images/PokeBody/body_403.png ./out/Assets/Colosseum/body_403.png
cp ../images/PokeFace/face_031.png ./out/Assets/Colosseum/face_031.png
cp ../images/PokeBody/body_149.png ./out/Assets/Colosseum/body_149.png
cp ../images/PokeFace/face_140.png ./out/Assets/Colosseum/face_140.png
cp ../images/ColoTrainers/colo_trainer_29.png ./out/Assets/Colosseum/colo_trainer_29.png
cp ../images/PokeBody/body_086.png ./out/Assets/Colosseum/body_086.png
cp ../images/PokeFace/face_135.png ./out/Assets/Colosseum/face_135.png
cp ../images/PokeFace/face_047.png ./out/Assets/Colosseum/face_047.png
cp ../images/PokeFace/face_313.png ./out/Assets/Colosseum/face_313.png
cp ../images/PokeBody/body_106.png ./out/Assets/Colosseum/body_106.png
cp ../images/PokeBody/body_228.png ./out/Assets/Colosseum/body_228.png
cp ../images/PokeFace/face_388.png ./out/Assets/Colosseum/face_388.png
cp ../images/PokeFace/face_352.png ./out/Assets/Colosseum/face_352.png
cp ../images/PokeBody/body_120.png ./out/Assets/Colosseum/body_120.png
cp ../images/PokeBody/body_154.png ./out/Assets/Colosseum/body_154.png
cp ../images/PokeFace/face_337.png ./out/Assets/Colosseum/face_337.png
cp ../images/PokeBody/body_317.png ./out/Assets/Colosseum/body_317.png
cp ../images/PokeFace/face_389.png ./out/Assets/Colosseum/face_389.png
cp ../images/ColoTrainers/colo_trainer_49.png ./out/Assets/Colosseum/colo_trainer_49.png
cp ../images/PokeBody/body_004.png ./out/Assets/Colosseum/body_004.png
cp ../images/PokeFace/face_300.png ./out/Assets/Colosseum/face_300.png
cp ../images/PokeFace/face_055.png ./out/Assets/Colosseum/face_055.png
cp ../images/PokeBody/body_138.png ./out/Assets/Colosseum/body_138.png
cp ../images/PokeBody/body_163.png ./out/Assets/Colosseum/body_163.png
cp ../images/PokeFace/face_318.png ./out/Assets/Colosseum/face_318.png
cp ../images/PokeBody/body_405.png ./out/Assets/Colosseum/body_405.png
cp ../images/PokeBody/body_247.png ./out/Assets/Colosseum/body_247.png
cp ../images/PokeBody/body_077.png ./out/Assets/Colosseum/body_077.png
cp ../images/PokeFace/face_169.png ./out/Assets/Colosseum/face_169.png
cp ../images/PokeFace/face_270.png ./out/Assets/Colosseum/face_270.png
cp ../images/PokeBody/body_152.png ./out/Assets/Colosseum/body_152.png
cp ../images/PokeBody/body_020.png ./out/Assets/Colosseum/body_020.png
cp ../images/PokeFace/face_186.png ./out/Assets/Colosseum/face_186.png
cp ../images/PokeFace/face_341.png ./out/Assets/Colosseum/face_341.png
cp ../images/ColoTrainers/colo_trainer_61.png ./out/Assets/Colosseum/colo_trainer_61.png
cp ../images/PokeBody/body_037.png ./out/Assets/Colosseum/body_037.png
cp ../images/PokeFace/face_106.png ./out/Assets/Colosseum/face_106.png
cp ../images/PokeFace/face_284.png ./out/Assets/Colosseum/face_284.png
cp ../images/PokeBody/body_325.png ./out/Assets/Colosseum/body_325.png
cp ../images/PokeFace/face_210.png ./out/Assets/Colosseum/face_210.png
cp ../images/PokeFace/face_163.png ./out/Assets/Colosseum/face_163.png
cp ../images/PokeBody/body_299.png ./out/Assets/Colosseum/body_299.png
cp ../images/PokeBody/body_067.png ./out/Assets/Colosseum/body_067.png
cp ../images/PokeBody/body_290.png ./out/Assets/Colosseum/body_290.png
cp ../images/PokeBody/body_015.png ./out/Assets/Colosseum/body_015.png
cp ../images/PokeFace/face_058.png ./out/Assets/Colosseum/face_058.png
cp ../images/PokeBody/body_039.png ./out/Assets/Colosseum/body_039.png
cp ../images/PokeBody/body_083.png ./out/Assets/Colosseum/body_083.png
cp ../images/PokeFace/face_068.png ./out/Assets/Colosseum/face_068.png
cp ../images/PokeBody/body_130.png ./out/Assets/Colosseum/body_130.png
cp ../images/PokeBody/body_027.png ./out/Assets/Colosseum/body_027.png
cp ../images/Types/type_8.png ./out/Assets/Colosseum/type_8.png
cp ../images/PokeFace/face_291.png ./out/Assets/Colosseum/face_291.png
cp ../images/PokeBody/body_038.png ./out/Assets/Colosseum/body_038.png
cp ../images/PokeBody/body_340.png ./out/Assets/Colosseum/body_340.png
cp ../images/PokeBody/body_306.png ./out/Assets/Colosseum/body_306.png
cp ../images/PokeBody/body_218.png ./out/Assets/Colosseum/body_218.png
cp ../images/PokeBody/body_295.png ./out/Assets/Colosseum/body_295.png
cp ../images/PokeBody/body_119.png ./out/Assets/Colosseum/body_119.png
cp ../images/PokeFace/face_156.png ./out/Assets/Colosseum/face_156.png
cp ../images/PokeBody/body_394.png ./out/Assets/Colosseum/body_394.png
cp ../images/ColoTrainers/colo_trainer_67.png ./out/Assets/Colosseum/colo_trainer_67.png
cp ../images/PokeBody/body_351.png ./out/Assets/Colosseum/body_351.png
cp ../images/PokeFace/face_381.png ./out/Assets/Colosseum/face_381.png
cp ../images/PokeBody/body_115.png ./out/Assets/Colosseum/body_115.png
cp ../images/PokeBody/body_044.png ./out/Assets/Colosseum/body_044.png
cp ../images/PokeBody/body_166.png ./out/Assets/Colosseum/body_166.png
cp ../images/PokeFace/face_280.png ./out/Assets/Colosseum/face_280.png
cp ../images/PokeFace/face_374.png ./out/Assets/Colosseum/face_374.png
cp ../images/PokeFace/face_122.png ./out/Assets/Colosseum/face_122.png
cp ../images/PokeFace/face_219.png ./out/Assets/Colosseum/face_219.png
cp ../images/PokeFace/face_397.png ./out/Assets/Colosseum/face_397.png
cp ../images/PokeFace/face_017.png ./out/Assets/Colosseum/face_017.png
cp ../images/PokeFace/face_273.png ./out/Assets/Colosseum/face_273.png
cp ../images/PokeBody/body_097.png ./out/Assets/Colosseum/body_097.png
cp ../images/ColoTrainers/colo_trainer_51.png ./out/Assets/Colosseum/colo_trainer_51.png
cp ../images/PokeBody/body_029.png ./out/Assets/Colosseum/body_029.png
cp ../images/PokeFace/face_346.png ./out/Assets/Colosseum/face_346.png
cp ../images/PokeBody/body_123.png ./out/Assets/Colosseum/body_123.png
cp ../images/PokeFace/face_294.png ./out/Assets/Colosseum/face_294.png
cp ../images/PokeBody/body_081.png ./out/Assets/Colosseum/body_081.png
cp ../images/PokeBody/body_323.png ./out/Assets/Colosseum/body_323.png
cp ../images/PokeFace/face_274.png ./out/Assets/Colosseum/face_274.png
cp ../images/PokeFace/face_084.png ./out/Assets/Colosseum/face_084.png
cp ../images/PokeFace/face_110.png ./out/Assets/Colosseum/face_110.png
cp ../images/PokeFace/face_077.png ./out/Assets/Colosseum/face_077.png
cp ../images/PokeBody/body_244.png ./out/Assets/Colosseum/body_244.png
cp ../images/PokeBody/body_262.png ./out/Assets/Colosseum/body_262.png
cp ../images/ColoTrainers/colo_trainer_14.png ./out/Assets/Colosseum/colo_trainer_14.png
cp ../images/PokeFace/face_224.png ./out/Assets/Colosseum/face_224.png
cp ../images/PokeBody/body_173.png ./out/Assets/Colosseum/body_173.png
cp ../images/PokeFace/face_006.png ./out/Assets/Colosseum/face_006.png
cp ../images/PokeFace/face_239.png ./out/Assets/Colosseum/face_239.png
cp ../images/ColoTrainers/colo_trainer_5.png ./out/Assets/Colosseum/colo_trainer_5.png
cp ../images/PokeBody/body_267.png ./out/Assets/Colosseum/body_267.png
cp ../images/PokeBody/body_406.png ./out/Assets/Colosseum/body_406.png
cp ../images/ColoTrainers/colo_trainer_20.png ./out/Assets/Colosseum/colo_trainer_20.png
cp ../images/PokeFace/face_394.png ./out/Assets/Colosseum/face_394.png
cp ../images/PokeFace/face_398.png ./out/Assets/Colosseum/face_398.png
cp ../images/ColoTrainers/colo_trainer_66.png ./out/Assets/Colosseum/colo_trainer_66.png
cp ../JSON/Colosseum/Original\ Moves.json ./out/Assets/Colosseum/Original\ Moves.json
cp ../images/PokeBody/body_221.png ./out/Assets/Colosseum/body_221.png
cp ../images/ColoTrainers/colo_trainer_70.png ./out/Assets/Colosseum/colo_trainer_70.png
cp ../images/PokeBody/body_391.png ./out/Assets/Colosseum/body_391.png
cp ../images/PokeFace/face_362.png ./out/Assets/Colosseum/face_362.png
cp ../images/PokeBody/body_178.png ./out/Assets/Colosseum/body_178.png
cp ../images/PokeBody/body_108.png ./out/Assets/Colosseum/body_108.png
cp ../images/PokeBody/body_376.png ./out/Assets/Colosseum/body_376.png
cp ../JSON/XD/Original\ Pokemon.json ./out/Assets/Colosseum/Original\ Pokemon.json
cp ../images/ColoTrainers/colo_trainer_48.png ./out/Assets/Colosseum/colo_trainer_48.png
cp ../images/PokeBody/body_282.png ./out/Assets/Colosseum/body_282.png
cp ../images/PokeFace/face_208.png ./out/Assets/Colosseum/face_208.png
cp ../images/PokeFace/face_393.png ./out/Assets/Colosseum/face_393.png
cp ../images/PokeBody/body_249.png ./out/Assets/Colosseum/body_249.png
cp ../images/PokeFace/face_188.png ./out/Assets/Colosseum/face_188.png
cp ../images/PokeFace/face_032.png ./out/Assets/Colosseum/face_032.png
cp ../images/PokeBody/body_288.png ./out/Assets/Colosseum/body_288.png
cp ../images/PokeFace/face_405.png ./out/Assets/Colosseum/face_405.png
cp ../images/PokeFace/face_321.png ./out/Assets/Colosseum/face_321.png
cp ../JSON/XD/Items.json ./out/Assets/Colosseum/Items.json
cp ../images/PokeBody/body_171.png ./out/Assets/Colosseum/body_171.png
cp ../images/PokeFace/face_165.png ./out/Assets/Colosseum/face_165.png
cp ../images/PokeBody/body_065.png ./out/Assets/Colosseum/body_065.png
cp ../images/PokeBody/body_362.png ./out/Assets/Colosseum/body_362.png
cp ../images/PokeFace/face_361.png ./out/Assets/Colosseum/face_361.png
cp ../images/PokeFace/face_111.png ./out/Assets/Colosseum/face_111.png
cp ../images/PokeBody/body_266.png ./out/Assets/Colosseum/body_266.png
cp ../images/PokeBody/body_336.png ./out/Assets/Colosseum/body_336.png
cp ../images/PokeFace/face_226.png ./out/Assets/Colosseum/face_226.png
cp ../images/PokeFace/face_026.png ./out/Assets/Colosseum/face_026.png
cp ../images/PokeFace/face_187.png ./out/Assets/Colosseum/face_187.png
cp ../images/Types/type_12.png ./out/Assets/Colosseum/type_12.png
cp ../images/PokeFace/face_242.png ./out/Assets/Colosseum/face_242.png
cp ../images/PokeFace/face_382.png ./out/Assets/Colosseum/face_382.png
cp ../images/PokeBody/body_131.png ./out/Assets/Colosseum/body_131.png
cp ../images/PokeFace/face_083.png ./out/Assets/Colosseum/face_083.png
cp ../images/PokeFace/face_403.png ./out/Assets/Colosseum/face_403.png
cp ../images/PokeBody/body_264.png ./out/Assets/Colosseum/body_264.png
cp ../images/PokeFace/face_241.png ./out/Assets/Colosseum/face_241.png
cp ../images/PokeFace/face_277.png ./out/Assets/Colosseum/face_277.png
cp ../Sublime/CM/CMScript.sublime-color-scheme ./out/Assets/Colosseum/CMScript.sublime-color-scheme
cp ../images/PokeBody/body_132.png ./out/Assets/Colosseum/body_132.png
cp ../images/PokeBody/body_093.png ./out/Assets/Colosseum/body_093.png
cp ../images/PokeFace/face_276.png ./out/Assets/Colosseum/face_276.png
cp ../images/PokeBody/body_207.png ./out/Assets/Colosseum/body_207.png
cp ../images/PokeFace/face_157.png ./out/Assets/Colosseum/face_157.png
cp ../images/PokeBalls/ball\ red.png ./out/Assets/Colosseum/ball\ red.png
cp ../images/PokeFace/face_016.png ./out/Assets/Colosseum/face_016.png
cp ../images/PokeBody/body_369.png ./out/Assets/Colosseum/body_369.png
cp ../images/PokeFace/face_132.png ./out/Assets/Colosseum/face_132.png
cp ../images/PokeBody/body_048.png ./out/Assets/Colosseum/body_048.png
cp ../images/PokeFace/face_175.png ./out/Assets/Colosseum/face_175.png
cp ../images/PokeFace/face_177.png ./out/Assets/Colosseum/face_177.png
cp ../images/PokeBody/body_141.png ./out/Assets/Colosseum/body_141.png
cp ../images/PokeBody/body_116.png ./out/Assets/Colosseum/body_116.png
cp ../JSON/Colosseum/Move\ Effects.json ./out/Assets/Colosseum/Move\ Effects.json
cp ../images/PokeBody/body_058.png ./out/Assets/Colosseum/body_058.png
cp ../images/PokeBody/body_107.png ./out/Assets/Colosseum/body_107.png
cp ../images/PokeBody/body_342.png ./out/Assets/Colosseum/body_342.png
cp ../images/PokeFace/face_158.png ./out/Assets/Colosseum/face_158.png
cp ../images/PokeBody/body_402.png ./out/Assets/Colosseum/body_402.png
cp ../images/PokeFace/face_062.png ./out/Assets/Colosseum/face_062.png
cp ../images/PokeBody/body_414.png ./out/Assets/Colosseum/body_414.png
cp ../images/PokeBody/body_365.png ./out/Assets/Colosseum/body_365.png
cp ../images/PokeFace/face_073.png ./out/Assets/Colosseum/face_073.png
cp ../images/PokeFace/face_015.png ./out/Assets/Colosseum/face_015.png
cp ../images/PokeBody/body_057.png ./out/Assets/Colosseum/body_057.png
cp ../images/PokeFace/face_395.png ./out/Assets/Colosseum/face_395.png
cp ../images/PokeFace/face_021.png ./out/Assets/Colosseum/face_021.png
cp ../images/PokeBody/body_217.png ./out/Assets/Colosseum/body_217.png
cp ../images/ColoTrainers/colo_trainer_36.png ./out/Assets/Colosseum/colo_trainer_36.png
cp ../images/PokeBody/body_085.png ./out/Assets/Colosseum/body_085.png
cp ../images/PokeFace/face_048.png ./out/Assets/Colosseum/face_048.png
cp ../images/PokeFace/face_128.png ./out/Assets/Colosseum/face_128.png
cp ../images/PokeFace/face_038.png ./out/Assets/Colosseum/face_038.png
cp ../images/PokeBody/body_051.png ./out/Assets/Colosseum/body_051.png
cp ../images/PokeFace/face_292.png ./out/Assets/Colosseum/face_292.png
cp ../images/PokeBody/body_310.png ./out/Assets/Colosseum/body_310.png
cp ../images/PokeFace/face_301.png ./out/Assets/Colosseum/face_301.png
cp ../images/PokeFace/face_411.png ./out/Assets/Colosseum/face_411.png
cp ../images/PokeBody/body_199.png ./out/Assets/Colosseum/body_199.png
cp ../images/PokeFace/face_183.png ./out/Assets/Colosseum/face_183.png
cp ../images/PokeBody/body_314.png ./out/Assets/Colosseum/body_314.png
cp ../images/PokeFace/face_046.png ./out/Assets/Colosseum/face_046.png
cp ../images/Types/type_7.png ./out/Assets/Colosseum/type_7.png
cp ../images/PokeBody/body_280.png ./out/Assets/Colosseum/body_280.png
cp ../images/PokeFace/face_404.png ./out/Assets/Colosseum/face_404.png
cp ../images/PokeBody/body_268.png ./out/Assets/Colosseum/body_268.png
cp ../images/PokeFace/face_007.png ./out/Assets/Colosseum/face_007.png
cp ../images/PokeFace/face_230.png ./out/Assets/Colosseum/face_230.png
cp ../images/PokeBody/body_061.png ./out/Assets/Colosseum/body_061.png
cp ../images/PokeBody/body_007.png ./out/Assets/Colosseum/body_007.png
cp ../images/ColoTrainers/colo_trainer_62.png ./out/Assets/Colosseum/colo_trainer_62.png
cp ../images/PokeBody/body_084.png ./out/Assets/Colosseum/body_084.png
cp ../images/PokeFace/face_079.png ./out/Assets/Colosseum/face_079.png
cp ../images/PokeBody/body_045.png ./out/Assets/Colosseum/body_045.png
cp ../images/PokeBody/body_070.png ./out/Assets/Colosseum/body_070.png
cp ../images/Table\ View\ Cells/Selected\ Cell.png ./out/Assets/Colosseum/Selected\ Cell.png
cp ../images/PokeBody/body_064.png ./out/Assets/Colosseum/body_064.png
cp ../images/PokeFace/face_126.png ./out/Assets/Colosseum/face_126.png
cp ../images/PokeBody/body_368.png ./out/Assets/Colosseum/body_368.png
cp ../images/PokeFace/face_322.png ./out/Assets/Colosseum/face_322.png
cp ../images/ColoTrainers/colo_trainer_3.png ./out/Assets/Colosseum/colo_trainer_3.png
cp ../images/PokeBody/body_035.png ./out/Assets/Colosseum/body_035.png
cp ../images/PokeBody/body_019.png ./out/Assets/Colosseum/body_019.png
cp ../images/PokeFace/face_000.png ./out/Assets/Colosseum/face_000.png
cp ../images/PokeBody/body_095.png ./out/Assets/Colosseum/body_095.png
cp ../images/PokeBody/body_298.png ./out/Assets/Colosseum/body_298.png
cp ../images/PokeFace/face_209.png ./out/Assets/Colosseum/face_209.png
cp ../images/PokeBody/body_386.png ./out/Assets/Colosseum/body_386.png
cp ../images/PokeBody/body_408.png ./out/Assets/Colosseum/body_408.png
cp ../images/ColoTrainers/colo_trainer_72.png ./out/Assets/Colosseum/colo_trainer_72.png
cp ../images/PokeFace/face_400.png ./out/Assets/Colosseum/face_400.png
cp ../images/PokeBody/body_245.png ./out/Assets/Colosseum/body_245.png
cp ../images/PokeBody/body_301.png ./out/Assets/Colosseum/body_301.png
cp ../images/PokeFace/face_153.png ./out/Assets/Colosseum/face_153.png
cp ../images/PokeBody/body_147.png ./out/Assets/Colosseum/body_147.png
cp ../images/PokeBody/body_101.png ./out/Assets/Colosseum/body_101.png
cp ../images/PokeFace/face_104.png ./out/Assets/Colosseum/face_104.png
cp ../images/PokeFace/face_003.png ./out/Assets/Colosseum/face_003.png
cp ../images/PokeFace/face_173.png ./out/Assets/Colosseum/face_173.png
cp ../images/PokeFace/face_339.png ./out/Assets/Colosseum/face_339.png
cp ../images/PokeFace/face_205.png ./out/Assets/Colosseum/face_205.png
cp ../images/PokeBody/body_002.png ./out/Assets/Colosseum/body_002.png
cp ../images/PokeFace/face_074.png ./out/Assets/Colosseum/face_074.png
cp ../images/PokeFace/face_222.png ./out/Assets/Colosseum/face_222.png
cp ../images/PokeBody/body_074.png ./out/Assets/Colosseum/body_074.png
cp ../images/PokeBody/body_026.png ./out/Assets/Colosseum/body_026.png
cp ../images/PokeFace/face_365.png ./out/Assets/Colosseum/face_365.png
cp ../images/PokeFace/face_288.png ./out/Assets/Colosseum/face_288.png
cp ../images/PokeBody/body_357.png ./out/Assets/Colosseum/body_357.png
cp ../images/PokeFace/face_028.png ./out/Assets/Colosseum/face_028.png
cp ../images/PokeBody/body_229.png ./out/Assets/Colosseum/body_229.png
cp ../images/PokeBody/body_366.png ./out/Assets/Colosseum/body_366.png
cp ../images/PokeBody/body_094.png ./out/Assets/Colosseum/body_094.png
cp ../images/PokeBody/body_235.png ./out/Assets/Colosseum/body_235.png
cp ../images/PokeFace/face_176.png ./out/Assets/Colosseum/face_176.png
cp ../images/PokeFace/face_383.png ./out/Assets/Colosseum/face_383.png
cp ../images/PokeFace/face_197.png ./out/Assets/Colosseum/face_197.png
cp ../images/PokeBody/body_201.png ./out/Assets/Colosseum/body_201.png
cp ../images/ColoTrainers/colo_trainer_21.png ./out/Assets/Colosseum/colo_trainer_21.png
cp ../images/PokeFace/face_380.png ./out/Assets/Colosseum/face_380.png
cp ../images/PokeBody/body_333.png ./out/Assets/Colosseum/body_333.png
cp ../images/PokeFace/face_281.png ./out/Assets/Colosseum/face_281.png
cp ../images/PokeFace/face_254.png ./out/Assets/Colosseum/face_254.png
cp ../images/PokeFace/face_343.png ./out/Assets/Colosseum/face_343.png
cp ../images/PokeBody/body_105.png ./out/Assets/Colosseum/body_105.png
cp ../images/PokeFace/face_147.png ./out/Assets/Colosseum/face_147.png
cp ../images/PokeBody/body_409.png ./out/Assets/Colosseum/body_409.png
cp ../images/PokeBody/body_255.png ./out/Assets/Colosseum/body_255.png
cp ../images/PokeBody/body_179.png ./out/Assets/Colosseum/body_179.png
cp ../images/PokeFace/face_081.png ./out/Assets/Colosseum/face_081.png
cp ../images/PokeFace/face_050.png ./out/Assets/Colosseum/face_050.png
cp ../images/PokeFace/face_263.png ./out/Assets/Colosseum/face_263.png
cp ../images/PokeBody/body_239.png ./out/Assets/Colosseum/body_239.png
cp ../images/PokeFace/face_100.png ./out/Assets/Colosseum/face_100.png
cp ../images/PokeBody/body_144.png ./out/Assets/Colosseum/body_144.png
cp ../images/PokeFace/face_315.png ./out/Assets/Colosseum/face_315.png
cp ../images/PokeBody/body_222.png ./out/Assets/Colosseum/body_222.png
cp ../images/PokeBody/body_062.png ./out/Assets/Colosseum/body_062.png
cp ../images/ColoTrainers/colo_trainer_44.png ./out/Assets/Colosseum/colo_trainer_44.png
cp ../images/PokeBody/body_246.png ./out/Assets/Colosseum/body_246.png
cp ../images/PokeFace/face_213.png ./out/Assets/Colosseum/face_213.png
cp ../images/PokeFace/face_331.png ./out/Assets/Colosseum/face_331.png
cp ../images/PokeBody/body_024.png ./out/Assets/Colosseum/body_024.png
cp ../images/PokeBody/body_219.png ./out/Assets/Colosseum/body_219.png
cp ../images/PokeFace/face_269.png ./out/Assets/Colosseum/face_269.png
cp ../images/PokeBody/body_000.png ./out/Assets/Colosseum/body_000.png
cp ../images/PokeFace/face_162.png ./out/Assets/Colosseum/face_162.png
cp ../images/PokeFace/face_286.png ./out/Assets/Colosseum/face_286.png
cp ../images/PokeFace/face_253.png ./out/Assets/Colosseum/face_253.png
cp ../images/PokeFace/face_372.png ./out/Assets/Colosseum/face_372.png
cp ../images/PokeBody/body_157.png ./out/Assets/Colosseum/body_157.png
cp ../images/PokeFace/face_298.png ./out/Assets/Colosseum/face_298.png
cp ../images/PokeBody/body_248.png ./out/Assets/Colosseum/body_248.png
cp ../images/PokeBody/body_270.png ./out/Assets/Colosseum/body_270.png
cp ../images/PokeBody/body_158.png ./out/Assets/Colosseum/body_158.png
cp ../images/PokeBody/body_327.png ./out/Assets/Colosseum/body_327.png
cp ../images/PokeBody/body_274.png ./out/Assets/Colosseum/body_274.png
cp ../images/PokeFace/face_328.png ./out/Assets/Colosseum/face_328.png
cp ../images/PokeFace/face_041.png ./out/Assets/Colosseum/face_041.png
cp ../images/PokeBody/body_046.png ./out/Assets/Colosseum/body_046.png
cp ../images/PokeFace/face_377.png ./out/Assets/Colosseum/face_377.png
cp ../images/PokeBody/body_324.png ./out/Assets/Colosseum/body_324.png
cp ../images/PokeBody/body_231.png ./out/Assets/Colosseum/body_231.png
cp ../images/ColoTrainers/colo_trainer_27.png ./out/Assets/Colosseum/colo_trainer_27.png
cp ../images/PokeFace/face_287.png ./out/Assets/Colosseum/face_287.png
cp ../images/PokeFace/face_194.png ./out/Assets/Colosseum/face_194.png
cp ../images/PokeBody/body_032.png ./out/Assets/Colosseum/body_032.png
cp ../images/PokeBody/body_263.png ./out/Assets/Colosseum/body_263.png
cp ../images/PokeBody/body_126.png ./out/Assets/Colosseum/body_126.png
cp ../images/ColoTrainers/colo_trainer_18.png ./out/Assets/Colosseum/colo_trainer_18.png
cp ../images/PokeBody/body_049.png ./out/Assets/Colosseum/body_049.png
cp ../images/ColoTrainers/colo_trainer_46.png ./out/Assets/Colosseum/colo_trainer_46.png
cp ../images/PokeFace/face_131.png ./out/Assets/Colosseum/face_131.png
cp ../images/PokeBody/body_014.png ./out/Assets/Colosseum/body_014.png
cp ../images/PokeBody/body_170.png ./out/Assets/Colosseum/body_170.png
cp ../images/PokeFace/face_105.png ./out/Assets/Colosseum/face_105.png
cp ../images/PokeBody/body_213.png ./out/Assets/Colosseum/body_213.png
cp ../images/ColoTrainers/colo_trainer_59.png ./out/Assets/Colosseum/colo_trainer_59.png
cp ../images/PokeFace/face_130.png ./out/Assets/Colosseum/face_130.png
cp ../images/Types/type_17.png ./out/Assets/Colosseum/type_17.png
cp ../images/PokeBody/body_225.png ./out/Assets/Colosseum/body_225.png
cp ../images/PokeFace/face_112.png ./out/Assets/Colosseum/face_112.png
cp ../images/PokeBody/body_343.png ./out/Assets/Colosseum/body_343.png
cp ../images/PokeBody/body_100.png ./out/Assets/Colosseum/body_100.png
cp ../images/PokeFace/face_034.png ./out/Assets/Colosseum/face_034.png
cp ../images/PokeFace/face_043.png ./out/Assets/Colosseum/face_043.png
cp ../images/PokeFace/face_243.png ./out/Assets/Colosseum/face_243.png
cp ../images/PokeFace/face_092.png ./out/Assets/Colosseum/face_092.png
cp ../images/PokeFace/face_125.png ./out/Assets/Colosseum/face_125.png
cp ../images/PokeFace/face_067.png ./out/Assets/Colosseum/face_067.png
cp ../images/PokeBody/body_165.png ./out/Assets/Colosseum/body_165.png
cp ../images/PokeFace/face_116.png ./out/Assets/Colosseum/face_116.png
cp ../images/PokeBody/body_281.png ./out/Assets/Colosseum/body_281.png
cp ../images/PokeFace/face_296.png ./out/Assets/Colosseum/face_296.png
cp ../images/PokeBody/body_185.png ./out/Assets/Colosseum/body_185.png
cp ../images/PokeBody/body_001.png ./out/Assets/Colosseum/body_001.png
cp ../images/PokeBody/body_177.png ./out/Assets/Colosseum/body_177.png
cp ../images/PokeBody/body_393.png ./out/Assets/Colosseum/body_393.png
cp ../images/PokeBody/body_195.png ./out/Assets/Colosseum/body_195.png
cp ../images/PokeBody/body_143.png ./out/Assets/Colosseum/body_143.png
cp ../images/ColoTrainers/colo_trainer_35.png ./out/Assets/Colosseum/colo_trainer_35.png
cp ../images/PokeFace/face_097.png ./out/Assets/Colosseum/face_097.png
cp ../images/PokeFace/face_306.png ./out/Assets/Colosseum/face_306.png
cp ../images/PokeFace/face_172.png ./out/Assets/Colosseum/face_172.png
cp ../images/PokeFace/face_367.png ./out/Assets/Colosseum/face_367.png
cp ../images/PokeBody/body_042.png ./out/Assets/Colosseum/body_042.png
cp ../images/PokeBody/body_329.png ./out/Assets/Colosseum/body_329.png
cp ../images/PokeFace/face_408.png ./out/Assets/Colosseum/face_408.png
cp ../images/PokeFace/face_351.png ./out/Assets/Colosseum/face_351.png
cp ../images/PokeBody/body_252.png ./out/Assets/Colosseum/body_252.png
cp ../images/PokeBody/body_136.png ./out/Assets/Colosseum/body_136.png
cp ../images/PokeFace/face_309.png ./out/Assets/Colosseum/face_309.png
cp ../images/ColoTrainers/colo_trainer_57.png ./out/Assets/Colosseum/colo_trainer_57.png
cp ../images/ColoTrainers/colo_trainer_47.png ./out/Assets/Colosseum/colo_trainer_47.png
cp ../images/PokeFace/face_119.png ./out/Assets/Colosseum/face_119.png
cp ../images/PokeFace/face_145.png ./out/Assets/Colosseum/face_145.png
cp ../images/PokeFace/face_304.png ./out/Assets/Colosseum/face_304.png
cp ../images/PokeBody/body_187.png ./out/Assets/Colosseum/body_187.png
cp ../images/PokeFace/face_386.png ./out/Assets/Colosseum/face_386.png
cp ../images/PokeFace/face_255.png ./out/Assets/Colosseum/face_255.png
cp ../images/PokeFace/face_350.png ./out/Assets/Colosseum/face_350.png
cp ../images/Types/type_9.png ./out/Assets/Colosseum/type_9.png
cp ../images/ColoTrainers/colo_trainer_22.png ./out/Assets/Colosseum/colo_trainer_22.png
cp ../images/PokeFace/face_410.png ./out/Assets/Colosseum/face_410.png
cp ../images/PokeFace/face_259.png ./out/Assets/Colosseum/face_259.png
cp ../images/PokeFace/face_090.png ./out/Assets/Colosseum/face_090.png
cp ../images/PokeFace/face_396.png ./out/Assets/Colosseum/face_396.png
cp ../images/PokeBody/body_012.png ./out/Assets/Colosseum/body_012.png
cp ../images/PokeFace/face_051.png ./out/Assets/Colosseum/face_051.png
cp ../images/PokeFace/face_347.png ./out/Assets/Colosseum/face_347.png
cp ../images/PokeFace/face_323.png ./out/Assets/Colosseum/face_323.png
cp ../images/PokeBody/body_102.png ./out/Assets/Colosseum/body_102.png
cp ../images/ColoTrainers/colo_trainer_40.png ./out/Assets/Colosseum/colo_trainer_40.png
cp ../images/PokeBody/body_036.png ./out/Assets/Colosseum/body_036.png
cp ../images/PokeBody/body_313.png ./out/Assets/Colosseum/body_313.png
cp ../images/PokeFace/face_376.png ./out/Assets/Colosseum/face_376.png
cp ../images/PokeFace/face_149.png ./out/Assets/Colosseum/face_149.png
cp ../images/PokeFace/face_004.png ./out/Assets/Colosseum/face_004.png
cp ../images/PokeFace/face_228.png ./out/Assets/Colosseum/face_228.png
cp ../images/PokeBody/body_034.png ./out/Assets/Colosseum/body_034.png
cp ../images/PokeFace/face_195.png ./out/Assets/Colosseum/face_195.png
cp ../images/PokeFace/face_057.png ./out/Assets/Colosseum/face_057.png
cp ../images/PokeBody/body_410.png ./out/Assets/Colosseum/body_410.png
cp ../images/PokeFace/face_103.png ./out/Assets/Colosseum/face_103.png
cp ../images/PokeFace/face_391.png ./out/Assets/Colosseum/face_391.png
cp ../images/ColoTrainers/colo_trainer_39.png ./out/Assets/Colosseum/colo_trainer_39.png
cp ../images/PokeFace/face_070.png ./out/Assets/Colosseum/face_070.png
cp ../images/PokeBody/body_133.png ./out/Assets/Colosseum/body_133.png
cp ../images/PokeBody/body_377.png ./out/Assets/Colosseum/body_377.png
cp ../images/PokeBody/body_040.png ./out/Assets/Colosseum/body_040.png
cp ../images/ColoTrainers/colo_trainer_52.png ./out/Assets/Colosseum/colo_trainer_52.png
cp ../images/PokeBody/body_063.png ./out/Assets/Colosseum/body_063.png
cp ../images/PokeFace/face_212.png ./out/Assets/Colosseum/face_212.png
cp ../images/PokeFace/face_407.png ./out/Assets/Colosseum/face_407.png
cp ../images/PokeBody/body_279.png ./out/Assets/Colosseum/body_279.png
cp ../images/PokeBody/body_006.png ./out/Assets/Colosseum/body_006.png
cp ../images/PokeBody/body_210.png ./out/Assets/Colosseum/body_210.png
cp ../images/PokeFace/face_146.png ./out/Assets/Colosseum/face_146.png
cp ../images/PokeBody/body_277.png ./out/Assets/Colosseum/body_277.png
cp ../images/ColoTrainers/colo_trainer_43.png ./out/Assets/Colosseum/colo_trainer_43.png
cp ../images/PokeBody/body_345.png ./out/Assets/Colosseum/body_345.png
cp ../images/PokeBody/body_390.png ./out/Assets/Colosseum/body_390.png
cp ../images/PokeFace/face_166.png ./out/Assets/Colosseum/face_166.png
cp ../images/PokeFace/face_020.png ./out/Assets/Colosseum/face_020.png
cp ../images/PokeBody/body_395.png ./out/Assets/Colosseum/body_395.png
cp ../images/PokeFace/face_191.png ./out/Assets/Colosseum/face_191.png
cp ../images/PokeBody/body_332.png ./out/Assets/Colosseum/body_332.png
cp ../images/PokeBody/body_356.png ./out/Assets/Colosseum/body_356.png
cp ../images/PokeFace/face_045.png ./out/Assets/Colosseum/face_045.png
cp ../images/PokeFace/face_355.png ./out/Assets/Colosseum/face_355.png
cp ../Sublime/CM/CMScript.sublime-syntax ./out/Assets/Colosseum/CMScript.sublime-syntax
cp ../images/PokeFace/face_354.png ./out/Assets/Colosseum/face_354.png
cp ../images/PokeBody/body_272.png ./out/Assets/Colosseum/body_272.png
cp ../images/PokeBody/body_388.png ./out/Assets/Colosseum/body_388.png
cp ../images/PokeBody/body_088.png ./out/Assets/Colosseum/body_088.png
cp ../images/PokeFace/face_184.png ./out/Assets/Colosseum/face_184.png
cp ../images/PokeFace/face_282.png ./out/Assets/Colosseum/face_282.png
cp ../images/PokeBody/body_346.png ./out/Assets/Colosseum/body_346.png
cp ../images/ColoTrainers/colo_trainer_58.png ./out/Assets/Colosseum/colo_trainer_58.png
cp ../images/PokeFace/face_064.png ./out/Assets/Colosseum/face_064.png
cp ../images/ColoTrainers/colo_trainer_26.png ./out/Assets/Colosseum/colo_trainer_26.png
cp ../images/PokeFace/face_023.png ./out/Assets/Colosseum/face_023.png
cp ../images/PokeFace/face_127.png ./out/Assets/Colosseum/face_127.png
cp ../images/PokeBody/body_008.png ./out/Assets/Colosseum/body_008.png
cp ../images/Types/type_4.png ./out/Assets/Colosseum/type_4.png
cp ../images/PokeBody/body_128.png ./out/Assets/Colosseum/body_128.png
cp ../images/PokeFace/face_066.png ./out/Assets/Colosseum/face_066.png
cp ../images/PokeBody/body_353.png ./out/Assets/Colosseum/body_353.png
cp ../images/PokeFace/face_206.png ./out/Assets/Colosseum/face_206.png
cp ../images/PokeBody/body_383.png ./out/Assets/Colosseum/body_383.png
cp ../images/PokeFace/face_185.png ./out/Assets/Colosseum/face_185.png
cp ../images/PokeBody/body_140.png ./out/Assets/Colosseum/body_140.png
cp ../images/PokeFace/face_114.png ./out/Assets/Colosseum/face_114.png
cp ../images/PokeFace/face_108.png ./out/Assets/Colosseum/face_108.png
cp ../images/PokeFace/face_207.png ./out/Assets/Colosseum/face_207.png
cp ../images/PokeFace/face_401.png ./out/Assets/Colosseum/face_401.png
cp ../images/Types/type_3.png ./out/Assets/Colosseum/type_3.png
cp ../images/PokeBalls/ball\ purple.png ./out/Assets/Colosseum/ball\ purple.png
cp ../images/PokeFace/face_332.png ./out/Assets/Colosseum/face_332.png
cp ../images/PokeFace/face_295.png ./out/Assets/Colosseum/face_295.png
cp ../images/ColoTrainers/colo_trainer_69.png ./out/Assets/Colosseum/colo_trainer_69.png
cp ../images/PokeFace/face_014.png ./out/Assets/Colosseum/face_014.png
cp ../images/PokeBody/body_151.png ./out/Assets/Colosseum/body_151.png
cp ../images/PokeFace/face_369.png ./out/Assets/Colosseum/face_369.png
cp ../images/PokeFace/face_329.png ./out/Assets/Colosseum/face_329.png
cp ../Sublime/CM/SCD.sublime-syntax ./out/Assets/Colosseum/SCD.sublime-syntax
cp ../images/PokeBody/body_350.png ./out/Assets/Colosseum/body_350.png
cp ../images/PokeFace/face_012.png ./out/Assets/Colosseum/face_012.png
cp ../images/PokeFace/face_336.png ./out/Assets/Colosseum/face_336.png
cp ../images/ColoTrainers/colo_trainer_31.png ./out/Assets/Colosseum/colo_trainer_31.png
cp ../images/PokeBody/body_009.png ./out/Assets/Colosseum/body_009.png
cp ../images/PokeBody/body_196.png ./out/Assets/Colosseum/body_196.png
cp ../images/PokeBody/body_278.png ./out/Assets/Colosseum/body_278.png
cp ../images/ColoTrainers/colo_trainer_8.png ./out/Assets/Colosseum/colo_trainer_8.png
cp ../images/PokeBody/body_059.png ./out/Assets/Colosseum/body_059.png
cp ../images/Types/type_15.png ./out/Assets/Colosseum/type_15.png
cp ../images/PokeBody/body_072.png ./out/Assets/Colosseum/body_072.png
cp ../images/PokeFace/face_093.png ./out/Assets/Colosseum/face_093.png
cp ../images/PokeBody/body_175.png ./out/Assets/Colosseum/body_175.png
cp ../images/PokeBody/body_017.png ./out/Assets/Colosseum/body_017.png
cp ../images/PokeBody/body_082.png ./out/Assets/Colosseum/body_082.png
cp ../images/PokeBody/body_273.png ./out/Assets/Colosseum/body_273.png
cp ../images/PokeBody/body_076.png ./out/Assets/Colosseum/body_076.png
cp ../images/PokeFace/face_363.png ./out/Assets/Colosseum/face_363.png
cp ../images/PokeBody/body_068.png ./out/Assets/Colosseum/body_068.png
cp ../images/PokeFace/face_237.png ./out/Assets/Colosseum/face_237.png
cp ../images/PokeBody/body_127.png ./out/Assets/Colosseum/body_127.png
cp ../images/PokeFace/face_115.png ./out/Assets/Colosseum/face_115.png
cp ../images/PokeBody/body_384.png ./out/Assets/Colosseum/body_384.png
cp ../images/PokeFace/face_238.png ./out/Assets/Colosseum/face_238.png
cp ../images/PokeFace/face_001.png ./out/Assets/Colosseum/face_001.png
cp ../JSON/Colosseum/Room\ IDs.json ./out/Assets/Colosseum/Room\ IDs.json
cp ../images/PokeFace/face_035.png ./out/Assets/Colosseum/face_035.png
cp ../images/PokeBody/body_289.png ./out/Assets/Colosseum/body_289.png
cp ../images/PokeBody/body_142.png ./out/Assets/Colosseum/body_142.png
cp ../images/PokeBody/body_256.png ./out/Assets/Colosseum/body_256.png
cp ../images/Types/type_14.png ./out/Assets/Colosseum/type_14.png
cp ../images/PokeFace/face_060.png ./out/Assets/Colosseum/face_060.png
cp ../images/Types/type_fairy.png ./out/Assets/Colosseum/type_fairy.png
cp ../images/PokeBody/body_193.png ./out/Assets/Colosseum/body_193.png
cp ../images/PokeBody/body_111.png ./out/Assets/Colosseum/body_111.png
cp ../images/PokeFace/face_251.png ./out/Assets/Colosseum/face_251.png
cp ../images/PokeFace/face_065.png ./out/Assets/Colosseum/face_065.png
cp ../images/PokeBody/body_055.png ./out/Assets/Colosseum/body_055.png
cp ../images/Types/type_shadow.png ./out/Assets/Colosseum/type_shadow.png
cp ../images/ColoTrainers/colo_trainer_64.png ./out/Assets/Colosseum/colo_trainer_64.png
cp ../images/PokeFace/face_211.png ./out/Assets/Colosseum/face_211.png
cp ../images/PokeFace/face_180.png ./out/Assets/Colosseum/face_180.png
cp ../images/PokeBody/body_339.png ./out/Assets/Colosseum/body_339.png
cp ../images/PokeFace/face_248.png ./out/Assets/Colosseum/face_248.png
cp ../images/PokeBody/body_209.png ./out/Assets/Colosseum/body_209.png
cp ../images/ColoTrainers/colo_trainer_34.png ./out/Assets/Colosseum/colo_trainer_34.png
cp ../images/PokeFace/face_030.png ./out/Assets/Colosseum/face_030.png
cp ../images/ColoTrainers/colo_trainer_71.png ./out/Assets/Colosseum/colo_trainer_71.png
cp ../images/PokeFace/face_150.png ./out/Assets/Colosseum/face_150.png
cp ../images/PokeBody/body_121.png ./out/Assets/Colosseum/body_121.png
cp ../images/PokeFace/face_155.png ./out/Assets/Colosseum/face_155.png
cp ../images/PokeFace/face_344.png ./out/Assets/Colosseum/face_344.png
cp ../images/PokeFace/face_141.png ./out/Assets/Colosseum/face_141.png
cp ../images/PokeBody/body_312.png ./out/Assets/Colosseum/body_312.png
cp ../images/PokeFace/face_025.png ./out/Assets/Colosseum/face_025.png
cp ../images/PokeFace/face_133.png ./out/Assets/Colosseum/face_133.png
cp ../images/PokeBody/body_033.png ./out/Assets/Colosseum/body_033.png
cp ../images/PokeBody/body_223.png ./out/Assets/Colosseum/body_223.png
cp ../images/PokeBody/body_205.png ./out/Assets/Colosseum/body_205.png
cp ../images/PokeFace/face_168.png ./out/Assets/Colosseum/face_168.png
cp ../images/PokeBody/body_291.png ./out/Assets/Colosseum/body_291.png
cp ../images/PokeFace/face_042.png ./out/Assets/Colosseum/face_042.png
cp ../images/PokeBody/body_060.png ./out/Assets/Colosseum/body_060.png
cp ../images/PokeFace/face_265.png ./out/Assets/Colosseum/face_265.png
cp ../images/PokeBody/body_078.png ./out/Assets/Colosseum/body_078.png
cp ../images/PokeFace/face_011.png ./out/Assets/Colosseum/face_011.png
cp ../images/PokeBody/body_250.png ./out/Assets/Colosseum/body_250.png
cp ../images/PokeFace/face_258.png ./out/Assets/Colosseum/face_258.png
cp ../images/PokeBody/body_186.png ./out/Assets/Colosseum/body_186.png
cp ../images/PokeFace/face_348.png ./out/Assets/Colosseum/face_348.png
cp ../images/PokeFace/face_036.png ./out/Assets/Colosseum/face_036.png
cp ../images/PokeBody/body_208.png ./out/Assets/Colosseum/body_208.png
cp ../images/PokeBody/body_294.png ./out/Assets/Colosseum/body_294.png
cp ../images/PokeBody/body_168.png ./out/Assets/Colosseum/body_168.png
cp ../images/PokeBody/body_016.png ./out/Assets/Colosseum/body_016.png
cp ../images/PokeBody/body_054.png ./out/Assets/Colosseum/body_054.png
cp ../images/PokeFace/face_088.png ./out/Assets/Colosseum/face_088.png
cp ../Sublime/CM/CMScript.sublime-settings ./out/Assets/Colosseum/CMScript.sublime-settings
cp ../images/PokeFace/face_082.png ./out/Assets/Colosseum/face_082.png
cp ../images/ColoTrainers/colo_trainer_6.png ./out/Assets/Colosseum/colo_trainer_6.png
cp ../images/PokeFace/face_317.png ./out/Assets/Colosseum/face_317.png
cp ../images/ColoTrainers/colo_trainer_53.png ./out/Assets/Colosseum/colo_trainer_53.png
cp ../images/PokeBody/body_073.png ./out/Assets/Colosseum/body_073.png
cp ../images/PokeFace/face_107.png ./out/Assets/Colosseum/face_107.png
cp ../images/PokeFace/face_345.png ./out/Assets/Colosseum/face_345.png
cp ../images/PokeFace/face_069.png ./out/Assets/Colosseum/face_069.png
cp ../images/PokeFace/face_013.png ./out/Assets/Colosseum/face_013.png
cp ../images/PokeFace/face_161.png ./out/Assets/Colosseum/face_161.png
cp ../images/PokeFace/face_002.png ./out/Assets/Colosseum/face_002.png
cp ../images/PokeBody/body_200.png ./out/Assets/Colosseum/body_200.png
cp ../images/PokeBody/body_322.png ./out/Assets/Colosseum/body_322.png
cp ../images/PokeFace/face_190.png ./out/Assets/Colosseum/face_190.png
cp ../images/PokeFace/face_044.png ./out/Assets/Colosseum/face_044.png
cp ../images/PokeFace/face_171.png ./out/Assets/Colosseum/face_171.png
cp ../Sublime/CM/SCD.sublime-color-scheme ./out/Assets/Colosseum/SCD.sublime-color-scheme
cp ../JSON/pokeAPI.json ./out/Assets/Colosseum/pokeAPI.json
cp ../images/PokeFace/face_285.png ./out/Assets/Colosseum/face_285.png
cp ../images/PokeBalls/ball\ grey.png ./out/Assets/Colosseum/ball\ grey.png
cp ../images/PokeBody/body_354.png ./out/Assets/Colosseum/body_354.png
cp ../images/PokeFace/face_334.png ./out/Assets/Colosseum/face_334.png
cp ../images/PokeFace/face_325.png ./out/Assets/Colosseum/face_325.png
cp ../images/PokeBody/body_005.png ./out/Assets/Colosseum/body_005.png
cp ../images/PokeFace/face_357.png ./out/Assets/Colosseum/face_357.png
cp ../images/Types/type_1.png ./out/Assets/Colosseum/type_1.png
cp ../images/ColoTrainers/colo_trainer_56.png ./out/Assets/Colosseum/colo_trainer_56.png
cp ../images/PokeBody/body_137.png ./out/Assets/Colosseum/body_137.png
cp ../images/PokeBody/body_052.png ./out/Assets/Colosseum/body_052.png
cp ../images/PokeFace/face_086.png ./out/Assets/Colosseum/face_086.png
cp ../images/PokeFace/face_022.png ./out/Assets/Colosseum/face_022.png
cp ../images/PokeBody/body_023.png ./out/Assets/Colosseum/body_023.png
cp ../images/PokeBody/body_367.png ./out/Assets/Colosseum/body_367.png
cp ../images/PokeBody/body_104.png ./out/Assets/Colosseum/body_104.png
cp ../images/PokeBody/body_261.png ./out/Assets/Colosseum/body_261.png
cp ../images/ColoTrainers/colo_trainer_50.png ./out/Assets/Colosseum/colo_trainer_50.png
cp ../images/PokeFace/face_264.png ./out/Assets/Colosseum/face_264.png
cp ../images/PokeFace/face_402.png ./out/Assets/Colosseum/face_402.png
cp ../images/PokeBody/body_382.png ./out/Assets/Colosseum/body_382.png
cp ../images/PokeBody/body_296.png ./out/Assets/Colosseum/body_296.png
cp ../images/PokeBody/body_328.png ./out/Assets/Colosseum/body_328.png
cp ../images/PokeFace/face_189.png ./out/Assets/Colosseum/face_189.png
cp ../images/PokeBody/body_092.png ./out/Assets/Colosseum/body_092.png
cp ../images/ColoTrainers/colo_trainer_7.png ./out/Assets/Colosseum/colo_trainer_7.png
cp ../images/PokeFace/face_247.png ./out/Assets/Colosseum/face_247.png
cp ../images/PokeFace/face_037.png ./out/Assets/Colosseum/face_037.png
cp ../images/PokeFace/face_118.png ./out/Assets/Colosseum/face_118.png
cp ../images/PokeFace/face_223.png ./out/Assets/Colosseum/face_223.png
cp ../images/PokeBody/body_156.png ./out/Assets/Colosseum/body_156.png
cp ../images/PokeFace/face_113.png ./out/Assets/Colosseum/face_113.png
cp ../images/PokeBody/body_161.png ./out/Assets/Colosseum/body_161.png
cp ../images/PokeBody/body_215.png ./out/Assets/Colosseum/body_215.png
cp ../images/PokeBody/body_226.png ./out/Assets/Colosseum/body_226.png
cp ../images/PokeBody/body_359.png ./out/Assets/Colosseum/body_359.png
cp ../images/PokeFace/face_178.png ./out/Assets/Colosseum/face_178.png
cp ../images/PokeFace/face_353.png ./out/Assets/Colosseum/face_353.png
cp ../images/PokeBody/body_118.png ./out/Assets/Colosseum/body_118.png
cp ../images/PokeFace/face_385.png ./out/Assets/Colosseum/face_385.png
cp ../images/PokeBody/body_243.png ./out/Assets/Colosseum/body_243.png
cp ../images/PokeBody/body_338.png ./out/Assets/Colosseum/body_338.png
cp ../images/PokeFace/face_240.png ./out/Assets/Colosseum/face_240.png
cp ../images/PokeBody/body_099.png ./out/Assets/Colosseum/body_099.png
cp ../images/PokeBody/body_259.png ./out/Assets/Colosseum/body_259.png
cp ../images/PokeBody/body_164.png ./out/Assets/Colosseum/body_164.png
cp ../images/PokeFace/face_262.png ./out/Assets/Colosseum/face_262.png
cp ../images/PokeBody/body_371.png ./out/Assets/Colosseum/body_371.png
cp ../images/PokeFace/face_010.png ./out/Assets/Colosseum/face_010.png
cp ../images/PokeBody/body_238.png ./out/Assets/Colosseum/body_238.png
cp ../images/PokeBody/body_379.png ./out/Assets/Colosseum/body_379.png
cp ../images/PokeFace/face_233.png ./out/Assets/Colosseum/face_233.png
cp ../images/PokeBody/body_413.png ./out/Assets/Colosseum/body_413.png
cp ../images/PokeFace/face_378.png ./out/Assets/Colosseum/face_378.png
cp ../images/PokeBody/body_030.png ./out/Assets/Colosseum/body_030.png
cp ../images/PokeBody/body_287.png ./out/Assets/Colosseum/body_287.png
cp ../images/PokeFace/face_390.png ./out/Assets/Colosseum/face_390.png
cp ../images/PokeBody/body_309.png ./out/Assets/Colosseum/body_309.png
cp ../images/PokeFace/face_087.png ./out/Assets/Colosseum/face_087.png
cp ../images/PokeFace/face_167.png ./out/Assets/Colosseum/face_167.png
cp ../images/PokeBody/body_240.png ./out/Assets/Colosseum/body_240.png
cp ../images/PokeFace/face_139.png ./out/Assets/Colosseum/face_139.png
cp ../images/PokeFace/face_072.png ./out/Assets/Colosseum/face_072.png
cp ../images/ColoTrainers/colo_trainer_28.png ./out/Assets/Colosseum/colo_trainer_28.png
cp ../images/PokeFace/face_406.png ./out/Assets/Colosseum/face_406.png
cp ../images/ColoTrainers/colo_trainer_0.png ./out/Assets/Colosseum/colo_trainer_0.png
cp ../images/PokeFace/face_260.png ./out/Assets/Colosseum/face_260.png
cp ../images/PokeFace/face_134.png ./out/Assets/Colosseum/face_134.png
cp ../images/PokeBody/body_216.png ./out/Assets/Colosseum/body_216.png
cp ../images/PokeFace/face_040.png ./out/Assets/Colosseum/face_040.png
cp ../images/PokeBody/body_363.png ./out/Assets/Colosseum/body_363.png
cp ../images/PokeBody/body_258.png ./out/Assets/Colosseum/body_258.png
cp ../images/PokeBody/body_053.png ./out/Assets/Colosseum/body_053.png
cp ../images/PokeFace/face_308.png ./out/Assets/Colosseum/face_308.png
cp ../images/PokeFace/face_220.png ./out/Assets/Colosseum/face_220.png
cp ../images/PokeFace/face_324.png ./out/Assets/Colosseum/face_324.png
cp ../images/ColoTrainers/colo_trainer_68.png ./out/Assets/Colosseum/colo_trainer_68.png
cp ../images/PokeFace/face_089.png ./out/Assets/Colosseum/face_089.png
cp ../images/PokeBody/body_148.png ./out/Assets/Colosseum/body_148.png
cp ../images/PokeBody/body_112.png ./out/Assets/Colosseum/body_112.png
cp ../images/PokeFace/face_136.png ./out/Assets/Colosseum/face_136.png
cp ../images/PokeFace/face_200.png ./out/Assets/Colosseum/face_200.png
cp ../images/PokeBody/body_135.png ./out/Assets/Colosseum/body_135.png
cp ../images/ColoTrainers/colo_trainer_32.png ./out/Assets/Colosseum/colo_trainer_32.png
cp ../images/ColoTrainers/colo_trainer_75.png ./out/Assets/Colosseum/colo_trainer_75.png
cp ../images/PokeFace/face_326.png ./out/Assets/Colosseum/face_326.png
cp ../images/PokeFace/face_076.png ./out/Assets/Colosseum/face_076.png
cp ../images/PokeFace/face_063.png ./out/Assets/Colosseum/face_063.png
cp ../images/PokeFace/face_148.png ./out/Assets/Colosseum/face_148.png
cp ../images/PokeFace/face_085.png ./out/Assets/Colosseum/face_085.png
cp ../images/PokeFace/face_142.png ./out/Assets/Colosseum/face_142.png
cp ../images/ColoTrainers/colo_trainer_12.png ./out/Assets/Colosseum/colo_trainer_12.png
cp ../images/PokeBody/body_344.png ./out/Assets/Colosseum/body_344.png
cp ../images/PokeFace/face_154.png ./out/Assets/Colosseum/face_154.png
cp ../images/PokeFace/face_039.png ./out/Assets/Colosseum/face_039.png
cp ../images/PokeFace/face_059.png ./out/Assets/Colosseum/face_059.png
cp ../images/PokeFace/face_102.png ./out/Assets/Colosseum/face_102.png
cp ../images/PokeBody/body_071.png ./out/Assets/Colosseum/body_071.png
cp ../JSON/Colosseum/Move\ Categories.json ./out/Assets/Colosseum/Move\ Categories.json
cp ../images/ColoTrainers/colo_trainer_65.png ./out/Assets/Colosseum/colo_trainer_65.png
cp ../images/PokeFace/face_342.png ./out/Assets/Colosseum/face_342.png
cp ../images/PokeBody/body_355.png ./out/Assets/Colosseum/body_355.png
cp ../images/PokeBody/body_234.png ./out/Assets/Colosseum/body_234.png
cp ../images/PokeFace/face_384.png ./out/Assets/Colosseum/face_384.png
cp ../images/PokeBody/body_227.png ./out/Assets/Colosseum/body_227.png
cp ../images/PokeBody/body_010.png ./out/Assets/Colosseum/body_010.png
cp ../images/Types/type_16.png ./out/Assets/Colosseum/type_16.png
cp ../images/PokeFace/face_327.png ./out/Assets/Colosseum/face_327.png
cp ../images/PokeBody/body_162.png ./out/Assets/Colosseum/body_162.png
cp ../images/ColoTrainers/colo_trainer_45.png ./out/Assets/Colosseum/colo_trainer_45.png
cp ../images/ColoTrainers/colo_trainer_33.png ./out/Assets/Colosseum/colo_trainer_33.png
cp ../images/PokeBody/body_212.png ./out/Assets/Colosseum/body_212.png
cp ../images/PokeBody/body_124.png ./out/Assets/Colosseum/body_124.png
cp ../images/PokeBody/body_125.png ./out/Assets/Colosseum/body_125.png
cp ../images/PokeFace/face_250.png ./out/Assets/Colosseum/face_250.png
cp ../images/ColoTrainers/colo_trainer_41.png ./out/Assets/Colosseum/colo_trainer_41.png
cp ../images/PokeFace/face_054.png ./out/Assets/Colosseum/face_054.png
cp ../images/Table\ View\ Cells/Tool\ Cell.png ./out/Assets/Colosseum/Tool\ Cell.png
cp ../images/Table\ View\ Cells/File\ Cell.png ./out/Assets/Colosseum/File\ Cell.png
cp ../images/PokeFace/face_096.png ./out/Assets/Colosseum/face_096.png
cp ../images/PokeFace/face_203.png ./out/Assets/Colosseum/face_203.png
cp ../images/PokeFace/face_236.png ./out/Assets/Colosseum/face_236.png
cp ../images/PokeBody/body_182.png ./out/Assets/Colosseum/body_182.png
cp ../images/PokeFace/face_094.png ./out/Assets/Colosseum/face_094.png
cp ../images/PokeFace/face_225.png ./out/Assets/Colosseum/face_225.png
cp ../images/PokeBody/body_203.png ./out/Assets/Colosseum/body_203.png
cp ../images/PokeFace/face_078.png ./out/Assets/Colosseum/face_078.png
cp ../images/PokeBody/body_361.png ./out/Assets/Colosseum/body_361.png
cp ../images/PokeBody/body_191.png ./out/Assets/Colosseum/body_191.png
cp ../images/PokeBody/body_387.png ./out/Assets/Colosseum/body_387.png
cp ../images/PokeFace/face_080.png ./out/Assets/Colosseum/face_080.png
cp ../images/PokeBody/body_316.png ./out/Assets/Colosseum/body_316.png
cp ../images/PokeFace/face_009.png ./out/Assets/Colosseum/face_009.png
cp ../images/PokeFace/face_235.png ./out/Assets/Colosseum/face_235.png
cp ../images/PokeBody/body_117.png ./out/Assets/Colosseum/body_117.png
cp ../images/PokeFace/face_249.png ./out/Assets/Colosseum/face_249.png
cp ../images/PokeFace/face_245.png ./out/Assets/Colosseum/face_245.png
cp ../images/PokeFace/face_192.png ./out/Assets/Colosseum/face_192.png
cp ../images/PokeBody/body_311.png ./out/Assets/Colosseum/body_311.png
cp ../images/PokeBody/body_398.png ./out/Assets/Colosseum/body_398.png
cp ../images/PokeFace/face_193.png ./out/Assets/Colosseum/face_193.png
cp ../images/PokeBody/body_189.png ./out/Assets/Colosseum/body_189.png
cp ../images/PokeBody/body_236.png ./out/Assets/Colosseum/body_236.png
cp ../images/PokeFace/face_196.png ./out/Assets/Colosseum/face_196.png
cp ../images/ColoTrainers/colo_trainer_4.png ./out/Assets/Colosseum/colo_trainer_4.png
cp ../images/PokeFace/face_159.png ./out/Assets/Colosseum/face_159.png
cp ../images/PokeBody/body_174.png ./out/Assets/Colosseum/body_174.png
cp ../images/PokeFace/face_310.png ./out/Assets/Colosseum/face_310.png
cp ../images/PokeFace/face_267.png ./out/Assets/Colosseum/face_267.png
cp ../images/ColoTrainers/colo_trainer_30.png ./out/Assets/Colosseum/colo_trainer_30.png
cp ../images/PokeFace/face_370.png ./out/Assets/Colosseum/face_370.png
cp ../images/PokeFace/face_368.png ./out/Assets/Colosseum/face_368.png
cp ../images/PokeBody/body_145.png ./out/Assets/Colosseum/body_145.png
cp ../images/PokeFace/face_330.png ./out/Assets/Colosseum/face_330.png
cp ../images/PokeFace/face_387.png ./out/Assets/Colosseum/face_387.png
cp ../images/PokeFace/face_302.png ./out/Assets/Colosseum/face_302.png
cp ../images/PokeFace/face_364.png ./out/Assets/Colosseum/face_364.png
cp ../images/PokeFace/face_307.png ./out/Assets/Colosseum/face_307.png
cp ../images/PokeBody/body_089.png ./out/Assets/Colosseum/body_089.png
cp ../images/PokeBody/body_364.png ./out/Assets/Colosseum/body_364.png
cp ../images/PokeBody/body_242.png ./out/Assets/Colosseum/body_242.png
cp ../images/PokeFace/face_299.png ./out/Assets/Colosseum/face_299.png
cp ../images/PokeBody/body_341.png ./out/Assets/Colosseum/body_341.png
cp ../images/PokeFace/face_340.png ./out/Assets/Colosseum/face_340.png
cp ../images/PokeFace/face_229.png ./out/Assets/Colosseum/face_229.png
cp ../images/PokeBody/body_129.png ./out/Assets/Colosseum/body_129.png
cp ../images/PokeFace/face_358.png ./out/Assets/Colosseum/face_358.png
cp ../images/ColoTrainers/colo_trainer_37.png ./out/Assets/Colosseum/colo_trainer_37.png
cp ../images/PokeFace/face_091.png ./out/Assets/Colosseum/face_091.png
cp ../images/PokeBody/body_169.png ./out/Assets/Colosseum/body_169.png
cp ../images/PokeBody/body_079.png ./out/Assets/Colosseum/body_079.png
cp ../images/PokeBody/body_110.png ./out/Assets/Colosseum/body_110.png
cp ../images/PokeBody/body_113.png ./out/Assets/Colosseum/body_113.png
cp ../images/PokeFace/face_232.png ./out/Assets/Colosseum/face_232.png
cp ../images/ColoTrainers/colo_trainer_60.png ./out/Assets/Colosseum/colo_trainer_60.png
cp ../images/PokeFace/face_120.png ./out/Assets/Colosseum/face_120.png
cp ../images/PokeFace/face_182.png ./out/Assets/Colosseum/face_182.png
cp ../images/PokeFace/face_061.png ./out/Assets/Colosseum/face_061.png
cp ../images/PokeFace/face_204.png ./out/Assets/Colosseum/face_204.png
cp ../images/PokeFace/face_244.png ./out/Assets/Colosseum/face_244.png
cp ../images/PokeFace/face_199.png ./out/Assets/Colosseum/face_199.png
cp ../images/PokeFace/face_217.png ./out/Assets/Colosseum/face_217.png
cp ../images/PokeBody/body_190.png ./out/Assets/Colosseum/body_190.png
cp ../images/ColoTrainers/colo_trainer_9.png ./out/Assets/Colosseum/colo_trainer_9.png
cp ../images/PokeBody/body_194.png ./out/Assets/Colosseum/body_194.png
cp ../images/PokeFace/face_303.png ./out/Assets/Colosseum/face_303.png
cp ../images/PokeFace/face_275.png ./out/Assets/Colosseum/face_275.png
cp ../images/PokeFace/face_261.png ./out/Assets/Colosseum/face_261.png
cp ../images/PokeFace/face_246.png ./out/Assets/Colosseum/face_246.png
cp ../images/PokeBody/body_302.png ./out/Assets/Colosseum/body_302.png
cp ../images/PokeBody/body_109.png ./out/Assets/Colosseum/body_109.png
cp ../images/PokeBody/body_397.png ./out/Assets/Colosseum/body_397.png
cp ../images/ColoTrainers/colo_trainer_23.png ./out/Assets/Colosseum/colo_trainer_23.png
cp ../images/PokeFace/face_252.png ./out/Assets/Colosseum/face_252.png
cp ../images/PokeBody/body_220.png ./out/Assets/Colosseum/body_220.png
cp ../images/PokeFace/face_371.png ./out/Assets/Colosseum/face_371.png
cp ../images/PokeFace/face_414.png ./out/Assets/Colosseum/face_414.png
cp ../images/ColoTrainers/colo_trainer_1.png ./out/Assets/Colosseum/colo_trainer_1.png
cp ../images/PokeFace/face_029.png ./out/Assets/Colosseum/face_029.png
cp ../images/PokeBody/body_319.png ./out/Assets/Colosseum/body_319.png
cp ../images/PokeBody/body_407.png ./out/Assets/Colosseum/body_407.png
cp ../images/PokeBody/body_021.png ./out/Assets/Colosseum/body_021.png
cp ../images/PokeBody/body_285.png ./out/Assets/Colosseum/body_285.png
cp ../images/PokeFace/face_257.png ./out/Assets/Colosseum/face_257.png
cp ../images/ColoTrainers/colo_trainer_55.png ./out/Assets/Colosseum/colo_trainer_55.png
cp ../images/Types/type_6.png ./out/Assets/Colosseum/type_6.png
cp ../images/PokeBody/body_378.png ./out/Assets/Colosseum/body_378.png
cp ../images/PokeBody/body_232.png ./out/Assets/Colosseum/body_232.png
cp ../images/PokeBody/body_056.png ./out/Assets/Colosseum/body_056.png
cp ../images/PokeFace/face_216.png ./out/Assets/Colosseum/face_216.png
cp ../images/PokeBody/body_352.png ./out/Assets/Colosseum/body_352.png
cp ../images/PokeBody/body_018.png ./out/Assets/Colosseum/body_018.png
cp ../images/PokeBody/body_224.png ./out/Assets/Colosseum/body_224.png
cp ../images/PokeFace/face_266.png ./out/Assets/Colosseum/face_266.png
cp ../images/PokeBody/body_167.png ./out/Assets/Colosseum/body_167.png
cp ../images/PokeBody/body_347.png ./out/Assets/Colosseum/body_347.png
cp ../images/PokeFace/face_056.png ./out/Assets/Colosseum/face_056.png
cp ../images/PokeFace/face_137.png ./out/Assets/Colosseum/face_137.png
cp ../images/PokeFace/face_297.png ./out/Assets/Colosseum/face_297.png
cp ../images/PokeBody/body_075.png ./out/Assets/Colosseum/body_075.png
cp ../images/PokeFace/face_218.png ./out/Assets/Colosseum/face_218.png
cp ../images/PokeBody/body_380.png ./out/Assets/Colosseum/body_380.png
cp ../images/PokeBody/body_307.png ./out/Assets/Colosseum/body_307.png
cp ../images/PokeFace/face_124.png ./out/Assets/Colosseum/face_124.png
cp ../images/PokeFace/face_349.png ./out/Assets/Colosseum/face_349.png
cp ../images/PokeBody/body_204.png ./out/Assets/Colosseum/body_204.png
cp ../images/PokeBody/body_321.png ./out/Assets/Colosseum/body_321.png
cp ../images/PokeFace/face_198.png ./out/Assets/Colosseum/face_198.png
cp ../images/PokeBody/body_066.png ./out/Assets/Colosseum/body_066.png
cp ../images/PokeFace/face_319.png ./out/Assets/Colosseum/face_319.png
cp ../images/PokeBody/body_385.png ./out/Assets/Colosseum/body_385.png
cp ../images/PokeFace/face_293.png ./out/Assets/Colosseum/face_293.png
cp ../images/ColoTrainers/colo_trainer_63.png ./out/Assets/Colosseum/colo_trainer_63.png
cp ../images/PokeBody/body_269.png ./out/Assets/Colosseum/body_269.png
cp ../images/PokeFace/face_234.png ./out/Assets/Colosseum/face_234.png
cp ../images/PokeBody/body_233.png ./out/Assets/Colosseum/body_233.png
cp ../images/PokeFace/face_174.png ./out/Assets/Colosseum/face_174.png
cp ../images/ColoTrainers/colo_trainer_24.png ./out/Assets/Colosseum/colo_trainer_24.png
cp ../images/PokeBody/body_237.png ./out/Assets/Colosseum/body_237.png
cp ../images/PokeBody/body_047.png ./out/Assets/Colosseum/body_047.png
cp ../images/PokeFace/face_316.png ./out/Assets/Colosseum/face_316.png
cp ../images/PokeBody/body_172.png ./out/Assets/Colosseum/body_172.png
cp ../images/PokeFace/face_413.png ./out/Assets/Colosseum/face_413.png
cp ../images/PokeBody/body_146.png ./out/Assets/Colosseum/body_146.png
cp ../images/PokeFace/face_027.png ./out/Assets/Colosseum/face_027.png
cp ../images/PokeFace/face_129.png ./out/Assets/Colosseum/face_129.png
cp ../images/PokeBody/body_181.png ./out/Assets/Colosseum/body_181.png
cp ../images/PokeFace/face_360.png ./out/Assets/Colosseum/face_360.png
cp ../images/Types/type_5.png ./out/Assets/Colosseum/type_5.png
cp ../images/PokeBody/body_025.png ./out/Assets/Colosseum/body_025.png
cp ../images/PokeBody/body_254.png ./out/Assets/Colosseum/body_254.png
cp ../images/ColoTrainers/colo_trainer_2.png ./out/Assets/Colosseum/colo_trainer_2.png
cp ../images/PokeBody/body_326.png ./out/Assets/Colosseum/body_326.png
cp ../images/PokeBody/body_349.png ./out/Assets/Colosseum/body_349.png
cp ../images/PokeFace/face_333.png ./out/Assets/Colosseum/face_333.png
cp ../images/PokeFace/face_143.png ./out/Assets/Colosseum/face_143.png
cp ../images/PokeFace/face_160.png ./out/Assets/Colosseum/face_160.png
cp ../images/PokeBody/body_396.png ./out/Assets/Colosseum/body_396.png
cp ../images/PokeFace/face_144.png ./out/Assets/Colosseum/face_144.png
cp ../images/Types/type_0.png ./out/Assets/Colosseum/type_0.png
cp ../images/PokeFace/face_109.png ./out/Assets/Colosseum/face_109.png
cp ../images/PokeBody/body_011.png ./out/Assets/Colosseum/body_011.png
cp ../images/PokeBody/body_180.png ./out/Assets/Colosseum/body_180.png
cp ../images/PokeBody/body_300.png ./out/Assets/Colosseum/body_300.png
cp ../images/PokeBody/body_370.png ./out/Assets/Colosseum/body_370.png
cp ../images/PokeFace/face_338.png ./out/Assets/Colosseum/face_338.png
cp ../images/PokeFace/face_375.png ./out/Assets/Colosseum/face_375.png
cp ../images/PokeFace/face_179.png ./out/Assets/Colosseum/face_179.png
cp ../images/PokeBody/body_003.png ./out/Assets/Colosseum/body_003.png
cp ../images/PokeFace/face_101.png ./out/Assets/Colosseum/face_101.png
cp ../images/PokeFace/face_268.png ./out/Assets/Colosseum/face_268.png
cp ../images/PokeBody/body_041.png ./out/Assets/Colosseum/body_041.png
cp ../images/PokeFace/face_117.png ./out/Assets/Colosseum/face_117.png
cp ../images/ColoTrainers/colo_trainer_10.png ./out/Assets/Colosseum/colo_trainer_10.png
cp ../tools/OSX/wiimm/* ./out/Assets/Colosseum/wiimm
cp ../tools/OSX/nedclib/* ./out/Assets/Colosseum/nedclib
cp ../tools/OSX/other/* ./out/Assets/Colosseum
echo "Compiling Colosseum Tool. This may take a while..."
swiftc -emit-executable -DENV_OSX -DGAME_COLO -o ./out/Colosseum\ Tool\ CLI  ../enums/XGMoveTargets.swift ../Objects/managers/GoDShellManager.swift ../enums/XGEffectivenessValues.swift ../Objects/managers/swift-png/PNG/ColorTargets/PNG.RGBA.swift ../Objects/managers/swift-png/swift-hash/BaseDigits/BaseDigits.swift ../enums/CMTMs.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.ColorProfile.swift ../Objects/data\ types/CMPartyPokemon.swift ../Objects/managers/GoDFiltersManager.swift ../Objects/textures/XGTextureBlock.swift ../Objects/file\ formats/XGTHP.swift ../Objects/scripts/Colosseum/CMScriptOps.swift ../Objects/scripts/Colosseum/CMSMacroTypes.swift ../Objects/struct\ tables/StructTablesList.swift ../Objects/struct\ tables/CMTrainersTable.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.Palette.swift ../Objects/managers/EcardCoder.swift ../Objects/processes/Dolphin/ColoXD/Colosseum/CMProcessSetup.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.Gamma.swift ../Objects/helper\ data\ types/GoDOffsetIO.swift ../enums/XGDayCareStatus.swift ../Objects/scripts/Colosseum/CMSExpr.swift ../Objects/struct\ tables/InteractionPointTable.swift ../Objects/struct\ parsing/GoDStructData.swift ../Objects/data\ types/XGEvolution.swift ../Objects/data\ types/enumerable/CMGiftPokemon.swift ../enums/XGMoveCategory.swift ../Objects/managers/swift-png/PNG/Decoding/PNG.Context.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.Header.swift ../Objects/protocols/ReadableWritable.swift ../Objects/managers/XGSaveManager.swift ../enums/XGFontColours.swift ../Objects/managers/swift-png/PNG/Encoding/PNG.Encoder.swift ../Objects/data\ types/enumerable/XGInteractionPoint.swift ../Objects/struct\ parsing/GoDStructTable.swift ../Objects/struct\ tables/AbilitiesTable.swift ../Objects/data\ types/enumerable/XGCharacterModel.swift ../Objects/managers/swift-png/PNG/ColorTargets/_PNGColor.swift ../Objects/managers/swift-png/swift-hash/Base64/Base64.Values.swift ../Objects/struct\ parsing/GoDStruct.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.PhysicalDimensions.swift ../enums/XGColosseumRounds.swift ../Objects/file\ formats/XGGSWTextures.swift ../Objects/struct\ tables/TreasureTable.swift ../Objects/scripts/Colosseum/CMScriptCompiler.swift ../Objects/managers/swift-png/swift-hash/Base64/Base64.swift ../enums/XGMoveTypes.swift ../Objects/scripts/Colosseum/CMScriptBuiltInFunctions.swift ../Objects/struct\ tables/StatusEffectsTable.swift ../enums/XGEvolutionConditionType.swift ../Objects/discord\ API/ColoursByName.swift ../Objects/managers/swift-png/PNG/Layout/PNG.swift ../enums/XGGenderRatios.swift ../enums/XGStatBoosts.swift ../Objects/managers/xxHash/xxh3/XXH3-Common.swift ../Objects/managers/swift-png/PNG/Decoding/PNG.DecodingError.swift ../enums/XGStatusEffects.swift ../Objects/managers/xxHash/xxh3/XXH3-Bit128.swift ../enums/XGResources.swift ../enums/XGBagSlots.swift ../Objects/file\ formats/XGCollisionData.swift ../extensions/HashExtensions.swift ../Objects/managers/swift-png/PNG/LZ77/General.Heap.swift ../Objects/processes/Dolphin/ColoXD/ColoXDGameState.swift ../Objects/managers/swift-png/PNG/Lexing/_PNGBytestreamDestination.swift ../Objects/managers/swift-png/PNG/Decoding/PNG.Metadata.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.SignificantBits.swift ../enums/XGContestCategories.swift ../Objects/data\ types/enumerable/XGTreasure.swift ../Objects/file\ formats/PKXModel.swift ../Objects/file\ formats/DATNodes.swift ../Objects/managers/swift-png/swift-hash/MessageAuthentication/MessageAuthenticationKey.swift ../Objects/struct\ tables/SaveFileTables.swift ../Objects/managers/swift-png/swift-hash/Base16/Base16.LowercaseDigits.swift ../Objects/managers/swift-png/PNG/System.swift ../Objects/managers/swift-png/PNG/LZ77/LZ77.Deflator.Term.swift ../Objects/managers/XGStringManager.swift ../enums/XGAbilities.swift ../Objects/managers/xxHash/xxh3/XXH3-Bit64.swift ../Objects/helper\ data\ types/XGBattleSequence.swift ../Objects/data\ types/enumerable/XGBattleField.swift ../Objects/data\ types/enumerable/XGNature.swift ../ColosseumToolCL/main.swift ../enums/XGASM.swift ../Objects/managers/swift-png/PNG/LZ77/LZ77.DecompressionError.swift ../Objects/managers/swift-png/swift-hash/Base16/Base16.Values.swift ../Objects/managers/swift-png/PNG/Layout/PNG.Layout.swift ../Objects/managers/swift-png/PNG/_PNGError.swift ../Objects/textures/XGPNGBlock.swift ../enums/GoDTextureFormats.swift ../Objects/struct\ tables/TexturesTable.swift ../Objects/file\ formats/XGMapRel.swift ../Objects/data\ types/enumerable/CMItem.swift ../Objects/struct\ tables/MovesTable.swift ../Objects/data\ types/enumerable/XGTrainerClass.swift ../Objects/textures/XGTexturePalette.swift ../Objects/data\ types/enumerable/XGDemoStarterPokemon.swift ../enums/XGBattleStyles.swift ../enums/XGMoveEffectTypes.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.ColorRendering.swift ../Objects/file\ formats/XGLZSS.swift ../Objects/managers/CMGiftPokemonManager.swift ../enums/XGEggGroups.swift ../Objects/managers/swift-png/swift-hash/Base64/Base64.Digits.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.Transparency.swift ../Objects/managers/swift-png/swift-hash/MessageAuthentication/MessageAuthenticationHash.swift ../Objects/managers/XGThreadManager.swift ../Objects/struct\ tables/RoomsTable.swift ../Objects/processes/Dolphin/GCController.swift ../Objects/managers/swift-png/PNG/Lexing/PNG.LexingError.swift ../Objects/processes/GoDProcess.swift ../Objects/struct\ parsing/CommonStructTable.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.Text.swift ../Objects/managers/swift-png/swift-hash/Base16/Base16.UppercaseDigits.swift ../Objects/struct\ tables/PokemonTable.swift ../enums/CMDecks.swift ../Objects/data\ types/enumerable/XGStarterPokemon.swift ../Objects/processes/Dolphin/ColoXD/ColoXDBreakPoints.swift ../Objects/struct\ tables/TypesTable.swift ../enums/XGTrainerContoller.swift ../Objects/managers/swift-png/PNG/__Entrypoint.swift ../Objects/data\ types/CMStoredShadowData.swift ../Objects/struct\ parsing/EncodableTableTypes.swift ../enums/XGBattleResult.swift ../Objects/managers/swift-png/PNG/LZ77/LZ77.Deflator.Term.Meta.swift ../Objects/managers/swift-png/PNG/LZ77/LZ77.Deflator.swift ../Objects/data\ types/enumerable/CMType.swift ../Objects/processes/ProcessIO.swift ../GoDToolCL/CommandLineArgs.swift ../Objects/discord\ API/Discord\ Plays\ Pokemon/DiscordBot.swift ../Objects/scripts/Colosseum/CMScript.swift ../GoDToolOSX/Objects/GoDKeyCodes.swift ../Objects/file\ formats/XGAssemblyCode.swift ../Objects/data\ types/enumerable/CMTrainer.swift ../Objects/struct\ tables/CharacterModelTable.swift ../Objects/file\ formats/WZXModel.swift ../GoDToolOSX/Objects/XGVertex.swift ../enums/XGNatures.swift ../Objects/managers/xxHash/XXH32.swift ../enums/CMItems.swift ../Objects/data\ types/enumerable/XGMove.swift ../Objects/managers/swift-png/swift-hash/CRC/CRC32.swift ../Objects/managers/swift-png/swift-hash/Base16/Base16.swift ../Objects/managers/xxHash/xxHash-Common.swift ../Objects/managers/xxHash/xxh3/XXH3.swift ../enums/XGMoves.swift ../enums/XGShinyValues.swift ../Objects/managers/swift-png/PNG/LZ77/LZ77.Inflator.swift ../Objects/file\ formats/GoDTexturesContaining.swift ../extensions/GoDImageExtensions.swift ../Objects/processes/Dolphin/ColoXD/ColoXDProcess.swift ../Objects/managers/swift-png/PNG/LZ77/General.Dictionary.swift ../enums/XGExpRate.swift ../Objects/discord\ API/Discord.swift ../Objects/textures/XGColour.swift ../GoDGameInit.swift ../Objects/data\ types/XGLevelUpMove.swift ../enums/XGWeather.swift ../Objects/managers/ASMScriptManager.swift ../enums/GamesAndLangauages.swift ../Objects/managers/xxHash/XXH64.swift ../Objects/protocols/EnumerableDocumentable.swift ../Objects/helper\ data\ types/GoDDataTableEntry.swift ../Objects/managers/XGSettings.swift ../Objects/struct\ tables/ItemsTable.swift ../enums/XGSpecialStringCharacters.swift ../Objects/managers/XGPatcher.swift ../Objects/file\ formats/XGISO.swift ../Objects/managers/swift-png/PNG/Decoding/PNG.Standard.swift ../Objects/scripts/Colosseum/CMSFlags.swift ../Objects/processes/Dolphin/ColoXD/Colosseum/context/CMBreakPoints.swift ../CMRelIndexes.swift ../Objects/processes/Dolphin/DolphinProcess.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.FormattingError.swift ../GoDToolOSX/Objects/GoDDesign.swift ../enums/XGGenders.swift ../Objects/struct\ tables/SmallStructTables.swift ../Objects/scripts/Colosseum/CMScriptValueTypes.swift ../Objects/managers/XGRandomiser.swift ../extensions/XGGeneralExtensions.swift ../Objects/helper\ data\ types/XGStack.swift ../GoDLogManager.swift ../enums/XGBattleTypes.swift ../Objects/data\ types/enumerable/XGGiftPokemon.swift ../enums/XGUnicodeCharacters.swift ../Objects/data\ types/enumerable/XGBattleModeRulesets.swift ../Objects/managers/swift-png/PNG/ColorTargets/PNG.VA.swift ../Objects/managers/swift-png/TerminalColors/String.swift ../Objects/file\ formats/XGRelocationTable.swift ../Objects/managers/swift-png/PNG/Lexing/_PNGBytestreamSource.swift ../Objects/managers/swift-png/PNG/Layout/PNG.Data.Rectangular.swift ../enums/XGPokemon.swift ../Objects/processes/Dolphin/DolphinSettings.swift ../Objects/textures/GoDTexture.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.Background.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.ParsingError.swift ../Objects/file\ formats/XGStringTable.swift ../Objects/struct\ tables/ScriptTable.swift ../extensions/PDADumper.swift ../extensions/XGFoundationExtensions.swift ../Objects/processes/Dolphin/ColoXD/Colosseum/CMProcess.swift ../Objects/data\ types/XGCharacter.swift ../Objects/managers/swift-png/PNG/Decoding/PNG.Decoder.swift ../enums/XGEvolutionMethods.swift ../Objects/helper\ data\ types/GoDDataTable.swift ../Objects/managers/swift-png/swift-hash/SHA2/SHA256.swift ../Objects/file\ formats/XGAssemblyCodeExtensions.swift ../Objects/helper\ data\ types/XGMutableData.swift ../Objects/file\ formats/GSFsys.swift ../Objects/data\ types/enumerable/CMTrainerPokemon.swift ../Objects/struct\ tables/NatureTable.swift ../Objects/scripts/Colosseum/CMSExtensions.swift ../Objects/data\ types/enumerable/CMPokemonStats.swift ../Objects/data\ types/enumerable/XGDoor.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.TimeModified.swift ../Objects/textures/XGImage.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.Chromaticity.swift ../Objects/file\ formats/XGFsys.swift ../enums/CMTrainerModels.swift ../extensions/ColosseumExtensions.swift ../enums/XGFileTypes.swift ../ColosseumToolCL/Code\ Snippets.swift ../Objects/file\ formats/DATModel.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.Histogram.swift ../Objects/textures/GoDTextureImporter.swift ../Objects/struct\ tables/PKXWZXTables.swift ../Objects/struct\ tables/EreaderTables.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.Percentmille.swift ../enums/CMTrainerClasses.swift ../enums/XGDeoxysFormes.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.Format.swift ../Objects/data\ types/enumerable/XGRoom.swift ../enums/XGMaps.swift ../Objects/discord\ API/Discord\ Plays\ Pokemon/DiscordPlaysOrre.swift ../Objects/discord\ API/Discord\ Plays\ Pokemon/PokeAPI.swift ../Objects/struct\ tables/Battles.swift ../Objects/managers/XGUtility.swift ../Objects/data\ types/XGString.swift ../Objects/managers/GoDNetworkingManager.swift ../Objects/processes/Dolphin/GCButtons.swift ../enums/XGFiles.swift ../Objects/managers/swift-png/PNG/Lexing/PNG.Chunk.swift ../GoDToolOSX/Objects/GoDOpenGL.swift ../Objects/managers/swift-png/PNG/Parsing/PNG.SuggestedPalette.swift ../Objects/data\ types/enumerable/CMBattle.swift