
name: Pokemon Tools CI

on: [push,pull_request,release]

jobs:
  Build:
    runs-on: macos-latest
    strategy:
        matrix:
          target: ['GoD Tool']
    steps:
      - name: Checkout to master
        uses: actions/checkout@master
      - name: Clean
        run: |
          xcodebuild clean
      - name: Build
        run: |
          xcodebuild build -project "GoD Tool.xcodeproj" -target "${target}" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        env:
          target: ${{ matrix.target }}
