
name: Pokemon Tools CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  macos:
    runs-on: macos-latest
    strategy:
        matrix:
          target: ['GoD Tool']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Clean
        run: |
          xcodebuild clean
      - name: Build
        run: |
          make build copy
          tar -cvf "${target}.tar" out/
        env:
          target: ${{ matrix.target }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: |
            ${{ matrix.target }}.tar
