#!/bin/bash
cd -- "$(dirname "$0")" #changes the terminal's directory to the directory where the script was launched
echo "Copying GoD Tool Assets. This may take a while..."
mkdir ./out/Assets
mkdir ./out/Assets/XD
mkdir ./out/Assets/XD/wiimm
cp ../images/PokeFace/face_115.png ./out/Assets/XD/face_115.png
cp ../images/PokeBody/body_226.png ./out/Assets/XD/body_226.png
cp ../images/PokeFace/face_189.png ./out/Assets/XD/face_189.png
cp ../images/Types/type_3.png ./out/Assets/XD/type_3.png
cp ../images/PokeFace/face_206.png ./out/Assets/XD/face_206.png
cp ../images/PokeBody/body_181.png ./out/Assets/XD/body_181.png
cp ../images/PokeFace/face_374.png ./out/Assets/XD/face_374.png
cp ../images/PokeBody/body_381.png ./out/Assets/XD/body_381.png
cp ../images/PokeFace/face_025.png ./out/Assets/XD/face_025.png
cp ../images/PokeFace/face_403.png ./out/Assets/XD/face_403.png
cp ../images/PokeFace/face_005.png ./out/Assets/XD/face_005.png
cp ../images/PokeFace/face_080.png ./out/Assets/XD/face_080.png
cp ../images/Trainers/trainer_60.png ./out/Assets/XD/trainer_60.png
cp ../images/PokeBody/body_172.png ./out/Assets/XD/body_172.png
cp ../images/PokeFace/face_128.png ./out/Assets/XD/face_128.png
cp ../images/PokeBody/body_169.png ./out/Assets/XD/body_169.png
cp ../images/PokeBody/body_109.png ./out/Assets/XD/body_109.png
cp ../images/PokeBody/body_037.png ./out/Assets/XD/body_037.png
cp ../images/PokeFace/face_229.png ./out/Assets/XD/face_229.png
cp ../images/PokeFace/face_196.png ./out/Assets/XD/face_196.png
cp ../images/PokeFace/face_397.png ./out/Assets/XD/face_397.png
cp ../images/PokeBody/body_393.png ./out/Assets/XD/body_393.png
cp ../images/PokeBody/body_277.png ./out/Assets/XD/body_277.png
cp ../images/Trainers/trainer_43.png ./out/Assets/XD/trainer_43.png
cp ../images/PokeBody/body_354.png ./out/Assets/XD/body_354.png
cp ../images/PokeFace/face_009.png ./out/Assets/XD/face_009.png
cp ../images/PokeFace/face_362.png ./out/Assets/XD/face_362.png
cp ../images/PokeBody/body_410.png ./out/Assets/XD/body_410.png
cp ../images/PokeBody/body_306.png ./out/Assets/XD/body_306.png
cp ../images/PokeBody/body_257.png ./out/Assets/XD/body_257.png
cp ../images/PokeBody/body_263.png ./out/Assets/XD/body_263.png
cp ../images/PokeBody/body_390.png ./out/Assets/XD/body_390.png
cp ../images/PokeBody/body_031.png ./out/Assets/XD/body_031.png
cp ../images/PokeBody/body_358.png ./out/Assets/XD/body_358.png
cp ../images/PokeBody/body_317.png ./out/Assets/XD/body_317.png
cp ../images/PokeFace/face_343.png ./out/Assets/XD/face_343.png
cp ../images/PokeBody/body_056.png ./out/Assets/XD/body_056.png
cp ../images/PokeBody/body_195.png ./out/Assets/XD/body_195.png
cp ../images/PokeBody/body_244.png ./out/Assets/XD/body_244.png
cp ../images/PokeBody/body_038.png ./out/Assets/XD/body_038.png
cp ../images/PokeBody/body_173.png ./out/Assets/XD/body_173.png
cp ../images/Trainers/trainer_56.png ./out/Assets/XD/trainer_56.png
cp ../images/PokeFace/face_154.png ./out/Assets/XD/face_154.png
cp ../images/PokeBody/body_096.png ./out/Assets/XD/body_096.png
cp ../images/PokeBody/body_161.png ./out/Assets/XD/body_161.png
cp ../images/PokeFace/face_215.png ./out/Assets/XD/face_215.png
cp ../images/Trainers/trainer_55.png ./out/Assets/XD/trainer_55.png
cp ../images/PokeBody/body_214.png ./out/Assets/XD/body_214.png
cp ../images/PokeBody/body_075.png ./out/Assets/XD/body_075.png
cp ../images/PokeBody/body_351.png ./out/Assets/XD/body_351.png
cp ../images/PokeFace/face_092.png ./out/Assets/XD/face_092.png
cp ../images/PokeFace/face_271.png ./out/Assets/XD/face_271.png
cp ../images/PokeFace/face_266.png ./out/Assets/XD/face_266.png
cp ../images/PokeBody/body_290.png ./out/Assets/XD/body_290.png
cp ../images/PokeFace/face_039.png ./out/Assets/XD/face_039.png
cp ../images/Trainers/trainer_4.png ./out/Assets/XD/trainer_4.png
cp ../images/PokeFace/face_000.png ./out/Assets/XD/face_000.png
cp ../images/Trainers/trainer_61.png ./out/Assets/XD/trainer_61.png
cp ../images/PokeFace/face_302.png ./out/Assets/XD/face_302.png
cp ../images/PokeFace/face_353.png ./out/Assets/XD/face_353.png
cp ../images/PokeBody/body_347.png ./out/Assets/XD/body_347.png
cp ../images/PokeFace/face_308.png ./out/Assets/XD/face_308.png
cp ../images/Types/type_2.png ./out/Assets/XD/type_2.png
cp ../images/PokeFace/face_032.png ./out/Assets/XD/face_032.png
cp ../images/PokeFace/face_070.png ./out/Assets/XD/face_070.png
cp ../images/PokeFace/face_205.png ./out/Assets/XD/face_205.png
cp ../images/PokeBody/body_320.png ./out/Assets/XD/body_320.png
cp ../images/Trainers/trainer_53.png ./out/Assets/XD/trainer_53.png
cp ../images/PokeFace/face_073.png ./out/Assets/XD/face_073.png
cp ../images/PokeBody/body_153.png ./out/Assets/XD/body_153.png
cp ../images/PokeBody/body_237.png ./out/Assets/XD/body_237.png
cp ../images/PokeBody/body_359.png ./out/Assets/XD/body_359.png
cp ../images/PokeFace/face_029.png ./out/Assets/XD/face_029.png
cp ../images/PokeFace/face_371.png ./out/Assets/XD/face_371.png
cp ../images/PokeBody/body_220.png ./out/Assets/XD/body_220.png
cp ../images/PokeBody/body_119.png ./out/Assets/XD/body_119.png
cp ../images/PokeBody/body_010.png ./out/Assets/XD/body_010.png
cp ../images/PokeBody/body_258.png ./out/Assets/XD/body_258.png
cp ../images/PokeFace/face_160.png ./out/Assets/XD/face_160.png
cp ../images/PokeFace/face_021.png ./out/Assets/XD/face_021.png
cp ../images/PokeBody/body_139.png ./out/Assets/XD/body_139.png
cp ../images/PokeBody/body_102.png ./out/Assets/XD/body_102.png
cp ../images/PokeFace/face_395.png ./out/Assets/XD/face_395.png
cp ../images/PokeBody/body_044.png ./out/Assets/XD/body_044.png
cp ../images/PokeBody/body_255.png ./out/Assets/XD/body_255.png
cp ../images/PokeFace/face_135.png ./out/Assets/XD/face_135.png
cp ../images/PokeFace/face_304.png ./out/Assets/XD/face_304.png
cp ../images/PokeBody/body_148.png ./out/Assets/XD/body_148.png
cp ../images/PokeFace/face_037.png ./out/Assets/XD/face_037.png
cp ../images/PokeFace/face_076.png ./out/Assets/XD/face_076.png
cp ../images/Trainers/trainer_25.png ./out/Assets/XD/trainer_25.png
cp ../images/PokeFace/face_296.png ./out/Assets/XD/face_296.png
cp ../images/PokeFace/face_315.png ./out/Assets/XD/face_315.png
cp ../images/PokeFace/face_247.png ./out/Assets/XD/face_247.png
cp ../images/Types/type_16.png ./out/Assets/XD/type_16.png
cp ../images/Trainers/trainer_46.png ./out/Assets/XD/trainer_46.png
cp ../images/PokeFace/face_169.png ./out/Assets/XD/face_169.png
cp ../images/PokeBody/body_078.png ./out/Assets/XD/body_078.png
cp ../images/PokeFace/face_378.png ./out/Assets/XD/face_378.png
cp ../images/PokeFace/face_227.png ./out/Assets/XD/face_227.png
cp ../images/PokeFace/face_041.png ./out/Assets/XD/face_041.png
cp ../images/PokeBody/body_291.png ./out/Assets/XD/body_291.png
cp ../images/PokeFace/face_209.png ./out/Assets/XD/face_209.png
cp ../images/Trainers/trainer_11.png ./out/Assets/XD/trainer_11.png
cp ../images/PokeBody/body_232.png ./out/Assets/XD/body_232.png
cp ../images/PokeFace/face_055.png ./out/Assets/XD/face_055.png
cp ../images/PokeFace/face_035.png ./out/Assets/XD/face_035.png
cp ../images/PokeFace/face_200.png ./out/Assets/XD/face_200.png
cp ../images/PokeFace/face_211.png ./out/Assets/XD/face_211.png
cp ../images/PokeFace/face_199.png ./out/Assets/XD/face_199.png
cp ../images/PokeFace/face_260.png ./out/Assets/XD/face_260.png
cp ../images/PokeBody/body_250.png ./out/Assets/XD/body_250.png
cp ../images/PokeFace/face_212.png ./out/Assets/XD/face_212.png
cp ../images/PokeFace/face_346.png ./out/Assets/XD/face_346.png
cp ../images/PokeBody/body_100.png ./out/Assets/XD/body_100.png
cp ../images/PokeFace/face_019.png ./out/Assets/XD/face_019.png
cp ../images/PokeFace/face_293.png ./out/Assets/XD/face_293.png
cp ../images/PokeFace/face_149.png ./out/Assets/XD/face_149.png
cp ../images/PokeBody/body_033.png ./out/Assets/XD/body_033.png
cp ../images/Trainers/trainer_51.png ./out/Assets/XD/trainer_51.png
cp ../images/PokeFace/face_213.png ./out/Assets/XD/face_213.png
cp ../images/PokeFace/face_224.png ./out/Assets/XD/face_224.png
cp ../images/PokeFace/face_389.png ./out/Assets/XD/face_389.png
cp ../images/PokeFace/face_328.png ./out/Assets/XD/face_328.png
cp ../images/PokeFace/face_180.png ./out/Assets/XD/face_180.png
cp ../images/PokeBody/body_082.png ./out/Assets/XD/body_082.png
cp ../images/PokeFace/face_412.png ./out/Assets/XD/face_412.png
cp ../images/PokeBody/body_236.png ./out/Assets/XD/body_236.png
cp ../images/PokeBody/body_068.png ./out/Assets/XD/body_068.png
cp ../images/PokeFace/face_274.png ./out/Assets/XD/face_274.png
cp ../images/PokeFace/face_190.png ./out/Assets/XD/face_190.png
cp ../images/PokeFace/face_017.png ./out/Assets/XD/face_017.png
cp ../images/Types/type_4.png ./out/Assets/XD/type_4.png
cp ../images/Trainers/trainer_36.png ./out/Assets/XD/trainer_36.png
cp ../images/PokeFace/face_404.png ./out/Assets/XD/face_404.png
cp ../images/PokeFace/face_045.png ./out/Assets/XD/face_045.png
cp ../images/Trainers/trainer_44.png ./out/Assets/XD/trainer_44.png
cp ../images/PokeFace/face_257.png ./out/Assets/XD/face_257.png
cp ../images/PokeBody/body_372.png ./out/Assets/XD/body_372.png
cp ../images/PokeBody/body_187.png ./out/Assets/XD/body_187.png
cp ../images/PokeBody/body_384.png ./out/Assets/XD/body_384.png
cp ../images/PokeBalls/ball\ grey.png ./out/Assets/XD/ball\ grey.png
cp ../images/PokeBody/body_296.png ./out/Assets/XD/body_296.png
cp ../images/PokeFace/face_398.png ./out/Assets/XD/face_398.png
cp ../images/Trainers/trainer_18.png ./out/Assets/XD/trainer_18.png
cp ../images/PokeFace/face_071.png ./out/Assets/XD/face_071.png
cp ../images/PokeBody/body_054.png ./out/Assets/XD/body_054.png
cp ../images/PokeFace/face_153.png ./out/Assets/XD/face_153.png
cp ../images/PokeFace/face_185.png ./out/Assets/XD/face_185.png
cp ../images/PokeBody/body_165.png ./out/Assets/XD/body_165.png
cp ../images/Trainers/trainer_15.png ./out/Assets/XD/trainer_15.png
cp ../images/PokeBody/body_321.png ./out/Assets/XD/body_321.png
cp ../images/PokeBody/body_225.png ./out/Assets/XD/body_225.png
cp ../images/PokeFace/face_237.png ./out/Assets/XD/face_237.png
cp ../images/PokeBody/body_210.png ./out/Assets/XD/body_210.png
cp ../images/Trainers/trainer_5.png ./out/Assets/XD/trainer_5.png
cp ../images/PokeFace/face_015.png ./out/Assets/XD/face_015.png
cp ../images/PokeBody/body_079.png ./out/Assets/XD/body_079.png
cp ../images/PokeFace/face_323.png ./out/Assets/XD/face_323.png
cp ../images/PokeBody/body_287.png ./out/Assets/XD/body_287.png
cp ../images/PokeFace/face_193.png ./out/Assets/XD/face_193.png
cp ../images/PokeBody/body_067.png ./out/Assets/XD/body_067.png
cp ../images/PokeFace/face_142.png ./out/Assets/XD/face_142.png
cp ../images/PokeBody/body_234.png ./out/Assets/XD/body_234.png
cp ../images/PokeFace/face_407.png ./out/Assets/XD/face_407.png
cp ../images/PokeBody/body_364.png ./out/Assets/XD/body_364.png
cp ../images/PokeBody/body_206.png ./out/Assets/XD/body_206.png
cp ../images/PokeBody/body_212.png ./out/Assets/XD/body_212.png
cp ../images/PokeBody/body_239.png ./out/Assets/XD/body_239.png
cp ../images/PokeBody/body_061.png ./out/Assets/XD/body_061.png
cp ../images/PokeBody/body_071.png ./out/Assets/XD/body_071.png
cp ../images/PokeBody/body_168.png ./out/Assets/XD/body_168.png
cp ../images/PokeBody/body_092.png ./out/Assets/XD/body_092.png
cp ../images/PokeBody/body_050.png ./out/Assets/XD/body_050.png
cp ../images/PokeFace/face_123.png ./out/Assets/XD/face_123.png
cp ../images/PokeFace/face_258.png ./out/Assets/XD/face_258.png
cp ../images/PokeFace/face_409.png ./out/Assets/XD/face_409.png
cp ../images/Trainers/trainer_59.png ./out/Assets/XD/trainer_59.png
cp ../images/Trainers/trainer_42.png ./out/Assets/XD/trainer_42.png
cp ../images/PokeFace/face_047.png ./out/Assets/XD/face_047.png
cp ../images/Trainers/trainer_32.png ./out/Assets/XD/trainer_32.png
cp ../images/PokeFace/face_125.png ./out/Assets/XD/face_125.png
cp ../images/PokeBody/body_015.png ./out/Assets/XD/body_015.png
cp ../images/Types/type_13.png ./out/Assets/XD/type_13.png
cp ../images/PokeBody/body_203.png ./out/Assets/XD/body_203.png
cp ../images/PokeFace/face_272.png ./out/Assets/XD/face_272.png
cp ../images/PokeBody/body_283.png ./out/Assets/XD/body_283.png
cp ../images/PokeFace/face_240.png ./out/Assets/XD/face_240.png
cp ../images/Trainers/trainer_62.png ./out/Assets/XD/trainer_62.png
cp ../images/PokeFace/face_335.png ./out/Assets/XD/face_335.png
cp ../images/Trainers/trainer_1.png ./out/Assets/XD/trainer_1.png
cp ../images/PokeFace/face_299.png ./out/Assets/XD/face_299.png
cp ../images/PokeFace/face_060.png ./out/Assets/XD/face_060.png
cp ../images/Trainers/trainer_21.png ./out/Assets/XD/trainer_21.png
cp ../images/PokeFace/face_325.png ./out/Assets/XD/face_325.png
cp ../images/Types/type_12.png ./out/Assets/XD/type_12.png
cp ../images/PokeFace/face_264.png ./out/Assets/XD/face_264.png
cp ../images/PokeBody/body_209.png ./out/Assets/XD/body_209.png
cp ../images/PokeBody/body_248.png ./out/Assets/XD/body_248.png
cp ../images/PokeBody/body_345.png ./out/Assets/XD/body_345.png
cp ../images/PokeBody/body_134.png ./out/Assets/XD/body_134.png
cp ../images/PokeFace/face_226.png ./out/Assets/XD/face_226.png
cp ../images/PokeFace/face_003.png ./out/Assets/XD/face_003.png
cp ../images/Table\ View\ Cells/File\ Cell.png ./out/Assets/XD/File\ Cell.png
cp ../images/PokeBody/body_376.png ./out/Assets/XD/body_376.png
cp ../images/PokeBody/body_160.png ./out/Assets/XD/body_160.png
cp ../images/PokeBody/body_147.png ./out/Assets/XD/body_147.png
cp ../images/PokeFace/face_177.png ./out/Assets/XD/face_177.png
cp ../images/Trainers/trainer_33.png ./out/Assets/XD/trainer_33.png
cp ../images/Trainers/trainer_7.png ./out/Assets/XD/trainer_7.png
cp ../images/PokeFace/face_263.png ./out/Assets/XD/face_263.png
cp ../images/PokeFace/face_090.png ./out/Assets/XD/face_090.png
cp ../images/PokeBody/body_322.png ./out/Assets/XD/body_322.png
cp ../images/PokeBody/body_299.png ./out/Assets/XD/body_299.png
cp ../images/PokeBody/body_370.png ./out/Assets/XD/body_370.png
cp ../images/PokeFace/face_182.png ./out/Assets/XD/face_182.png
cp ../images/Table\ View\ Cells/Tool\ Cell.png ./out/Assets/XD/Tool\ Cell.png
cp ../images/PokeBody/body_027.png ./out/Assets/XD/body_027.png
cp ../images/Trainers/trainer_66.png ./out/Assets/XD/trainer_66.png
cp ../images/PokeFace/face_367.png ./out/Assets/XD/face_367.png
cp ../images/PokeFace/face_203.png ./out/Assets/XD/face_203.png
cp ../images/PokeBody/body_288.png ./out/Assets/XD/body_288.png
cp ../Sublime/SCD.sublime-color-scheme ./out/Assets/XD/SCD.sublime-color-scheme
cp ../images/PokeBody/body_241.png ./out/Assets/XD/body_241.png
cp ../images/PokeFace/face_054.png ./out/Assets/XD/face_054.png
cp ../images/PokeFace/face_083.png ./out/Assets/XD/face_083.png
cp ../images/PokeBody/body_373.png ./out/Assets/XD/body_373.png
cp ../images/PokeFace/face_254.png ./out/Assets/XD/face_254.png
cp ../images/PokeFace/face_104.png ./out/Assets/XD/face_104.png
cp ../images/PokeBody/body_118.png ./out/Assets/XD/body_118.png
cp ../images/PokeFace/face_292.png ./out/Assets/XD/face_292.png
cp ../images/PokeBody/body_007.png ./out/Assets/XD/body_007.png
cp ../images/PokeFace/face_126.png ./out/Assets/XD/face_126.png
cp ../images/PokeBody/body_149.png ./out/Assets/XD/body_149.png
cp ../images/PokeFace/face_157.png ./out/Assets/XD/face_157.png
cp ../images/PokeBody/body_194.png ./out/Assets/XD/body_194.png
cp ../images/PokeBody/body_374.png ./out/Assets/XD/body_374.png
cp ../images/PokeFace/face_064.png ./out/Assets/XD/face_064.png
cp ../images/PokeBody/body_265.png ./out/Assets/XD/body_265.png
cp ../images/PokeBody/body_276.png ./out/Assets/XD/body_276.png
cp ../images/PokeFace/face_286.png ./out/Assets/XD/face_286.png
cp ../images/PokeFace/face_245.png ./out/Assets/XD/face_245.png
cp ../images/PokeFace/face_094.png ./out/Assets/XD/face_094.png
cp ../images/PokeFace/face_399.png ./out/Assets/XD/face_399.png
cp ../images/PokeFace/face_295.png ./out/Assets/XD/face_295.png
cp ../images/PokeBody/body_152.png ./out/Assets/XD/body_152.png
cp ../images/PokeFace/face_113.png ./out/Assets/XD/face_113.png
cp ../images/PokeFace/face_352.png ./out/Assets/XD/face_352.png
cp ../images/PokeFace/face_085.png ./out/Assets/XD/face_085.png
cp ../images/PokeBody/body_024.png ./out/Assets/XD/body_024.png
cp ../images/PokeFace/face_344.png ./out/Assets/XD/face_344.png
cp ../images/PokeFace/face_377.png ./out/Assets/XD/face_377.png
cp ../images/PokeBalls/ball\ purple.png ./out/Assets/XD/ball\ purple.png
cp ../images/PokeBody/body_328.png ./out/Assets/XD/body_328.png
cp ../images/PokeBody/body_021.png ./out/Assets/XD/body_021.png
cp ../images/PokeFace/face_228.png ./out/Assets/XD/face_228.png
cp ../images/PokeBody/body_382.png ./out/Assets/XD/body_382.png
cp ../images/Trainers/trainer_41.png ./out/Assets/XD/trainer_41.png
cp ../images/Types/type_shadow.png ./out/Assets/XD/type_shadow.png
cp ../images/PokeFace/face_341.png ./out/Assets/XD/face_341.png
cp ../images/PokeBody/body_377.png ./out/Assets/XD/body_377.png
cp ../images/PokeFace/face_366.png ./out/Assets/XD/face_366.png
cp ../images/PokeBody/body_180.png ./out/Assets/XD/body_180.png
cp ../images/PokeFace/face_183.png ./out/Assets/XD/face_183.png
cp ../images/PokeFace/face_364.png ./out/Assets/XD/face_364.png
cp ../images/PokeBody/body_111.png ./out/Assets/XD/body_111.png
cp ../images/PokeBody/body_074.png ./out/Assets/XD/body_074.png
cp ../images/PokeFace/face_219.png ./out/Assets/XD/face_219.png
cp ../images/PokeBody/body_308.png ./out/Assets/XD/body_308.png
cp ../images/PokeBody/body_323.png ./out/Assets/XD/body_323.png
cp ../images/Trainers/trainer_10.png ./out/Assets/XD/trainer_10.png
cp ../images/Trainers/trainer_30.png ./out/Assets/XD/trainer_30.png
cp ../images/PokeBody/body_112.png ./out/Assets/XD/body_112.png
cp ../images/PokeFace/face_329.png ./out/Assets/XD/face_329.png
cp ../images/PokeBody/body_399.png ./out/Assets/XD/body_399.png
cp ../images/PokeFace/face_007.png ./out/Assets/XD/face_007.png
cp ../images/PokeFace/face_066.png ./out/Assets/XD/face_066.png
cp ../images/PokeFace/face_067.png ./out/Assets/XD/face_067.png
cp ../images/PokeBody/body_246.png ./out/Assets/XD/body_246.png
cp ../images/PokeBody/body_144.png ./out/Assets/XD/body_144.png
cp ../images/PokeBody/body_121.png ./out/Assets/XD/body_121.png
cp ../images/PokeBody/body_362.png ./out/Assets/XD/body_362.png
cp ../images/PokeFace/face_372.png ./out/Assets/XD/face_372.png
cp ../images/PokeBody/body_397.png ./out/Assets/XD/body_397.png
cp ../images/PokeFace/face_246.png ./out/Assets/XD/face_246.png
cp ../images/PokeFace/face_053.png ./out/Assets/XD/face_053.png
cp ../images/PokeBody/body_154.png ./out/Assets/XD/body_154.png
cp ../images/PokeBody/body_297.png ./out/Assets/XD/body_297.png
cp ../images/PokeBody/body_083.png ./out/Assets/XD/body_083.png
cp ../images/PokeFace/face_082.png ./out/Assets/XD/face_082.png
cp ../images/Trainers/trainer_67.png ./out/Assets/XD/trainer_67.png
cp ../images/PokeBody/body_141.png ./out/Assets/XD/body_141.png
cp ../images/PokeFace/face_118.png ./out/Assets/XD/face_118.png
cp ../images/PokeBody/body_344.png ./out/Assets/XD/body_344.png
cp ../images/PokeFace/face_305.png ./out/Assets/XD/face_305.png
cp ../images/PokeFace/face_077.png ./out/Assets/XD/face_077.png
cp ../images/PokeFace/face_253.png ./out/Assets/XD/face_253.png
cp ../images/PokeFace/face_342.png ./out/Assets/XD/face_342.png
cp ../images/PokeFace/face_150.png ./out/Assets/XD/face_150.png
cp ../images/PokeFace/face_217.png ./out/Assets/XD/face_217.png
cp ../images/PokeFace/face_155.png ./out/Assets/XD/face_155.png
cp ../images/PokeFace/face_301.png ./out/Assets/XD/face_301.png
cp ../images/PokeBody/body_392.png ./out/Assets/XD/body_392.png
cp ../images/PokeBody/body_412.png ./out/Assets/XD/body_412.png
cp ../images/PokeBody/body_108.png ./out/Assets/XD/body_108.png
cp ../images/Types/type_6.png ./out/Assets/XD/type_6.png
cp ../images/PokeFace/face_165.png ./out/Assets/XD/face_165.png
cp ../images/PokeFace/face_051.png ./out/Assets/XD/face_051.png
cp ../images/PokeBody/body_278.png ./out/Assets/XD/body_278.png
cp ../images/PokeFace/face_164.png ./out/Assets/XD/face_164.png
cp ../images/PokeBody/body_066.png ./out/Assets/XD/body_066.png
cp ../images/PokeFace/face_376.png ./out/Assets/XD/face_376.png
cp ../images/PokeBody/body_383.png ./out/Assets/XD/body_383.png
cp ../images/PokeFace/face_168.png ./out/Assets/XD/face_168.png
cp ../images/PokeFace/face_089.png ./out/Assets/XD/face_089.png
cp ../images/PokeFace/face_261.png ./out/Assets/XD/face_261.png
cp ../images/PokeBody/body_018.png ./out/Assets/XD/body_018.png
cp ../images/PokeBody/body_022.png ./out/Assets/XD/body_022.png
cp ../images/PokeFace/face_028.png ./out/Assets/XD/face_028.png
cp ../images/PokeBody/body_378.png ./out/Assets/XD/body_378.png
cp ../images/PokeFace/face_363.png ./out/Assets/XD/face_363.png
cp ../images/PokeFace/face_061.png ./out/Assets/XD/face_061.png
cp ../images/PokeFace/face_163.png ./out/Assets/XD/face_163.png
cp ../images/Trainers/trainer_26.png ./out/Assets/XD/trainer_26.png
cp ../images/PokeBody/body_222.png ./out/Assets/XD/body_222.png
cp ../images/PokeBody/body_369.png ./out/Assets/XD/body_369.png
cp ../images/Trainers/trainer_63.png ./out/Assets/XD/trainer_63.png
cp ../images/PokeBody/body_170.png ./out/Assets/XD/body_170.png
cp ../images/PokeBody/body_084.png ./out/Assets/XD/body_084.png
cp ../images/PokeFace/face_079.png ./out/Assets/XD/face_079.png
cp ../JSON/XD/Move\ Categories.json ./out/Assets/XD/Move\ Categories.json
cp ../images/PokeBody/body_331.png ./out/Assets/XD/body_331.png
cp ../images/PokeFace/face_277.png ./out/Assets/XD/face_277.png
cp ../images/Types/type_8.png ./out/Assets/XD/type_8.png
cp ../images/PokeBody/body_213.png ./out/Assets/XD/body_213.png
cp ../images/PokeBody/body_207.png ./out/Assets/XD/body_207.png
cp ../images/Trainers/trainer_8.png ./out/Assets/XD/trainer_8.png
cp ../images/PokeFace/face_011.png ./out/Assets/XD/face_011.png
cp ../images/PokeBody/body_151.png ./out/Assets/XD/body_151.png
cp ../images/PokeBody/body_342.png ./out/Assets/XD/body_342.png
cp ../images/PokeBody/body_135.png ./out/Assets/XD/body_135.png
cp ../images/PokeFace/face_024.png ./out/Assets/XD/face_024.png
cp ../images/Types/type_fairy.png ./out/Assets/XD/type_fairy.png
cp ../images/PokeFace/face_275.png ./out/Assets/XD/face_275.png
cp ../images/PokeBody/body_208.png ./out/Assets/XD/body_208.png
cp ../images/PokeBody/body_069.png ./out/Assets/XD/body_069.png
cp ../images/PokeBody/body_046.png ./out/Assets/XD/body_046.png
cp ../images/PokeFace/face_112.png ./out/Assets/XD/face_112.png
cp ../images/PokeBody/body_219.png ./out/Assets/XD/body_219.png
cp ../images/PokeFace/face_001.png ./out/Assets/XD/face_001.png
cp ../images/PokeBody/body_114.png ./out/Assets/XD/body_114.png
cp ../images/PokeBody/body_087.png ./out/Assets/XD/body_087.png
cp ../images/PokeBody/body_268.png ./out/Assets/XD/body_268.png
cp ../images/PokeBody/body_090.png ./out/Assets/XD/body_090.png
cp ../images/PokeFace/face_273.png ./out/Assets/XD/face_273.png
cp ../images/PokeFace/face_107.png ./out/Assets/XD/face_107.png
cp ../images/PokeBody/body_145.png ./out/Assets/XD/body_145.png
cp ../JSON/XD/Move\ Effects.json ./out/Assets/XD/Move\ Effects.json
cp ../images/PokeBody/body_200.png ./out/Assets/XD/body_200.png
cp ../images/PokeFace/face_340.png ./out/Assets/XD/face_340.png
cp ../images/PokeBody/body_166.png ./out/Assets/XD/body_166.png
cp ../images/PokeFace/face_033.png ./out/Assets/XD/face_033.png
cp ../images/PokeFace/face_251.png ./out/Assets/XD/face_251.png
cp ../images/Trainers/trainer_6.png ./out/Assets/XD/trainer_6.png
cp ../images/PokeBody/body_106.png ./out/Assets/XD/body_106.png
cp ../images/Trainers/trainer_29.png ./out/Assets/XD/trainer_29.png
cp ../images/PokeBody/body_162.png ./out/Assets/XD/body_162.png
cp ../images/PokeFace/face_406.png ./out/Assets/XD/face_406.png
cp ../images/PokeBody/body_216.png ./out/Assets/XD/body_216.png
cp ../images/PokeBody/body_326.png ./out/Assets/XD/body_326.png
cp ../images/PokeFace/face_392.png ./out/Assets/XD/face_392.png
cp ../images/PokeBody/body_387.png ./out/Assets/XD/body_387.png
cp ../JSON/XD/Original\ Pokemon.json ./out/Assets/XD/Original\ Pokemon.json
cp ../images/PokeFace/face_002.png ./out/Assets/XD/face_002.png
cp ../images/PokeFace/face_318.png ./out/Assets/XD/face_318.png
cp ../images/PokeBody/body_177.png ./out/Assets/XD/body_177.png
cp ../images/PokeBody/body_049.png ./out/Assets/XD/body_049.png
cp ../images/PokeBody/body_350.png ./out/Assets/XD/body_350.png
cp ../images/PokeBody/body_324.png ./out/Assets/XD/body_324.png
cp ../images/PokeFace/face_236.png ./out/Assets/XD/face_236.png
cp ../images/PokeBody/body_081.png ./out/Assets/XD/body_081.png
cp ../images/PokeBody/body_129.png ./out/Assets/XD/body_129.png
cp ../images/PokeFace/face_312.png ./out/Assets/XD/face_312.png
cp ../images/PokeFace/face_108.png ./out/Assets/XD/face_108.png
cp ../images/Types/type_11.png ./out/Assets/XD/type_11.png
cp ../images/PokeBody/body_388.png ./out/Assets/XD/body_388.png
cp ../images/PokeFace/face_222.png ./out/Assets/XD/face_222.png
cp ../images/PokeFace/face_088.png ./out/Assets/XD/face_088.png
cp ../images/PokeBody/body_352.png ./out/Assets/XD/body_352.png
cp ../images/PokeBody/body_127.png ./out/Assets/XD/body_127.png
cp ../images/PokeFace/face_262.png ./out/Assets/XD/face_262.png
cp ../images/PokeFace/face_234.png ./out/Assets/XD/face_234.png
cp ../images/PokeFace/face_259.png ./out/Assets/XD/face_259.png
cp ../images/PokeBody/body_003.png ./out/Assets/XD/body_003.png
cp ../images/PokeBody/body_261.png ./out/Assets/XD/body_261.png
cp ../images/PokeBody/body_064.png ./out/Assets/XD/body_064.png
cp ../images/PokeBody/body_088.png ./out/Assets/XD/body_088.png
cp ../images/PokeFace/face_351.png ./out/Assets/XD/face_351.png
cp ../images/PokeFace/face_313.png ./out/Assets/XD/face_313.png
cp ../images/PokeFace/face_208.png ./out/Assets/XD/face_208.png
cp ../images/PokeFace/face_356.png ./out/Assets/XD/face_356.png
cp ../images/PokeBody/body_099.png ./out/Assets/XD/body_099.png
cp ../images/Trainers/trainer_3.png ./out/Assets/XD/trainer_3.png
cp ../images/Trainers/trainer_57.png ./out/Assets/XD/trainer_57.png
cp ../images/PokeFace/face_231.png ./out/Assets/XD/face_231.png
cp ../images/PokeBody/body_240.png ./out/Assets/XD/body_240.png
cp ../images/PokeFace/face_221.png ./out/Assets/XD/face_221.png
cp ../images/PokeBody/body_229.png ./out/Assets/XD/body_229.png
cp ../images/PokeFace/face_141.png ./out/Assets/XD/face_141.png
cp ../images/PokeFace/face_357.png ./out/Assets/XD/face_357.png
cp ../images/Trainers/trainer_16.png ./out/Assets/XD/trainer_16.png
cp ../images/PokeFace/face_375.png ./out/Assets/XD/face_375.png
cp ../images/PokeBody/body_408.png ./out/Assets/XD/body_408.png
cp ../images/PokeFace/face_006.png ./out/Assets/XD/face_006.png
cp ../images/PokeFace/face_186.png ./out/Assets/XD/face_186.png
cp ../images/PokeFace/face_127.png ./out/Assets/XD/face_127.png
cp ../images/PokeFace/face_218.png ./out/Assets/XD/face_218.png
cp ../images/Trainers/trainer_9.png ./out/Assets/XD/trainer_9.png
cp ../images/PokeBody/body_191.png ./out/Assets/XD/body_191.png
cp ../images/PokeBody/body_130.png ./out/Assets/XD/body_130.png
cp ../images/PokeBody/body_272.png ./out/Assets/XD/body_272.png
cp ../images/PokeFace/face_306.png ./out/Assets/XD/face_306.png
cp ../images/PokeBody/body_059.png ./out/Assets/XD/body_059.png
cp ../images/PokeBody/body_391.png ./out/Assets/XD/body_391.png
cp ../images/PokeFace/face_093.png ./out/Assets/XD/face_093.png
cp ../images/PokeBody/body_198.png ./out/Assets/XD/body_198.png
cp ../images/PokeFace/face_380.png ./out/Assets/XD/face_380.png
cp ../images/PokeFace/face_096.png ./out/Assets/XD/face_096.png
cp ../images/PokeBody/body_159.png ./out/Assets/XD/body_159.png
cp ../images/PokeFace/face_410.png ./out/Assets/XD/face_410.png
cp ../Sublime/XDScript.sublime-color-scheme ./out/Assets/XD/XDScript.sublime-color-scheme
cp ../images/PokeBody/body_338.png ./out/Assets/XD/body_338.png
cp ../images/PokeBody/body_249.png ./out/Assets/XD/body_249.png
cp ../images/PokeFace/face_239.png ./out/Assets/XD/face_239.png
cp ../images/PokeBody/body_178.png ./out/Assets/XD/body_178.png
cp ../images/PokeFace/face_084.png ./out/Assets/XD/face_084.png
cp ../images/PokeFace/face_097.png ./out/Assets/XD/face_097.png
cp ../images/Trainers/trainer_39.png ./out/Assets/XD/trainer_39.png
cp ../images/PokeFace/face_148.png ./out/Assets/XD/face_148.png
cp ../images/PokeFace/face_354.png ./out/Assets/XD/face_354.png
cp ../images/PokeFace/face_065.png ./out/Assets/XD/face_065.png
cp ../images/PokeBody/body_186.png ./out/Assets/XD/body_186.png
cp ../images/Trainers/trainer_23.png ./out/Assets/XD/trainer_23.png
cp ../images/PokeBody/body_221.png ./out/Assets/XD/body_221.png
cp ../images/PokeBody/body_254.png ./out/Assets/XD/body_254.png
cp ../images/PokeBody/body_266.png ./out/Assets/XD/body_266.png
cp ../images/PokeFace/face_384.png ./out/Assets/XD/face_384.png
cp ../images/PokeFace/face_232.png ./out/Assets/XD/face_232.png
cp ../images/PokeBody/body_048.png ./out/Assets/XD/body_048.png
cp ../images/PokeBody/body_009.png ./out/Assets/XD/body_009.png
cp ../images/PokeBody/body_042.png ./out/Assets/XD/body_042.png
cp ../images/PokeFace/face_320.png ./out/Assets/XD/face_320.png
cp ../images/PokeBody/body_309.png ./out/Assets/XD/body_309.png
cp ../images/PokeFace/face_349.png ./out/Assets/XD/face_349.png
cp ../images/PokeBody/body_120.png ./out/Assets/XD/body_120.png
cp ../images/PokeFace/face_394.png ./out/Assets/XD/face_394.png
cp ../images/PokeBody/body_294.png ./out/Assets/XD/body_294.png
cp ../images/PokeBody/body_002.png ./out/Assets/XD/body_002.png
cp ../images/PokeBody/body_065.png ./out/Assets/XD/body_065.png
cp ../images/PokeFace/face_252.png ./out/Assets/XD/face_252.png
cp ../images/Trainers/trainer_37.png ./out/Assets/XD/trainer_37.png
cp ../images/PokeFace/face_267.png ./out/Assets/XD/face_267.png
cp ../images/PokeFace/face_087.png ./out/Assets/XD/face_087.png
cp ../images/PokeFace/face_197.png ./out/Assets/XD/face_197.png
cp ../images/PokeFace/face_131.png ./out/Assets/XD/face_131.png
cp ../images/PokeBody/body_157.png ./out/Assets/XD/body_157.png
cp ../images/PokeFace/face_311.png ./out/Assets/XD/face_311.png
cp ../images/PokeBody/body_360.png ./out/Assets/XD/body_360.png
cp ../images/PokeFace/face_173.png ./out/Assets/XD/face_173.png
cp ../images/PokeBody/body_286.png ./out/Assets/XD/body_286.png
cp ../images/PokeBody/body_336.png ./out/Assets/XD/body_336.png
cp ../images/PokeBody/body_098.png ./out/Assets/XD/body_098.png
cp ../images/PokeBody/body_105.png ./out/Assets/XD/body_105.png
cp ../images/PokeFace/face_048.png ./out/Assets/XD/face_048.png
cp ../images/PokeBody/body_032.png ./out/Assets/XD/body_032.png
cp ../images/PokeFace/face_120.png ./out/Assets/XD/face_120.png
cp ../images/PokeBody/body_215.png ./out/Assets/XD/body_215.png
cp ../images/PokeFace/face_268.png ./out/Assets/XD/face_268.png
cp ../images/PokeBody/body_403.png ./out/Assets/XD/body_403.png
cp ../images/PokeBody/body_302.png ./out/Assets/XD/body_302.png
cp ../images/PokeBody/body_036.png ./out/Assets/XD/body_036.png
cp ../images/PokeBody/body_349.png ./out/Assets/XD/body_349.png
cp ../images/PokeBody/body_303.png ./out/Assets/XD/body_303.png
cp ../images/PokeBody/body_140.png ./out/Assets/XD/body_140.png
cp ../images/PokeBody/body_026.png ./out/Assets/XD/body_026.png
cp ../images/PokeFace/face_216.png ./out/Assets/XD/face_216.png
cp ../images/PokeFace/face_004.png ./out/Assets/XD/face_004.png
cp ../images/PokeBody/body_030.png ./out/Assets/XD/body_030.png
cp ../images/PokeBody/body_128.png ./out/Assets/XD/body_128.png
cp ../images/Types/type_15.png ./out/Assets/XD/type_15.png
cp ../images/PokeBody/body_184.png ./out/Assets/XD/body_184.png
cp ../images/PokeBody/body_293.png ./out/Assets/XD/body_293.png
cp ../images/PokeFace/face_086.png ./out/Assets/XD/face_086.png
cp ../images/Trainers/trainer_13.png ./out/Assets/XD/trainer_13.png
cp ../images/Trainers/trainer_64.png ./out/Assets/XD/trainer_64.png
cp ../images/PokeFace/face_202.png ./out/Assets/XD/face_202.png
cp ../images/PokeBody/body_091.png ./out/Assets/XD/body_091.png
cp ../images/PokeBody/body_076.png ./out/Assets/XD/body_076.png
cp ../images/PokeBody/body_414.png ./out/Assets/XD/body_414.png
cp ../images/PokeBody/body_217.png ./out/Assets/XD/body_217.png
cp ../images/PokeBody/body_218.png ./out/Assets/XD/body_218.png
cp ../images/PokeFace/face_102.png ./out/Assets/XD/face_102.png
cp ../images/Trainers/trainer_34.png ./out/Assets/XD/trainer_34.png
cp ../images/PokeBody/body_043.png ./out/Assets/XD/body_043.png
cp ../images/Types/type_10.png ./out/Assets/XD/type_10.png
cp ../images/PokeFace/face_195.png ./out/Assets/XD/face_195.png
cp ../images/Trainers/trainer_12.png ./out/Assets/XD/trainer_12.png
cp ../images/Types/type_14.png ./out/Assets/XD/type_14.png
cp ../images/PokeFace/face_280.png ./out/Assets/XD/face_280.png
cp ../images/PokeFace/face_387.png ./out/Assets/XD/face_387.png
cp ../images/PokeFace/face_369.png ./out/Assets/XD/face_369.png
cp ../images/PokeBody/body_063.png ./out/Assets/XD/body_063.png
cp ../images/PokeFace/face_287.png ./out/Assets/XD/face_287.png
cp ../images/PokeFace/face_248.png ./out/Assets/XD/face_248.png
cp ../images/PokeBody/body_175.png ./out/Assets/XD/body_175.png
cp ../images/PokeFace/face_103.png ./out/Assets/XD/face_103.png
cp ../images/PokeBody/body_228.png ./out/Assets/XD/body_228.png
cp ../images/PokeBody/body_137.png ./out/Assets/XD/body_137.png
cp ../images/PokeBody/body_013.png ./out/Assets/XD/body_013.png
cp ../images/PokeFace/face_321.png ./out/Assets/XD/face_321.png
cp ../images/PokeBody/body_060.png ./out/Assets/XD/body_060.png
cp ../images/PokeBody/body_193.png ./out/Assets/XD/body_193.png
cp ../Sublime/XDScript.sublime-completions ./out/Assets/XD/XDScript.sublime-completions
cp ../images/PokeFace/face_391.png ./out/Assets/XD/face_391.png
cp ../images/PokeFace/face_040.png ./out/Assets/XD/face_040.png
cp ../images/PokeFace/face_146.png ./out/Assets/XD/face_146.png
cp ../images/PokeBody/body_110.png ./out/Assets/XD/body_110.png
cp ../images/PokeFace/face_078.png ./out/Assets/XD/face_078.png
cp ../images/Types/type_0.png ./out/Assets/XD/type_0.png
cp ../images/PokeBody/body_197.png ./out/Assets/XD/body_197.png
cp ../images/PokeFace/face_201.png ./out/Assets/XD/face_201.png
cp ../images/PokeBody/body_034.png ./out/Assets/XD/body_034.png
cp ../images/PokeBody/body_231.png ./out/Assets/XD/body_231.png
cp ../images/PokeFace/face_119.png ./out/Assets/XD/face_119.png
cp ../images/PokeBody/body_204.png ./out/Assets/XD/body_204.png
cp ../images/PokeBody/body_023.png ./out/Assets/XD/body_023.png
cp ../images/PokeBody/body_411.png ./out/Assets/XD/body_411.png
cp ../images/Types/type_7.png ./out/Assets/XD/type_7.png
cp ../images/PokeBody/body_171.png ./out/Assets/XD/body_171.png
cp ../images/PokeFace/face_385.png ./out/Assets/XD/face_385.png
cp ../images/PokeFace/face_326.png ./out/Assets/XD/face_326.png
cp ../images/PokeBody/body_357.png ./out/Assets/XD/body_357.png
cp ../images/PokeBody/body_253.png ./out/Assets/XD/body_253.png
cp ../images/Trainers/trainer_14.png ./out/Assets/XD/trainer_14.png
cp ../images/PokeFace/face_361.png ./out/Assets/XD/face_361.png
cp ../images/Trainers/trainer_38.png ./out/Assets/XD/trainer_38.png
cp ../images/PokeFace/face_283.png ./out/Assets/XD/face_283.png
cp ../images/PokeBody/body_361.png ./out/Assets/XD/body_361.png
cp ../images/PokeFace/face_074.png ./out/Assets/XD/face_074.png
cp ../images/PokeFace/face_144.png ./out/Assets/XD/face_144.png
cp ../images/PokeBody/body_057.png ./out/Assets/XD/body_057.png
cp ../images/PokeBody/body_327.png ./out/Assets/XD/body_327.png
cp ../images/PokeFace/face_316.png ./out/Assets/XD/face_316.png
cp ../images/PokeFace/face_098.png ./out/Assets/XD/face_098.png
cp ../images/PokeBody/body_259.png ./out/Assets/XD/body_259.png
cp ../images/PokeFace/face_114.png ./out/Assets/XD/face_114.png
cp ../images/PokeBody/body_122.png ./out/Assets/XD/body_122.png
cp ../images/PokeFace/face_140.png ./out/Assets/XD/face_140.png
cp ../images/PokeFace/face_303.png ./out/Assets/XD/face_303.png
cp ../images/PokeFace/face_151.png ./out/Assets/XD/face_151.png
cp ../images/PokeBody/body_223.png ./out/Assets/XD/body_223.png
cp ../images/PokeFace/face_049.png ./out/Assets/XD/face_049.png
cp ../images/Trainers/trainer_24.png ./out/Assets/XD/trainer_24.png
cp ../images/PokeFace/face_298.png ./out/Assets/XD/face_298.png
cp ../images/PokeBody/body_337.png ./out/Assets/XD/body_337.png
cp ../images/PokeBody/body_123.png ./out/Assets/XD/body_123.png
cp ../images/PokeBody/body_000.png ./out/Assets/XD/body_000.png
cp ../images/PokeFace/face_013.png ./out/Assets/XD/face_013.png
cp ../images/PokeBalls/ball\ red.png ./out/Assets/XD/ball\ red.png
cp ../images/PokeBody/body_389.png ./out/Assets/XD/body_389.png
cp ../JSON/XD/Moves\ raw.json ./out/Assets/XD/Moves\ raw.json
cp ../images/PokeBody/body_094.png ./out/Assets/XD/body_094.png
cp ../images/Types/type_5.png ./out/Assets/XD/type_5.png
cp ../images/PokeFace/face_334.png ./out/Assets/XD/face_334.png
cp ../images/PokeBody/body_267.png ./out/Assets/XD/body_267.png
cp ../images/PokeFace/face_106.png ./out/Assets/XD/face_106.png
cp ../images/PokeBody/body_365.png ./out/Assets/XD/body_365.png
cp ../images/PokeBody/body_103.png ./out/Assets/XD/body_103.png
cp ../images/Trainers/trainer_52.png ./out/Assets/XD/trainer_52.png
cp ../images/PokeBody/body_158.png ./out/Assets/XD/body_158.png
cp ../images/PokeBody/body_300.png ./out/Assets/XD/body_300.png
cp ../images/PokeFace/face_383.png ./out/Assets/XD/face_383.png
cp ../images/PokeFace/face_327.png ./out/Assets/XD/face_327.png
cp ../images/PokeBody/body_310.png ./out/Assets/XD/body_310.png
cp ../images/PokeFace/face_204.png ./out/Assets/XD/face_204.png
cp ../images/PokeBody/body_315.png ./out/Assets/XD/body_315.png
cp ../images/PokeBody/body_164.png ./out/Assets/XD/body_164.png
cp ../images/Trainers/trainer_2.png ./out/Assets/XD/trainer_2.png
cp ../images/PokeBody/body_199.png ./out/Assets/XD/body_199.png
cp ../images/PokeBody/body_375.png ./out/Assets/XD/body_375.png
cp ../images/PokeBody/body_406.png ./out/Assets/XD/body_406.png
cp ../images/PokeFace/face_270.png ./out/Assets/XD/face_270.png
cp ../images/PokeFace/face_139.png ./out/Assets/XD/face_139.png
cp ../images/PokeBody/body_312.png ./out/Assets/XD/body_312.png
cp ../images/PokeBody/body_346.png ./out/Assets/XD/body_346.png
cp ../images/PokeFace/face_010.png ./out/Assets/XD/face_010.png
cp ../images/PokeBody/body_366.png ./out/Assets/XD/body_366.png
cp ../images/PokeBody/body_280.png ./out/Assets/XD/body_280.png
cp ../images/PokeBody/body_409.png ./out/Assets/XD/body_409.png
cp ../images/PokeFace/face_130.png ./out/Assets/XD/face_130.png
cp ../images/PokeFace/face_284.png ./out/Assets/XD/face_284.png
cp ../images/Trainers/trainer_48.png ./out/Assets/XD/trainer_48.png
cp ../images/PokeBody/body_325.png ./out/Assets/XD/body_325.png
cp ../images/PokeFace/face_411.png ./out/Assets/XD/face_411.png
cp ../images/PokeFace/face_158.png ./out/Assets/XD/face_158.png
cp ../images/PokeBody/body_041.png ./out/Assets/XD/body_041.png
cp ../images/PokeFace/face_281.png ./out/Assets/XD/face_281.png
cp ../images/PokeBody/body_058.png ./out/Assets/XD/body_058.png
cp ../images/PokeBody/body_196.png ./out/Assets/XD/body_196.png
cp ../images/Types/type_9.png ./out/Assets/XD/type_9.png
cp ../images/PokeFace/face_081.png ./out/Assets/XD/face_081.png
cp ../images/PokeBody/body_284.png ./out/Assets/XD/body_284.png
cp ../images/PokeBody/body_116.png ./out/Assets/XD/body_116.png
cp ../images/PokeBody/body_020.png ./out/Assets/XD/body_020.png
cp ../images/PokeFace/face_365.png ./out/Assets/XD/face_365.png
cp ../images/PokeBody/body_295.png ./out/Assets/XD/body_295.png
cp ../images/PokeBody/body_298.png ./out/Assets/XD/body_298.png
cp ../images/PokeBody/body_348.png ./out/Assets/XD/body_348.png
cp ../images/PokeFace/face_109.png ./out/Assets/XD/face_109.png
cp ../images/PokeFace/face_249.png ./out/Assets/XD/face_249.png
cp ../images/PokeFace/face_194.png ./out/Assets/XD/face_194.png
cp ../images/PokeFace/face_145.png ./out/Assets/XD/face_145.png
cp ../images/PokeFace/face_068.png ./out/Assets/XD/face_068.png
cp ../images/PokeFace/face_242.png ./out/Assets/XD/face_242.png
cp ../images/Trainers/trainer_31.png ./out/Assets/XD/trainer_31.png
cp ../images/PokeFace/face_072.png ./out/Assets/XD/face_072.png
cp ../images/PokeBody/body_405.png ./out/Assets/XD/body_405.png
cp ../images/PokeFace/face_331.png ./out/Assets/XD/face_331.png
cp ../images/PokeFace/face_117.png ./out/Assets/XD/face_117.png
cp ../images/PokeBody/body_356.png ./out/Assets/XD/body_356.png
cp ../images/PokeBody/body_394.png ./out/Assets/XD/body_394.png
cp ../images/PokeFace/face_171.png ./out/Assets/XD/face_171.png
cp ../images/PokeBody/body_011.png ./out/Assets/XD/body_011.png
cp ../images/PokeFace/face_381.png ./out/Assets/XD/face_381.png
cp ../images/PokeFace/face_294.png ./out/Assets/XD/face_294.png
cp ../images/PokeBody/body_273.png ./out/Assets/XD/body_273.png
cp ../images/PokeFace/face_152.png ./out/Assets/XD/face_152.png
cp ../images/Trainers/trainer_50.png ./out/Assets/XD/trainer_50.png
cp ../images/PokeBody/body_045.png ./out/Assets/XD/body_045.png
cp ../images/PokeFace/face_310.png ./out/Assets/XD/face_310.png
cp ../images/PokeFace/face_339.png ./out/Assets/XD/face_339.png
cp ../images/PokeFace/face_332.png ./out/Assets/XD/face_332.png
cp ../images/PokeFace/face_137.png ./out/Assets/XD/face_137.png
cp ../images/PokeBody/body_190.png ./out/Assets/XD/body_190.png
cp ../images/PokeBody/body_304.png ./out/Assets/XD/body_304.png
cp ../images/PokeBody/body_047.png ./out/Assets/XD/body_047.png
cp ../images/PokeFace/face_138.png ./out/Assets/XD/face_138.png
cp ../images/PokeFace/face_336.png ./out/Assets/XD/face_336.png
cp ../images/PokeFace/face_386.png ./out/Assets/XD/face_386.png
cp ../images/PokeBody/body_332.png ./out/Assets/XD/body_332.png
cp ../images/PokeFace/face_401.png ./out/Assets/XD/face_401.png
cp ../images/Trainers/trainer_28.png ./out/Assets/XD/trainer_28.png
cp ../images/PokeFace/face_129.png ./out/Assets/XD/face_129.png
cp ../images/PokeBody/body_189.png ./out/Assets/XD/body_189.png
cp ../images/PokeFace/face_350.png ./out/Assets/XD/face_350.png
cp ../images/PokeBody/body_115.png ./out/Assets/XD/body_115.png
cp ../images/PokeFace/face_031.png ./out/Assets/XD/face_031.png
cp ../images/PokeBody/body_192.png ./out/Assets/XD/body_192.png
cp ../images/PokeFace/face_319.png ./out/Assets/XD/face_319.png
cp ../images/PokeFace/face_159.png ./out/Assets/XD/face_159.png
cp ../images/PokeBody/body_404.png ./out/Assets/XD/body_404.png
cp ../images/PokeBody/body_238.png ./out/Assets/XD/body_238.png
cp ../images/PokeFace/face_400.png ./out/Assets/XD/face_400.png
cp ../images/PokeBody/body_271.png ./out/Assets/XD/body_271.png
cp ../images/PokeBody/body_188.png ./out/Assets/XD/body_188.png
cp ../images/PokeBody/body_104.png ./out/Assets/XD/body_104.png
cp ../images/PokeBody/body_334.png ./out/Assets/XD/body_334.png
cp ../images/PokeFace/face_333.png ./out/Assets/XD/face_333.png
cp ../images/PokeFace/face_044.png ./out/Assets/XD/face_044.png
cp ../images/Trainers/trainer_49.png ./out/Assets/XD/trainer_49.png
cp ../images/PokeFace/face_099.png ./out/Assets/XD/face_099.png
cp ../images/PokeBody/body_339.png ./out/Assets/XD/body_339.png
cp ../images/PokeFace/face_052.png ./out/Assets/XD/face_052.png
cp ../images/PokeFace/face_414.png ./out/Assets/XD/face_414.png
cp ../images/PokeFace/face_289.png ./out/Assets/XD/face_289.png
cp ../images/Trainers/trainer_35.png ./out/Assets/XD/trainer_35.png
cp ../images/PokeBody/body_330.png ./out/Assets/XD/body_330.png
cp ../images/PokeFace/face_038.png ./out/Assets/XD/face_038.png
cp ../images/PokeFace/face_276.png ./out/Assets/XD/face_276.png
cp ../images/PokeFace/face_124.png ./out/Assets/XD/face_124.png
cp ../images/PokeBody/body_413.png ./out/Assets/XD/body_413.png
cp ../images/PokeBody/body_113.png ./out/Assets/XD/body_113.png
cp ../images/PokeFace/face_207.png ./out/Assets/XD/face_207.png
cp ../images/PokeBody/body_093.png ./out/Assets/XD/body_093.png
cp ../images/Trainers/trainer_65.png ./out/Assets/XD/trainer_65.png
cp ../images/PokeFace/face_355.png ./out/Assets/XD/face_355.png
cp ../images/PokeFace/face_178.png ./out/Assets/XD/face_178.png
cp ../images/PokeFace/face_345.png ./out/Assets/XD/face_345.png
cp ../Sublime/XDScript.sublime-settings ./out/Assets/XD/XDScript.sublime-settings
cp ../images/PokeBody/body_019.png ./out/Assets/XD/body_019.png
cp ../images/PokeFace/face_290.png ./out/Assets/XD/face_290.png
cp ../images/PokeFace/face_069.png ./out/Assets/XD/face_069.png
cp ../images/PokeBody/body_333.png ./out/Assets/XD/body_333.png
cp ../images/PokeBody/body_005.png ./out/Assets/XD/body_005.png
cp ../images/Types/type_17.png ./out/Assets/XD/type_17.png
cp ../images/PokeFace/face_358.png ./out/Assets/XD/face_358.png
cp ../images/PokeBody/body_274.png ./out/Assets/XD/body_274.png
cp ../images/Trainers/trainer_0.png ./out/Assets/XD/trainer_0.png
cp ../images/PokeBody/body_230.png ./out/Assets/XD/body_230.png
cp ../images/PokeFace/face_181.png ./out/Assets/XD/face_181.png
cp ../images/PokeBody/body_264.png ./out/Assets/XD/body_264.png
cp ../images/PokeFace/face_243.png ./out/Assets/XD/face_243.png
cp ../JSON/XD/Pokemon\ Stats\ raw.json ./out/Assets/XD/Pokemon\ Stats\ raw.json
cp ../images/PokeFace/face_020.png ./out/Assets/XD/face_020.png
cp ../images/PokeBody/body_185.png ./out/Assets/XD/body_185.png
cp ../images/PokeFace/face_162.png ./out/Assets/XD/face_162.png
cp ../images/PokeFace/face_238.png ./out/Assets/XD/face_238.png
cp ../images/PokeBody/body_233.png ./out/Assets/XD/body_233.png
cp ../images/PokeFace/face_359.png ./out/Assets/XD/face_359.png
cp ../images/PokeBody/body_028.png ./out/Assets/XD/body_028.png
cp ../images/PokeFace/face_184.png ./out/Assets/XD/face_184.png
cp ../images/PokeBody/body_282.png ./out/Assets/XD/body_282.png
cp ../images/PokeFace/face_330.png ./out/Assets/XD/face_330.png
cp ../images/PokeBody/body_001.png ./out/Assets/XD/body_001.png
cp ../images/PokeBody/body_285.png ./out/Assets/XD/body_285.png
cp ../images/PokeBody/body_227.png ./out/Assets/XD/body_227.png
cp ../images/PokeBody/body_101.png ./out/Assets/XD/body_101.png
cp ../images/PokeFace/face_174.png ./out/Assets/XD/face_174.png
cp ../images/PokeBody/body_117.png ./out/Assets/XD/body_117.png
cp ../images/PokeFace/face_282.png ./out/Assets/XD/face_282.png
cp ../images/PokeBody/body_380.png ./out/Assets/XD/body_380.png
cp ../images/PokeBody/body_319.png ./out/Assets/XD/body_319.png
cp ../images/PokeBody/body_256.png ./out/Assets/XD/body_256.png
cp ../images/PokeBody/body_052.png ./out/Assets/XD/body_052.png
cp ../images/PokeBody/body_025.png ./out/Assets/XD/body_025.png
cp ../images/PokeFace/face_100.png ./out/Assets/XD/face_100.png
cp ../images/PokeBody/body_269.png ./out/Assets/XD/body_269.png
cp ../images/PokeFace/face_176.png ./out/Assets/XD/face_176.png
cp ../images/PokeBody/body_316.png ./out/Assets/XD/body_316.png
cp ../images/PokeBody/body_329.png ./out/Assets/XD/body_329.png
cp ../images/PokeFace/face_192.png ./out/Assets/XD/face_192.png
cp ../images/PokeBody/body_363.png ./out/Assets/XD/body_363.png
cp ../images/Trainers/trainer_40.png ./out/Assets/XD/trainer_40.png
cp ../images/PokeBody/body_247.png ./out/Assets/XD/body_247.png
cp ../images/PokeFace/face_285.png ./out/Assets/XD/face_285.png
cp ../images/PokeBody/body_155.png ./out/Assets/XD/body_155.png
cp ../images/PokeFace/face_166.png ./out/Assets/XD/face_166.png
cp ../images/PokeFace/face_360.png ./out/Assets/XD/face_360.png
cp ../images/PokeBody/body_085.png ./out/Assets/XD/body_085.png
cp ../images/PokeBody/body_367.png ./out/Assets/XD/body_367.png
cp ../images/PokeFace/face_014.png ./out/Assets/XD/face_014.png
cp ../images/PokeBody/body_039.png ./out/Assets/XD/body_039.png
cp ../images/Trainers/trainer_20.png ./out/Assets/XD/trainer_20.png
cp ../images/PokeBody/body_262.png ./out/Assets/XD/body_262.png
cp ../images/PokeBody/body_053.png ./out/Assets/XD/body_053.png
cp ../images/PokeBody/body_055.png ./out/Assets/XD/body_055.png
cp ../images/PokeBody/body_174.png ./out/Assets/XD/body_174.png
cp ../images/PokeBody/body_379.png ./out/Assets/XD/body_379.png
cp ../images/Table\ View\ Cells/Item\ Cell.png ./out/Assets/XD/Item\ Cell.png
cp ../images/PokeBody/body_368.png ./out/Assets/XD/body_368.png
cp ../images/Trainers/trainer_58.png ./out/Assets/XD/trainer_58.png
cp ../images/PokeFace/face_307.png ./out/Assets/XD/face_307.png
cp ../images/PokeBody/body_133.png ./out/Assets/XD/body_133.png
cp ../images/PokeFace/face_413.png ./out/Assets/XD/face_413.png
cp ../images/PokeBody/body_396.png ./out/Assets/XD/body_396.png
cp ../images/PokeFace/face_250.png ./out/Assets/XD/face_250.png
cp ../images/PokeFace/face_379.png ./out/Assets/XD/face_379.png
cp ../images/PokeBody/body_131.png ./out/Assets/XD/body_131.png
cp ../images/PokeBody/body_070.png ./out/Assets/XD/body_070.png
cp ../images/PokeBody/body_318.png ./out/Assets/XD/body_318.png
cp ../images/Trainers/trainer_27.png ./out/Assets/XD/trainer_27.png
cp ../images/PokeBody/body_398.png ./out/Assets/XD/body_398.png
cp ../images/PokeBody/body_279.png ./out/Assets/XD/body_279.png
cp ../images/PokeFace/face_214.png ./out/Assets/XD/face_214.png
cp ../images/PokeBody/body_008.png ./out/Assets/XD/body_008.png
cp ../images/PokeFace/face_059.png ./out/Assets/XD/face_059.png
cp ../images/PokeFace/face_043.png ./out/Assets/XD/face_043.png
cp ../images/PokeFace/face_230.png ./out/Assets/XD/face_230.png
cp ../images/PokeFace/face_132.png ./out/Assets/XD/face_132.png
cp ../images/PokeBody/body_073.png ./out/Assets/XD/body_073.png
cp ../images/PokeBody/body_313.png ./out/Assets/XD/body_313.png
cp ../images/PokeBody/body_095.png ./out/Assets/XD/body_095.png
cp ../images/PokeBody/body_077.png ./out/Assets/XD/body_077.png
cp ../images/PokeBody/body_176.png ./out/Assets/XD/body_176.png
cp ../images/PokeFace/face_317.png ./out/Assets/XD/face_317.png
cp ../images/PokeFace/face_012.png ./out/Assets/XD/face_012.png
cp ../images/PokeBody/body_386.png ./out/Assets/XD/body_386.png
cp ../images/PokeFace/face_210.png ./out/Assets/XD/face_210.png
cp ../images/PokeFace/face_147.png ./out/Assets/XD/face_147.png
cp ../images/PokeBody/body_136.png ./out/Assets/XD/body_136.png
cp ../images/PokeFace/face_223.png ./out/Assets/XD/face_223.png
cp ../images/PokeFace/face_027.png ./out/Assets/XD/face_027.png
cp ../images/PokeBody/body_292.png ./out/Assets/XD/body_292.png
cp ../images/PokeBody/body_401.png ./out/Assets/XD/body_401.png
cp ../images/PokeBody/body_179.png ./out/Assets/XD/body_179.png
cp ../images/PokeFace/face_105.png ./out/Assets/XD/face_105.png
cp ../images/PokeFace/face_110.png ./out/Assets/XD/face_110.png
cp ../images/PokeFace/face_030.png ./out/Assets/XD/face_030.png
cp ../images/PokeBody/body_150.png ./out/Assets/XD/body_150.png
cp ../images/PokeBody/body_307.png ./out/Assets/XD/body_307.png
cp ../images/PokeBody/body_243.png ./out/Assets/XD/body_243.png
cp ../images/PokeFace/face_373.png ./out/Assets/XD/face_373.png
cp ../images/PokeFace/face_008.png ./out/Assets/XD/face_008.png
cp ../images/PokeBody/body_004.png ./out/Assets/XD/body_004.png
cp ../images/PokeFace/face_179.png ./out/Assets/XD/face_179.png
cp ../images/PokeBody/body_201.png ./out/Assets/XD/body_201.png
cp ../images/PokeFace/face_402.png ./out/Assets/XD/face_402.png
cp ../images/PokeFace/face_170.png ./out/Assets/XD/face_170.png
cp ../images/PokeFace/face_235.png ./out/Assets/XD/face_235.png
cp ../images/PokeFace/face_057.png ./out/Assets/XD/face_057.png
cp ../images/PokeFace/face_136.png ./out/Assets/XD/face_136.png
cp ../images/PokeBody/body_385.png ./out/Assets/XD/body_385.png
cp ../images/PokeFace/face_300.png ./out/Assets/XD/face_300.png
cp ../images/PokeFace/face_198.png ./out/Assets/XD/face_198.png
cp ../images/PokeBody/body_143.png ./out/Assets/XD/body_143.png
cp ../images/PokeBody/body_017.png ./out/Assets/XD/body_017.png
cp ../images/PokeBody/body_124.png ./out/Assets/XD/body_124.png
cp ../images/PokeFace/face_382.png ./out/Assets/XD/face_382.png
cp ../images/PokeFace/face_062.png ./out/Assets/XD/face_062.png
cp ../images/PokeFace/face_297.png ./out/Assets/XD/face_297.png
cp ../images/PokeFace/face_050.png ./out/Assets/XD/face_050.png
cp ../images/PokeFace/face_348.png ./out/Assets/XD/face_348.png
cp ../images/PokeBody/body_205.png ./out/Assets/XD/body_205.png
cp ../images/PokeFace/face_016.png ./out/Assets/XD/face_016.png
cp ../images/PokeFace/face_388.png ./out/Assets/XD/face_388.png
cp ../images/PokeFace/face_324.png ./out/Assets/XD/face_324.png
cp ../images/Trainers/trainer_19.png ./out/Assets/XD/trainer_19.png
cp ../images/PokeFace/face_233.png ./out/Assets/XD/face_233.png
cp ../images/PokeFace/face_022.png ./out/Assets/XD/face_022.png
cp ../images/PokeBody/body_353.png ./out/Assets/XD/body_353.png
cp ../images/PokeFace/face_133.png ./out/Assets/XD/face_133.png
cp ../images/PokeFace/face_288.png ./out/Assets/XD/face_288.png
cp ../images/PokeFace/face_370.png ./out/Assets/XD/face_370.png
cp ../images/PokeFace/face_156.png ./out/Assets/XD/face_156.png
cp ../images/PokeBody/body_311.png ./out/Assets/XD/body_311.png
cp ../JSON/XD/Room\ IDs.json ./out/Assets/XD/Room\ IDs.json
cp ../images/PokeBody/body_182.png ./out/Assets/XD/body_182.png
cp ../images/PokeFace/face_191.png ./out/Assets/XD/face_191.png
cp ../images/PokeBody/body_224.png ./out/Assets/XD/body_224.png
cp ../images/PokeBody/body_341.png ./out/Assets/XD/body_341.png
cp ../images/PokeBody/body_072.png ./out/Assets/XD/body_072.png
cp ../images/PokeBody/body_371.png ./out/Assets/XD/body_371.png
cp ../images/PokeBody/body_260.png ./out/Assets/XD/body_260.png
cp ../images/PokeFace/face_018.png ./out/Assets/XD/face_018.png
cp ../images/PokeBody/body_142.png ./out/Assets/XD/body_142.png
cp ../images/PokeBody/body_146.png ./out/Assets/XD/body_146.png
cp ../images/PokeFace/face_056.png ./out/Assets/XD/face_056.png
cp ../images/PokeBody/body_125.png ./out/Assets/XD/body_125.png
cp ../images/PokeFace/face_101.png ./out/Assets/XD/face_101.png
cp ../images/Trainers/trainer_54.png ./out/Assets/XD/trainer_54.png
cp ../images/PokeFace/face_121.png ./out/Assets/XD/face_121.png
cp ../images/PokeBody/body_062.png ./out/Assets/XD/body_062.png
cp ../images/PokeBody/body_275.png ./out/Assets/XD/body_275.png
cp ../images/Trainers/trainer_22.png ./out/Assets/XD/trainer_22.png
cp ../images/PokeFace/face_225.png ./out/Assets/XD/face_225.png
cp ../images/PokeFace/face_172.png ./out/Assets/XD/face_172.png
cp ../images/PokeFace/face_337.png ./out/Assets/XD/face_337.png
cp ../images/PokeFace/face_116.png ./out/Assets/XD/face_116.png
cp ../images/PokeFace/face_368.png ./out/Assets/XD/face_368.png
cp ../images/PokeFace/face_023.png ./out/Assets/XD/face_023.png
cp ../images/PokeBody/body_080.png ./out/Assets/XD/body_080.png
cp ../images/PokeFace/face_063.png ./out/Assets/XD/face_063.png
cp ../images/PokeBody/body_156.png ./out/Assets/XD/body_156.png
cp ../images/PokeFace/face_309.png ./out/Assets/XD/face_309.png
cp ../images/PokeBody/body_040.png ./out/Assets/XD/body_040.png
cp ../images/PokeBody/body_281.png ./out/Assets/XD/body_281.png
cp ../images/PokeFace/face_291.png ./out/Assets/XD/face_291.png
cp ../images/PokeBody/body_107.png ./out/Assets/XD/body_107.png
cp ../images/PokeFace/face_390.png ./out/Assets/XD/face_390.png
cp ../images/PokeBody/body_012.png ./out/Assets/XD/body_012.png
cp ../images/PokeBody/body_202.png ./out/Assets/XD/body_202.png
cp ../Sublime/SCD.sublime-syntax ./out/Assets/XD/SCD.sublime-syntax
cp ../images/PokeBody/body_305.png ./out/Assets/XD/body_305.png
cp ../images/PokeBody/body_163.png ./out/Assets/XD/body_163.png
cp ../images/PokeBody/body_289.png ./out/Assets/XD/body_289.png
cp ../images/PokeBody/body_251.png ./out/Assets/XD/body_251.png
cp ../images/PokeBody/body_402.png ./out/Assets/XD/body_402.png
cp ../images/PokeFace/face_042.png ./out/Assets/XD/face_042.png
cp ../images/PokeBody/body_051.png ./out/Assets/XD/body_051.png
cp ../images/Trainers/trainer_17.png ./out/Assets/XD/trainer_17.png
cp ../images/PokeFace/face_322.png ./out/Assets/XD/face_322.png
cp ../images/PokeFace/face_269.png ./out/Assets/XD/face_269.png
cp ../images/Trainers/trainer_45.png ./out/Assets/XD/trainer_45.png
cp ../images/PokeBody/body_340.png ./out/Assets/XD/body_340.png
cp ../images/PokeFace/face_396.png ./out/Assets/XD/face_396.png
cp ../images/PokeFace/face_036.png ./out/Assets/XD/face_036.png
cp ../images/PokeBody/body_301.png ./out/Assets/XD/body_301.png
cp ../images/PokeBody/body_335.png ./out/Assets/XD/body_335.png
cp ../images/PokeFace/face_075.png ./out/Assets/XD/face_075.png
cp ../images/PokeFace/face_314.png ./out/Assets/XD/face_314.png
cp ../images/PokeBody/body_097.png ./out/Assets/XD/body_097.png
cp ../images/PokeBody/body_400.png ./out/Assets/XD/body_400.png
cp ../images/PokeFace/face_188.png ./out/Assets/XD/face_188.png
cp ../images/PokeBody/body_235.png ./out/Assets/XD/body_235.png
cp ../images/PokeFace/face_122.png ./out/Assets/XD/face_122.png
cp ../images/Types/type_1.png ./out/Assets/XD/type_1.png
cp ../JSON/XD/Original\ Moves.json ./out/Assets/XD/Original\ Moves.json
cp ../images/PokeBody/body_006.png ./out/Assets/XD/body_006.png
cp ../images/PokeFace/face_255.png ./out/Assets/XD/face_255.png
cp ../images/Table\ View\ Cells/Selected\ Cell.png ./out/Assets/XD/Selected\ Cell.png
cp ../images/PokeFace/face_095.png ./out/Assets/XD/face_095.png
cp ../images/PokeFace/face_256.png ./out/Assets/XD/face_256.png
cp ../images/PokeFace/face_175.png ./out/Assets/XD/face_175.png
cp ../images/PokeBody/body_086.png ./out/Assets/XD/body_086.png
cp ../images/PokeBody/body_343.png ./out/Assets/XD/body_343.png
cp ../images/PokeFace/face_091.png ./out/Assets/XD/face_091.png
cp ../images/PokeFace/face_338.png ./out/Assets/XD/face_338.png
cp ../images/PokeFace/face_111.png ./out/Assets/XD/face_111.png
cp ../images/PokeBody/body_211.png ./out/Assets/XD/body_211.png
cp ../images/PokeFace/face_279.png ./out/Assets/XD/face_279.png
cp ../images/PokeFace/face_187.png ./out/Assets/XD/face_187.png
cp ../images/PokeFace/face_278.png ./out/Assets/XD/face_278.png
cp ../images/PokeBody/body_270.png ./out/Assets/XD/body_270.png
cp ../images/PokeFace/face_058.png ./out/Assets/XD/face_058.png
cp ../images/PokeBody/body_016.png ./out/Assets/XD/body_016.png
cp ../images/PokeBody/body_355.png ./out/Assets/XD/body_355.png
cp ../images/PokeBody/body_395.png ./out/Assets/XD/body_395.png
cp ../images/PokeBody/body_138.png ./out/Assets/XD/body_138.png
cp ../images/PokeFace/face_241.png ./out/Assets/XD/face_241.png
cp ../images/PokeBody/body_035.png ./out/Assets/XD/body_035.png
cp ../images/PokeBody/body_183.png ./out/Assets/XD/body_183.png
cp ../images/PokeFace/face_405.png ./out/Assets/XD/face_405.png
cp ../images/PokeFace/face_244.png ./out/Assets/XD/face_244.png
cp ../Sublime/XDScript.sublime-syntax ./out/Assets/XD/XDScript.sublime-syntax
cp ../images/PokeBody/body_014.png ./out/Assets/XD/body_014.png
cp ../images/PokeFace/face_393.png ./out/Assets/XD/face_393.png
cp ../images/PokeBody/body_167.png ./out/Assets/XD/body_167.png
cp ../images/PokeBody/body_126.png ./out/Assets/XD/body_126.png
cp ../images/PokeFace/face_167.png ./out/Assets/XD/face_167.png
cp ../images/PokeBody/body_242.png ./out/Assets/XD/body_242.png
cp ../images/Trainers/trainer_47.png ./out/Assets/XD/trainer_47.png
cp ../images/PokeFace/face_046.png ./out/Assets/XD/face_046.png
cp ../images/PokeFace/face_347.png ./out/Assets/XD/face_347.png
cp ../images/PokeFace/face_026.png ./out/Assets/XD/face_026.png
cp ../images/PokeBody/body_245.png ./out/Assets/XD/body_245.png
cp ../JSON/XD/Items.json ./out/Assets/XD/Items.json
cp ../images/PokeFace/face_220.png ./out/Assets/XD/face_220.png
cp ../images/PokeFace/face_265.png ./out/Assets/XD/face_265.png
cp ../images/PokeBody/body_029.png ./out/Assets/XD/body_029.png
cp ../images/PokeBody/body_314.png ./out/Assets/XD/body_314.png
cp ../images/PokeBody/body_252.png ./out/Assets/XD/body_252.png
cp ../images/PokeFace/face_034.png ./out/Assets/XD/face_034.png
cp ../images/PokeFace/face_408.png ./out/Assets/XD/face_408.png
cp ../images/PokeBody/body_089.png ./out/Assets/XD/body_089.png
cp ../images/PokeFace/face_161.png ./out/Assets/XD/face_161.png
cp ../images/PokeFace/face_134.png ./out/Assets/XD/face_134.png
cp ../images/PokeBody/body_132.png ./out/Assets/XD/body_132.png
cp ../images/PokeFace/face_143.png ./out/Assets/XD/face_143.png
cp ../images/PokeBody/body_407.png ./out/Assets/XD/body_407.png
cp ../tools/OSX/wiimm/* ./out/Assets/XD/wiimm
cp ../tools/OSX/other/* ./out/Assets/XD
echo "Compiling GoD Tool. This may take a while..."
swiftc -emit-executable -DENV_OSX -o ./out/GoD\ Tool\ CLI ../extensions/OSXExtensions.swift ../Objects/textures/GoDTextureImporter.swift ../enums/XGEvolutionMethods.swift ../Objects/data\ types/enumerable/XGTrainerClass.swift ../Objects/scripts/XD/XDSFlags.swift ../Objects/textures/XGTextureBlock.swift ../enums/XDSMacroTypes.swift ../Objects/textures/XGColour.swift ../GoDToolOSX/Objects/GoDKeyCodes.swift ../extensions/GoDToolCLExtensions.swift ../Objects/data\ types/XGBattleBingoPokemon.swift ../Objects/file\ formats/GoDTexturesContaining.swift ../enums/XGNatures.swift ../Objects/textures/XGPNGBlock.swift ../enums/XGStatusEffects.swift ../Objects/managers/GoDShellManager.swift ../enums/XGContestCategories.swift ../Objects/helper\ data\ types/XGStack.swift ../enums/XGBattleBingoPanel.swift ../Objects/scripts/XD/XGScriptOps.swift ../enums/XGResources.swift ../Objects/data\ types/enumerable/XGRoom.swift ../Objects/data\ types/enumerable/XGBattleCD.swift ../Objects/textures/GoDTexture.swift ../Objects/data\ types/enumerable/XGDoor.swift ../Objects/file\ formats/XGLZSS.swift ../enums/XGTrainerModels.swift ../extensions/XGExtensions.swift ../enums/GoDTextureFormats.swift ../enums/XGExpRate.swift ../Objects/data\ types/enumerable/XGPokeSpotPokemon.swift ../Objects/file\ formats/XGAssemblyCode.swift ../extensions/XGOSXExtensions.swift ../enums/XGDecks.swift ../enums/XGBagSlots.swift ../enums/XGItems.swift ../Objects/data\ types/enumerable/XGInteractionPoint.swift ../Objects/scripts/XD/XDSExpr.swift ../Objects/textures/XGTexturePalette.swift ../enums/XGSpecialStringCharacters.swift ../Objects/managers/XGRandomiser.swift ../Objects/managers/XGDolPatcher.swift ../Objects/file\ formats/XGAssemblyCodeExtensions.swift ../enums/XGGenders.swift ../enums/XGColosseumRounds.swift ../Objects/data\ types/enumerable/XGBattleBingoCard.swift ../Objects/file\ formats/XGStringTable.swift ../Objects/managers/XGGiftPokemonManager.swift ../enums/XGMaps.swift ../enums/XGShinyValues.swift ../enums/XGMoveTargets.swift ../Objects/file\ formats/XGCollisionData.swift ../protocols/EnumerableDocumentable.swift ../Objects/managers/XGStringManager.swift ../Objects/data\ types/enumerable/XGDemoStarterPokemon.swift ../Objects/data\ types/enumerable/XGTreasure.swift ../Objects/data\ types/XGCharacter.swift ../Objects/data\ types/enumerable/XGMtBattlePokemon.swift ../enums/XGTrainerContoller.swift ../Objects/scripts/XD/XDSConstant.swift ../Objects/managers/DummyThreadManager.swift ../Objects/scripts/XD/XGScript.swift ../Objects/data\ types/XGString.swift ../Objects/managers/XGSettings.swift ../enums/XGGenderRatios.swift ../Objects/data\ types/enumerable/XGStoryProgress.swift ../Objects/data\ types/enumerable/XGType.swift ../enums/XGDeckPokemon.swift ../Objects/data\ types/enumerable/XGTradePokemon.swift ../XDRelIndexes.swift ../enums/XGMoveEffectTypes.swift ../enums/XGMoves.swift ../extensions/GoDImageExtensions.swift ../Objects/file\ formats/XGGSWTextures.swift ../Objects/data\ types/enumerable/XGTradeShadowPokemon.swift ../Objects/data\ types/enumerable/XGMove.swift ../Objects/data\ types/XGLevelUpMove.swift ../enums/XGFontColours.swift ../Objects/file\ formats/XGISO.swift ../Objects/textures/XGImage.swift ../enums/XGDeoxysFormes.swift ../Objects/data\ types/enumerable/XGNature.swift ../Objects/scripts/XD/XGScriptClassFunctionsData.swift ../Objects/data\ types/enumerable/XGPokemart.swift ../Objects/data\ types/enumerable/XGMusic.swift ../Objects/helper\ data\ types/XGMutableData.swift ../enums/XGASM.swift ../Objects/textures/XGTextureMetaData.swift ../enums/XGFileTypes.swift ../enums/XGFiles.swift ../Objects/data\ types/enumerable/XGCharacterModel.swift ../enums/XGWeather.swift ../Objects/data\ types/enumerable/XGBattleField.swift ../enums/XGUnicodeCharacters.swift ../enums/XGEffectivenessValues.swift ../extensions/XDExtensions.swift ../enums/XGPokemon.swift ../Objects/managers/XGUtility.swift ../enums/XGEvolutionConditionType.swift ../enums/XGBattleTypes.swift ../Objects/data\ types/enumerable/XGTrainerPokemon.swift ../Objects/data\ types/enumerable/XGStarterPokemon.swift ../Objects/data\ types/enumerable/XGPokemonStats.swift ../extensions/XDSExtensions.swift ../enums/XGAbilities.swift ../Objects/file\ formats/XGRelocationTable.swift ../Objects/data\ types/enumerable/XGGiftPokemon.swift ../GoD-CLI/main.swift ../enums/XGMoveTypes.swift ../Objects/data\ types/XGEvolution.swift ../Objects/scripts/XD/XGScriptInstruction.swift ../Objects/data\ types/enumerable/CMGiftPokemon.swift ../Objects/file\ formats/XGFsys.swift ../enums/XGBattleStyles.swift ../Objects/scripts/XD/XGScriptClass.swift ../extensions/GoDOSXExtensions.swift ../GoDToolOSX/Objects/XGVertex.swift ../Objects/data\ types/enumerable/XGBattle.swift ../Objects/scripts/XD/XDSScriptCompiler.swift ../Objects/data\ types/enumerable/XGItem.swift ../enums/XGPokeSpots.swift ../enums/XGTMs.swift ../enums/XGMoveCategory.swift ../Objects/data\ types/enumerable/XGTrainer.swift ../enums/XGStatBoosts.swift ../enums/XGTrainerClasses.swift