setlocal enableextensions

rmdir /s /q spm\virt\GoD-CLI\Sources
md spm\virt\GoD-CLI\Sources

rmdir /s /q spm\virt\Colosseum-CLI\Sources
md spm\virt\Colosseum-CLI\Sources

rmdir /s /q spm\virt\PBR-CLI\Sources
md spm\virt\PBR-CLI\Sources

endlocal

mklink spm\virt\GoD-CLI\Sources\WindowsExtensions.swift "%cd%\extensions\WindowsExtensions.swift"
mklink spm\virt\Colosseum-CLI\Sources\WindowsExtensions.swift "%cd%\extensions\WindowsExtensions.swift"
mklink spm\virt\PBR-CLI\Sources\WindowsExtensions.swift "%cd%\extensions\WindowsExtensions.swift"

mklink "spm\virt\GoD-CLI\Sources\GoDTextureImporter.swift" "%cd%\Objects\textures\GoDTextureImporter.swift"
mklink "spm\virt\GoD-CLI\Sources\XGEvolutionMethods.swift" "%cd%\enums\XGEvolutionMethods.swift"
mklink "spm\virt\GoD-CLI\Sources\XGTrainerClass.swift" "%cd%\Objects\data types\enumerable\XGTrainerClass.swift"
mklink "spm\virt\GoD-CLI\Sources\XDSFlags.swift" "%cd%\Objects\scripts\XD\XDSFlags.swift"
mklink "spm\virt\GoD-CLI\Sources\XGTextureBlock.swift" "%cd%\Objects\textures\XGTextureBlock.swift"
mklink "spm\virt\GoD-CLI\Sources\XDSMacroTypes.swift" "%cd%\enums\XDSMacroTypes.swift"
mklink "spm\virt\GoD-CLI\Sources\XGColour.swift" "%cd%\Objects\textures\XGColour.swift"
mklink "spm\virt\GoD-CLI\Sources\GoDKeyCodes.swift" "%cd%\GoDToolOSX\Objects\GoDKeyCodes.swift"
mklink "spm\virt\GoD-CLI\Sources\GoDToolCLExtensions.swift" "%cd%\extensions\GoDToolCLExtensions.swift"
mklink "spm\virt\GoD-CLI\Sources\XGBattleBingoPokemon.swift" "%cd%\Objects\data types\XGBattleBingoPokemon.swift"
mklink "spm\virt\GoD-CLI\Sources\GoDTexturesContaining.swift" "%cd%\Objects\file formats\GoDTexturesContaining.swift"
mklink "spm\virt\GoD-CLI\Sources\XGNatures.swift" "%cd%\enums\XGNatures.swift"
mklink "spm\virt\GoD-CLI\Sources\XGPNGBlock.swift" "%cd%\Objects\textures\XGPNGBlock.swift"
mklink "spm\virt\GoD-CLI\Sources\XGStatusEffects.swift" "%cd%\enums\XGStatusEffects.swift"
mklink "spm\virt\GoD-CLI\Sources\GoDShellManager.swift" "%cd%\Objects\managers\GoDShellManager.swift"
mklink "spm\virt\GoD-CLI\Sources\XGContestCategories.swift" "%cd%\enums\XGContestCategories.swift"
mklink "spm\virt\GoD-CLI\Sources\XGStack.swift" "%cd%\Objects\helper data types\XGStack.swift"
mklink "spm\virt\GoD-CLI\Sources\XGBattleBingoPanel.swift" "%cd%\enums\XGBattleBingoPanel.swift"
mklink "spm\virt\GoD-CLI\Sources\XGScriptOps.swift" "%cd%\Objects\scripts\XD\XGScriptOps.swift"
mklink "spm\virt\GoD-CLI\Sources\XGResources.swift" "%cd%\enums\XGResources.swift"
mklink "spm\virt\GoD-CLI\Sources\XGRoom.swift" "%cd%\Objects\data types\enumerable\XGRoom.swift"
mklink "spm\virt\GoD-CLI\Sources\XGBattleCD.swift" "%cd%\Objects\data types\enumerable\XGBattleCD.swift"
mklink "spm\virt\GoD-CLI\Sources\GoDTexture.swift" "%cd%\Objects\textures\GoDTexture.swift"
mklink "spm\virt\GoD-CLI\Sources\XGDoor.swift" "%cd%\Objects\data types\enumerable\XGDoor.swift"
mklink "spm\virt\GoD-CLI\Sources\XGLZSS.swift" "%cd%\Objects\file formats\XGLZSS.swift"
mklink "spm\virt\GoD-CLI\Sources\XGTrainerModels.swift" "%cd%\enums\XGTrainerModels.swift"
mklink "spm\virt\GoD-CLI\Sources\XGTHP.swift" "%cd%\Objects\file formats\XGTHP.swift"
mklink "spm\virt\GoD-CLI\Sources\XGExtensions.swift" "%cd%\extensions\XGExtensions.swift"
mklink "spm\virt\GoD-CLI\Sources\GoDTextureFormats.swift" "%cd%\enums\GoDTextureFormats.swift"
mklink "spm\virt\GoD-CLI\Sources\XGExpRate.swift" "%cd%\enums\XGExpRate.swift"
mklink "spm\virt\GoD-CLI\Sources\XGPokeSpotPokemon.swift" "%cd%\Objects\data types\enumerable\XGPokeSpotPokemon.swift"
mklink "spm\virt\GoD-CLI\Sources\XGAssemblyCode.swift" "%cd%\Objects\file formats\XGAssemblyCode.swift"
mklink "spm\virt\GoD-CLI\Sources\XGOSXExtensions.swift" "%cd%\extensions\XGOSXExtensions.swift"
mklink "spm\virt\GoD-CLI\Sources\XGDecks.swift" "%cd%\enums\XGDecks.swift"
mklink "spm\virt\GoD-CLI\Sources\XGBagSlots.swift" "%cd%\enums\XGBagSlots.swift"
mklink "spm\virt\GoD-CLI\Sources\XGItems.swift" "%cd%\enums\XGItems.swift"
mklink "spm\virt\GoD-CLI\Sources\XGInteractionPoint.swift" "%cd%\Objects\data types\enumerable\XGInteractionPoint.swift"
mklink "spm\virt\GoD-CLI\Sources\XDSExpr.swift" "%cd%\Objects\scripts\XD\XDSExpr.swift"
mklink "spm\virt\GoD-CLI\Sources\XGTexturePalette.swift" "%cd%\Objects\textures\XGTexturePalette.swift"
mklink "spm\virt\GoD-CLI\Sources\XGSpecialStringCharacters.swift" "%cd%\enums\XGSpecialStringCharacters.swift"
mklink "spm\virt\GoD-CLI\Sources\XGRandomiser.swift" "%cd%\Objects\managers\XGRandomiser.swift"
mklink "spm\virt\GoD-CLI\Sources\XGDolPatcher.swift" "%cd%\Objects\managers\XGDolPatcher.swift"
mklink "spm\virt\GoD-CLI\Sources\XGAssemblyCodeExtensions.swift" "%cd%\Objects\file formats\XGAssemblyCodeExtensions.swift"
mklink "spm\virt\GoD-CLI\Sources\XGGenders.swift" "%cd%\enums\XGGenders.swift"
mklink "spm\virt\GoD-CLI\Sources\XGColosseumRounds.swift" "%cd%\enums\XGColosseumRounds.swift"
mklink "spm\virt\GoD-CLI\Sources\XGBattleBingoCard.swift" "%cd%\Objects\data types\enumerable\XGBattleBingoCard.swift"
mklink "spm\virt\GoD-CLI\Sources\XGStringTable.swift" "%cd%\Objects\file formats\XGStringTable.swift"
mklink "spm\virt\GoD-CLI\Sources\XGGiftPokemonManager.swift" "%cd%\Objects\managers\XGGiftPokemonManager.swift"
mklink "spm\virt\GoD-CLI\Sources\XGMaps.swift" "%cd%\enums\XGMaps.swift"
mklink "spm\virt\GoD-CLI\Sources\XGShinyValues.swift" "%cd%\enums\XGShinyValues.swift"
mklink "spm\virt\GoD-CLI\Sources\XGMoveTargets.swift" "%cd%\enums\XGMoveTargets.swift"
mklink "spm\virt\GoD-CLI\Sources\XGCollisionData.swift" "%cd%\Objects\file formats\XGCollisionData.swift"
mklink "spm\virt\GoD-CLI\Sources\EnumerableDocumentable.swift" "%cd%\protocols\EnumerableDocumentable.swift"
mklink "spm\virt\GoD-CLI\Sources\XGStringManager.swift" "%cd%\Objects\managers\XGStringManager.swift"
mklink "spm\virt\GoD-CLI\Sources\XGDemoStarterPokemon.swift" "%cd%\Objects\data types\enumerable\XGDemoStarterPokemon.swift"
mklink "spm\virt\GoD-CLI\Sources\XGTreasure.swift" "%cd%\Objects\data types\enumerable\XGTreasure.swift"
mklink "spm\virt\GoD-CLI\Sources\XGCharacter.swift" "%cd%\Objects\data types\XGCharacter.swift"
mklink "spm\virt\GoD-CLI\Sources\XGMtBattlePokemon.swift" "%cd%\Objects\data types\enumerable\XGMtBattlePokemon.swift"
mklink "spm\virt\GoD-CLI\Sources\XGTrainerContoller.swift" "%cd%\enums\XGTrainerContoller.swift"
mklink "spm\virt\GoD-CLI\Sources\XDSConstant.swift" "%cd%\Objects\scripts\XD\XDSConstant.swift"
mklink "spm\virt\GoD-CLI\Sources\DummyThreadManager.swift" "%cd%\Objects\managers\DummyThreadManager.swift"
mklink "spm\virt\GoD-CLI\Sources\XGScript.swift" "%cd%\Objects\scripts\XD\XGScript.swift"
mklink "spm\virt\GoD-CLI\Sources\XGString.swift" "%cd%\Objects\data types\XGString.swift"
mklink "spm\virt\GoD-CLI\Sources\XGSettings.swift" "%cd%\Objects\managers\XGSettings.swift"
mklink "spm\virt\GoD-CLI\Sources\XGGenderRatios.swift" "%cd%\enums\XGGenderRatios.swift"
mklink "spm\virt\GoD-CLI\Sources\XGStoryProgress.swift" "%cd%\Objects\data types\enumerable\XGStoryProgress.swift"
mklink "spm\virt\GoD-CLI\Sources\XGType.swift" "%cd%\Objects\data types\enumerable\XGType.swift"
mklink "spm\virt\GoD-CLI\Sources\XGDeckPokemon.swift" "%cd%\enums\XGDeckPokemon.swift"
mklink "spm\virt\GoD-CLI\Sources\XGTradePokemon.swift" "%cd%\Objects\data types\enumerable\XGTradePokemon.swift"
mklink "spm\virt\GoD-CLI\Sources\XDRelIndexes.swift" "%cd%\XDRelIndexes.swift"
mklink "spm\virt\GoD-CLI\Sources\XGMoveEffectTypes.swift" "%cd%\enums\XGMoveEffectTypes.swift"
mklink "spm\virt\GoD-CLI\Sources\XGMoves.swift" "%cd%\enums\XGMoves.swift"
mklink "spm\virt\GoD-CLI\Sources\GoDImageExtensions.swift" "%cd%\extensions\GoDImageExtensions.swift"
mklink "spm\virt\GoD-CLI\Sources\XGGSWTextures.swift" "%cd%\Objects\file formats\XGGSWTextures.swift"
mklink "spm\virt\GoD-CLI\Sources\XGTradeShadowPokemon.swift" "%cd%\Objects\data types\enumerable\XGTradeShadowPokemon.swift"
mklink "spm\virt\GoD-CLI\Sources\XGMove.swift" "%cd%\Objects\data types\enumerable\XGMove.swift"
mklink "spm\virt\GoD-CLI\Sources\XGLevelUpMove.swift" "%cd%\Objects\data types\XGLevelUpMove.swift"
mklink "spm\virt\GoD-CLI\Sources\XGFontColours.swift" "%cd%\enums\XGFontColours.swift"
mklink "spm\virt\GoD-CLI\Sources\XGISO.swift" "%cd%\Objects\file formats\XGISO.swift"
mklink "spm\virt\GoD-CLI\Sources\XGImage.swift" "%cd%\Objects\textures\XGImage.swift"
mklink "spm\virt\GoD-CLI\Sources\XGDeoxysFormes.swift" "%cd%\enums\XGDeoxysFormes.swift"
mklink "spm\virt\GoD-CLI\Sources\XGNature.swift" "%cd%\Objects\data types\enumerable\XGNature.swift"
mklink "spm\virt\GoD-CLI\Sources\XGScriptClassFunctionsData.swift" "%cd%\Objects\scripts\XD\XGScriptClassFunctionsData.swift"
mklink "spm\virt\GoD-CLI\Sources\XGPokemart.swift" "%cd%\Objects\data types\enumerable\XGPokemart.swift"
mklink "spm\virt\GoD-CLI\Sources\XGMusic.swift" "%cd%\Objects\data types\enumerable\XGMusic.swift"
mklink "spm\virt\GoD-CLI\Sources\XGMutableData.swift" "%cd%\Objects\helper data types\XGMutableData.swift"
mklink "spm\virt\GoD-CLI\Sources\XGASM.swift" "%cd%\enums\XGASM.swift"
mklink "spm\virt\GoD-CLI\Sources\XGTextureMetaData.swift" "%cd%\Objects\textures\XGTextureMetaData.swift"
mklink "spm\virt\GoD-CLI\Sources\XGFileTypes.swift" "%cd%\enums\XGFileTypes.swift"
mklink "spm\virt\GoD-CLI\Sources\XGFiles.swift" "%cd%\enums\XGFiles.swift"
mklink "spm\virt\GoD-CLI\Sources\XGCharacterModel.swift" "%cd%\Objects\data types\enumerable\XGCharacterModel.swift"
mklink "spm\virt\GoD-CLI\Sources\XGWeather.swift" "%cd%\enums\XGWeather.swift"
mklink "spm\virt\GoD-CLI\Sources\XGBattleField.swift" "%cd%\Objects\data types\enumerable\XGBattleField.swift"
mklink "spm\virt\GoD-CLI\Sources\XGUnicodeCharacters.swift" "%cd%\enums\XGUnicodeCharacters.swift"
mklink "spm\virt\GoD-CLI\Sources\XGEffectivenessValues.swift" "%cd%\enums\XGEffectivenessValues.swift"
mklink "spm\virt\GoD-CLI\Sources\XDExtensions.swift" "%cd%\extensions\XDExtensions.swift"
mklink "spm\virt\GoD-CLI\Sources\XGPokemon.swift" "%cd%\enums\XGPokemon.swift"
mklink "spm\virt\GoD-CLI\Sources\XGUtility.swift" "%cd%\Objects\managers\XGUtility.swift"
mklink "spm\virt\GoD-CLI\Sources\XGEvolutionConditionType.swift" "%cd%\enums\XGEvolutionConditionType.swift"
mklink "spm\virt\GoD-CLI\Sources\XGBattleTypes.swift" "%cd%\enums\XGBattleTypes.swift"
mklink "spm\virt\GoD-CLI\Sources\XGTrainerPokemon.swift" "%cd%\Objects\data types\enumerable\XGTrainerPokemon.swift"
mklink "spm\virt\GoD-CLI\Sources\XGStarterPokemon.swift" "%cd%\Objects\data types\enumerable\XGStarterPokemon.swift"
mklink "spm\virt\GoD-CLI\Sources\XGPokemonStats.swift" "%cd%\Objects\data types\enumerable\XGPokemonStats.swift"
mklink "spm\virt\GoD-CLI\Sources\XDSExtensions.swift" "%cd%\extensions\XDSExtensions.swift"
mklink "spm\virt\GoD-CLI\Sources\XGAbilities.swift" "%cd%\enums\XGAbilities.swift"
mklink "spm\virt\GoD-CLI\Sources\XGRelocationTable.swift" "%cd%\Objects\file formats\XGRelocationTable.swift"
mklink "spm\virt\GoD-CLI\Sources\XGGiftPokemon.swift" "%cd%\Objects\data types\enumerable\XGGiftPokemon.swift"
mklink "spm\virt\GoD-CLI\Sources\main.swift" "%cd%\GoD-CLI\main.swift"
mklink "spm\virt\GoD-CLI\Sources\XGMoveTypes.swift" "%cd%\enums\XGMoveTypes.swift"
mklink "spm\virt\GoD-CLI\Sources\XGEvolution.swift" "%cd%\Objects\data types\XGEvolution.swift"
mklink "spm\virt\GoD-CLI\Sources\XGScriptInstruction.swift" "%cd%\Objects\scripts\XD\XGScriptInstruction.swift"
mklink "spm\virt\GoD-CLI\Sources\CMGiftPokemon.swift" "%cd%\Objects\data types\enumerable\CMGiftPokemon.swift"
mklink "spm\virt\GoD-CLI\Sources\XGFsys.swift" "%cd%\Objects\file formats\XGFsys.swift"
mklink "spm\virt\GoD-CLI\Sources\XGBattleStyles.swift" "%cd%\enums\XGBattleStyles.swift"
mklink "spm\virt\GoD-CLI\Sources\XGScriptClass.swift" "%cd%\Objects\scripts\XD\XGScriptClass.swift"
mklink "spm\virt\GoD-CLI\Sources\GoDOSXExtensions.swift" "%cd%\extensions\GoDOSXExtensions.swift"
mklink "spm\virt\GoD-CLI\Sources\XGVertex.swift" "%cd%\GoDToolOSX\Objects\XGVertex.swift"
mklink "spm\virt\GoD-CLI\Sources\XGBattle.swift" "%cd%\Objects\data types\enumerable\XGBattle.swift"
mklink "spm\virt\GoD-CLI\Sources\XDSScriptCompiler.swift" "%cd%\Objects\scripts\XD\XDSScriptCompiler.swift"
mklink "spm\virt\GoD-CLI\Sources\XGItem.swift" "%cd%\Objects\data types\enumerable\XGItem.swift"
mklink "spm\virt\GoD-CLI\Sources\XGPokeSpots.swift" "%cd%\enums\XGPokeSpots.swift"
mklink "spm\virt\GoD-CLI\Sources\XGTMs.swift" "%cd%\enums\XGTMs.swift"
mklink "spm\virt\GoD-CLI\Sources\XGMoveCategory.swift" "%cd%\enums\XGMoveCategory.swift"
mklink "spm\virt\GoD-CLI\Sources\XGTrainer.swift" "%cd%\Objects\data types\enumerable\XGTrainer.swift"
mklink "spm\virt\GoD-CLI\Sources\XGStatBoosts.swift" "%cd%\enums\XGStatBoosts.swift"
mklink "spm\virt\GoD-CLI\Sources\XGTrainerClasses.swift" "%cd%\enums\XGTrainerClasses.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGEvolution.swift" "%cd%\Objects\data types\XGEvolution.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGMoveTargets.swift" "%cd%\enums\XGMoveTargets.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGEvolutionConditionType.swift" "%cd%\enums\XGEvolutionConditionType.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGEffectivenessValues.swift" "%cd%\enums\XGEffectivenessValues.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGBagSlots.swift" "%cd%\enums\XGBagSlots.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGMoveCategory.swift" "%cd%\enums\XGMoveCategory.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGTHP.swift" "%cd%\Objects\file formats\XGTHP.swift"
mklink "spm\virt\Colosseum-CLI\Sources\GoDTexture.swift" "%cd%\Objects\textures\GoDTexture.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGAbilities.swift" "%cd%\enums\XGAbilities.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGLevelUpMove.swift" "%cd%\Objects\data types\XGLevelUpMove.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGUnicodeCharacters.swift" "%cd%\enums\XGUnicodeCharacters.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGSaveManager.swift" "%cd%\Objects\managers\XGSaveManager.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMScriptStandardFunctions.swift" "%cd%\Objects\scripts\Colosseum\CMScriptStandardFunctions.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMFiles.swift" "%cd%\enums\CMFiles.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGCharacter.swift" "%cd%\Objects\data types\XGCharacter.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGResources.swift" "%cd%\enums\XGResources.swift"
mklink "spm\virt\Colosseum-CLI\Sources\DummyThreadManager.swift" "%cd%\Objects\managers\DummyThreadManager.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGContestCategories.swift" "%cd%\enums\XGContestCategories.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMScript.swift" "%cd%\Objects\scripts\Colosseum\CMScript.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGTexturePalette.swift" "%cd%\Objects\textures\XGTexturePalette.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMGiftPokemon.swift" "%cd%\Objects\data types\enumerable\CMGiftPokemon.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGStack.swift" "%cd%\Objects\helper data types\XGStack.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMOSXExtensions.swift" "%cd%\extensions\CMOSXExtensions.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGTreasure.swift" "%cd%\Objects\data types\enumerable\XGTreasure.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGStatusEffects.swift" "%cd%\enums\XGStatusEffects.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGStatBoosts.swift" "%cd%\enums\XGStatBoosts.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMTrainerPokemon.swift" "%cd%\Objects\data types\enumerable\CMTrainerPokemon.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGMoveTypes.swift" "%cd%\enums\XGMoveTypes.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGCollisionData.swift" "%cd%\Objects\file formats\XGCollisionData.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGStringManager.swift" "%cd%\Objects\managers\XGStringManager.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMType.swift" "%cd%\Objects\data types\enumerable\CMType.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMPokemonStats.swift" "%cd%\Objects\data types\enumerable\CMPokemonStats.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGGenderRatios.swift" "%cd%\enums\XGGenderRatios.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGTrainerClass.swift" "%cd%\Objects\data types\enumerable\XGTrainerClass.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGDolPatcher.swift" "%cd%\Objects\managers\XGDolPatcher.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGFontColours.swift" "%cd%\enums\XGFontColours.swift"
mklink "spm\virt\Colosseum-CLI\Sources\ColosseumToolCLExtensions.swift" "%cd%\extensions\ColosseumToolCLExtensions.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGBattleTypes.swift" "%cd%\enums\XGBattleTypes.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGRelocationTable.swift" "%cd%\Objects\file formats\XGRelocationTable.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGStringTable.swift" "%cd%\Objects\file formats\XGStringTable.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGMoveEffectTypes.swift" "%cd%\enums\XGMoveEffectTypes.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMScriptValueTypes.swift" "%cd%\Objects\scripts\Colosseum\CMScriptValueTypes.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMItem.swift" "%cd%\Objects\data types\enumerable\CMItem.swift"
mklink "spm\virt\Colosseum-CLI\Sources\ColosseumExtensions.swift" "%cd%\extensions\ColosseumExtensions.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGDoor.swift" "%cd%\Objects\data types\enumerable\XGDoor.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMColosseumRounds.swift" "%cd%\enums\CMColosseumRounds.swift"
mklink "spm\virt\Colosseum-CLI\Sources\GoDTextureImporter.swift" "%cd%\Objects\textures\GoDTextureImporter.swift"
mklink "spm\virt\Colosseum-CLI\Sources\GoDImageExtensions.swift" "%cd%\extensions\GoDImageExtensions.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGStarterPokemon.swift" "%cd%\Objects\data types\enumerable\XGStarterPokemon.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGLZSS.swift" "%cd%\Objects\file formats\XGLZSS.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGFsys.swift" "%cd%\Objects\file formats\XGFsys.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMBattle.swift" "%cd%\Objects\data types\enumerable\CMBattle.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGNatures.swift" "%cd%\enums\XGNatures.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGMutableData.swift" "%cd%\Objects\helper data types\XGMutableData.swift"
mklink "spm\virt\Colosseum-CLI\Sources\GoDKeyCodes.swift" "%cd%\GoDToolOSX\Objects\GoDKeyCodes.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGPNGBlock.swift" "%cd%\Objects\textures\XGPNGBlock.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGVertex.swift" "%cd%\GoDToolOSX\Objects\XGVertex.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGTrainerContoller.swift" "%cd%\enums\XGTrainerContoller.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMTrainerModels.swift" "%cd%\enums\CMTrainerModels.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMGiftPokemonManager.swift" "%cd%\Objects\managers\CMGiftPokemonManager.swift"
mklink "spm\virt\Colosseum-CLI\Sources\GoDTexturesContaining.swift" "%cd%\Objects\file formats\GoDTexturesContaining.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGTextureBlock.swift" "%cd%\Objects\textures\XGTextureBlock.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGWeather.swift" "%cd%\enums\XGWeather.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMItems.swift" "%cd%\enums\CMItems.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGMoves.swift" "%cd%\enums\XGMoves.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGNature.swift" "%cd%\Objects\data types\enumerable\XGNature.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGRoom.swift" "%cd%\Objects\data types\enumerable\XGRoom.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMTrainer.swift" "%cd%\Objects\data types\enumerable\CMTrainer.swift"
mklink "spm\virt\Colosseum-CLI\Sources\GoDOSXExtensions.swift" "%cd%\extensions\GoDOSXExtensions.swift"
mklink "spm\virt\Colosseum-CLI\Sources\GoDShellManager.swift" "%cd%\Objects\managers\GoDShellManager.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGExpRate.swift" "%cd%\enums\XGExpRate.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGISO.swift" "%cd%\Objects\file formats\XGISO.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMTMs.swift" "%cd%\enums\CMTMs.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMScriptOps.swift" "%cd%\Objects\scripts\Colosseum\CMScriptOps.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGGenders.swift" "%cd%\enums\XGGenders.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMRelIndexes.swift" "%cd%\CMRelIndexes.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGString.swift" "%cd%\Objects\data types\XGString.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMScriptCompiler.swift" "%cd%\Objects\scripts\Colosseum\CMScriptCompiler.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGPokemon.swift" "%cd%\enums\XGPokemon.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGDemoStarterPokemon.swift" "%cd%\Objects\data types\enumerable\XGDemoStarterPokemon.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGAssemblyCodeExtensions.swift" "%cd%\Objects\file formats\XGAssemblyCodeExtensions.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGShinyValues.swift" "%cd%\enums\XGShinyValues.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGGSWTextures.swift" "%cd%\Objects\file formats\XGGSWTextures.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGInteractionPoint.swift" "%cd%\Objects\data types\enumerable\XGInteractionPoint.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGFileTypes.swift" "%cd%\enums\XGFileTypes.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGBattleField.swift" "%cd%\Objects\data types\enumerable\XGBattleField.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGExtensions.swift" "%cd%\extensions\XGExtensions.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMRandomiser.swift" "%cd%\Objects\managers\CMRandomiser.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGSettings.swift" "%cd%\Objects\managers\XGSettings.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGBattleStyles.swift" "%cd%\enums\XGBattleStyles.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGEvolutionMethods.swift" "%cd%\enums\XGEvolutionMethods.swift"
mklink "spm\virt\Colosseum-CLI\Sources\main.swift" "%cd%\Colosseum-CLI\main.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGImage.swift" "%cd%\Objects\textures\XGImage.swift"
mklink "spm\virt\Colosseum-CLI\Sources\GoDTextureFormats.swift" "%cd%\enums\GoDTextureFormats.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGUtility.swift" "%cd%\Objects\managers\XGUtility.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGCharacterModel.swift" "%cd%\Objects\data types\enumerable\XGCharacterModel.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGASM.swift" "%cd%\enums\XGASM.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGDeoxysFormes.swift" "%cd%\enums\XGDeoxysFormes.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGMaps.swift" "%cd%\enums\XGMaps.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGSpecialStringCharacters.swift" "%cd%\enums\XGSpecialStringCharacters.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGColour.swift" "%cd%\Objects\textures\XGColour.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGAssemblyCode.swift" "%cd%\Objects\file formats\XGAssemblyCode.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGGiftPokemon.swift" "%cd%\Objects\data types\enumerable\XGGiftPokemon.swift"
mklink "spm\virt\Colosseum-CLI\Sources\CMTrainerClasses.swift" "%cd%\enums\CMTrainerClasses.swift"
mklink "spm\virt\Colosseum-CLI\Sources\XGMove.swift" "%cd%\Objects\data types\enumerable\XGMove.swift"
mklink "spm\virt\Colosseum-CLI\Sources\EnumerableDocumentable.swift" "%cd%\protocols\EnumerableDocumentable.swift"
mklink "spm\virt\PBR-CLI\Sources\XGResources.swift" "%cd%\enums\XGResources.swift"
mklink "spm\virt\PBR-CLI\Sources\XGFsys.swift" "%cd%\Objects\file formats\XGFsys.swift"
mklink "spm\virt\PBR-CLI\Sources\GoDKeyCodes.swift" "%cd%\GoDToolOSX\Objects\GoDKeyCodes.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRType.swift" "%cd%\Revolution Tool CL\objects\PBRType.swift"
mklink "spm\virt\PBR-CLI\Sources\XGVertex.swift" "%cd%\GoDToolOSX\Objects\XGVertex.swift"
mklink "spm\virt\PBR-CLI\Sources\GoDImageExtensions.swift" "%cd%\extensions\GoDImageExtensions.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRTMs.swift" "%cd%\Revolution Tool CL\enums\PBRTMs.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRMoveTypes.swift" "%cd%\Revolution Tool CL\enums\PBRMoveTypes.swift"
mklink "spm\virt\PBR-CLI\Sources\XGEvolution.swift" "%cd%\Objects\data types\XGEvolution.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRDataTableEntry.swift" "%cd%\Revolution Tool CL\objects\PBRDataTableEntry.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRMove.swift" "%cd%\Revolution Tool CL\objects\PBRMove.swift"
mklink "spm\virt\PBR-CLI\Sources\XGWormadamForms.swift" "%cd%\enums\XGWormadamForms.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRScriptOps.swift" "%cd%\Revolution Tool CL\enums\PBRScriptOps.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRMoveCategory.swift" "%cd%\Revolution Tool CL\enums\PBRMoveCategory.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRDecks.swift" "%cd%\Revolution Tool CL\enums\PBRDecks.swift"
mklink "spm\virt\PBR-CLI\Sources\XGNatures.swift" "%cd%\enums\XGNatures.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRFiles.swift" "%cd%\Revolution Tool CL\enums\PBRFiles.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRPokemonStats.swift" "%cd%\Revolution Tool CL\objects\PBRPokemonStats.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRUnicodeCharacters.swift" "%cd%\Revolution Tool CL\enums\PBRUnicodeCharacters.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRTrainerModels.swift" "%cd%\Revolution Tool CL\enums\PBRTrainerModels.swift"
mklink "spm\virt\PBR-CLI\Sources\XGTHP.swift" "%cd%\Objects\file formats\XGTHP.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRTypeManager.swift" "%cd%\Revolution Tool CL\objects\PBRTypeManager.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRScriptInstruction.swift" "%cd%\Revolution Tool CL\objects\PBRScriptInstruction.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRISO.swift" "%cd%\Revolution Tool CL\objects\PBRISO.swift"
mklink "spm\virt\PBR-CLI\Sources\XGGenders.swift" "%cd%\enums\XGGenders.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRPokemonSprite.swift" "%cd%\Revolution Tool CL\enums\PBRPokemonSprite.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRTrainer.swift" "%cd%\Revolution Tool CL\objects\PBRTrainer.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRContestAppeals.swift" "%cd%\Revolution Tool CL\enums\PBRContestAppeals.swift"
mklink "spm\virt\PBR-CLI\Sources\XGExtensions.swift" "%cd%\extensions\XGExtensions.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRExtensions.swift" "%cd%\extensions\PBRExtensions.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRScriptClass.swift" "%cd%\Revolution Tool CL\objects\PBRScriptClass.swift"
mklink "spm\virt\PBR-CLI\Sources\PBREffectivenessValues.swift" "%cd%\Revolution Tool CL\enums\PBREffectivenessValues.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRCLExtensions.swift" "%cd%\extensions\PBRCLExtensions.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRFileTypes.swift" "%cd%\Revolution Tool CL\enums\PBRFileTypes.swift"
mklink "spm\virt\PBR-CLI\Sources\XGString.swift" "%cd%\Objects\data types\XGString.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRAbilities.swift" "%cd%\Revolution Tool CL\enums\PBRAbilities.swift"
mklink "spm\virt\PBR-CLI\Sources\XGExpRate.swift" "%cd%\enums\XGExpRate.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRExpr.swift" "%cd%\Revolution Tool CL\enums\PBRExpr.swift"
mklink "spm\virt\PBR-CLI\Sources\XGASM.swift" "%cd%\enums\XGASM.swift"
mklink "spm\virt\PBR-CLI\Sources\XGTextureBlock.swift" "%cd%\Objects\textures\XGTextureBlock.swift"
mklink "spm\virt\PBR-CLI\Sources\GoDShellManager.swift" "%cd%\Objects\managers\GoDShellManager.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRDolPatcher.swift" "%cd%\Revolution Tool CL\objects\PBRDolPatcher.swift"
mklink "spm\virt\PBR-CLI\Sources\GoDTextureFormats.swift" "%cd%\enums\GoDTextureFormats.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRPokemon.swift" "%cd%\Revolution Tool CL\enums\PBRPokemon.swift"
mklink "spm\virt\PBR-CLI\Sources\DummyThreadManager.swift" "%cd%\Objects\managers\DummyThreadManager.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRDeckTrainer.swift" "%cd%\Revolution Tool CL\enums\PBRDeckTrainer.swift"
mklink "spm\virt\PBR-CLI\Sources\XGGSWTextures.swift" "%cd%\Objects\file formats\XGGSWTextures.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRSpecialStringCharacters.swift" "%cd%\Revolution Tool CL\enums\PBRSpecialStringCharacters.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRMoves.swift" "%cd%\Revolution Tool CL\enums\PBRMoves.swift"
mklink "spm\virt\PBR-CLI\Sources\XGShinyValues.swift" "%cd%\enums\XGShinyValues.swift"
mklink "spm\virt\PBR-CLI\Sources\XGWeather.swift" "%cd%\enums\XGWeather.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRScriptCompiler.swift" "%cd%\Revolution Tool CL\objects\PBRScriptCompiler.swift"
mklink "spm\virt\PBR-CLI\Sources\XGEvolutionConditionType.swift" "%cd%\enums\XGEvolutionConditionType.swift"
mklink "spm\virt\PBR-CLI\Sources\XGLZSS.swift" "%cd%\Objects\file formats\XGLZSS.swift"
mklink "spm\virt\PBR-CLI\Sources\PBREvolutionMethods.swift" "%cd%\Revolution Tool CL\enums\PBREvolutionMethods.swift"
mklink "spm\virt\PBR-CLI\Sources\XGBattleStyles.swift" "%cd%\enums\XGBattleStyles.swift"
mklink "spm\virt\PBR-CLI\Sources\XGLevelUpMove.swift" "%cd%\Objects\data types\XGLevelUpMove.swift"
mklink "spm\virt\PBR-CLI\Sources\GoDTextureImporter.swift" "%cd%\Objects\textures\GoDTextureImporter.swift"
mklink "spm\virt\PBR-CLI\Sources\XGTexturePalette.swift" "%cd%\Objects\textures\XGTexturePalette.swift"
mklink "spm\virt\PBR-CLI\Sources\XGContestCategories.swift" "%cd%\enums\XGContestCategories.swift"
mklink "spm\virt\PBR-CLI\Sources\EnumerableDocumentable.swift" "%cd%\protocols\EnumerableDocumentable.swift"
mklink "spm\virt\PBR-CLI\Sources\XGSettings.swift" "%cd%\Objects\managers\XGSettings.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRMoveTargets.swift" "%cd%\Revolution Tool CL\enums\PBRMoveTargets.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRDeckPokemon.swift" "%cd%\Revolution Tool CL\enums\PBRDeckPokemon.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRItem.swift" "%cd%\Revolution Tool CL\objects\PBRItem.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRConstant.swift" "%cd%\Revolution Tool CL\objects\PBRConstant.swift"
mklink "spm\virt\PBR-CLI\Sources\XGGenderRatios.swift" "%cd%\enums\XGGenderRatios.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRStringTable.swift" "%cd%\Revolution Tool CL\objects\PBRStringTable.swift"
mklink "spm\virt\PBR-CLI\Sources\main.swift" "%cd%\PBR-CLI\main.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRTextureContainingFormats.swift" "%cd%\Revolution Tool CL\objects\PBRTextureContainingFormats.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRTrainerPokemon.swift" "%cd%\Revolution Tool CL\objects\PBRTrainerPokemon.swift"
mklink "spm\virt\PBR-CLI\Sources\GoDTexture.swift" "%cd%\Objects\textures\GoDTexture.swift"
mklink "spm\virt\PBR-CLI\Sources\XGAssemblyCode.swift" "%cd%\Objects\file formats\XGAssemblyCode.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRScriptClassData.swift" "%cd%\Revolution Tool CL\objects\PBRScriptClassData.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRItems.swift" "%cd%\Revolution Tool CL\enums\PBRItems.swift"
mklink "spm\virt\PBR-CLI\Sources\XGDeoxysFormes.swift" "%cd%\enums\XGDeoxysFormes.swift"
mklink "spm\virt\PBR-CLI\Sources\GoDTexturesContaining.swift" "%cd%\Objects\file formats\GoDTexturesContaining.swift"
mklink "spm\virt\PBR-CLI\Sources\XGImage.swift" "%cd%\Objects\textures\XGImage.swift"
mklink "spm\virt\PBR-CLI\Sources\XGColour.swift" "%cd%\Objects\textures\XGColour.swift"
mklink "spm\virt\PBR-CLI\Sources\XGStack.swift" "%cd%\Objects\helper data types\XGStack.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRMoveEffectTypes.swift" "%cd%\Revolution Tool CL\enums\PBRMoveEffectTypes.swift"
mklink "spm\virt\PBR-CLI\Sources\GoDOSXExtensions.swift" "%cd%\extensions\GoDOSXExtensions.swift"
mklink "spm\virt\PBR-CLI\Sources\XGMutableData.swift" "%cd%\Objects\helper data types\XGMutableData.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRScript.swift" "%cd%\Revolution Tool CL\objects\PBRScript.swift"
mklink "spm\virt\PBR-CLI\Sources\PBRDataTable.swift" "%cd%\Revolution Tool CL\objects\PBRDataTable.swift"
mklink "spm\virt\PBR-CLI\Sources\XGPNGBlock.swift" "%cd%\Objects\textures\XGPNGBlock.swift"