#!/bin/bash
cd -- "$(dirname "$0")" #changes the terminal's directory to the directory where the script was launched
echo "Copying PBR Tool Assets. This may take a while..."
mkdir ./out/Assets
mkdir ./out/Assets/PBR
mkdir ./out/Assets/PBR/wiimm
cp ../images/PBR\ body/PBR_body_308.png ./out/Assets/PBR/PBR_body_308.png
cp ../images/PBR\ body/PBR_body_087.png ./out/Assets/PBR/PBR_body_087.png
cp ../images/PBR\ body/PBR_body_334.png ./out/Assets/PBR/PBR_body_334.png
cp ../images/PBR\ body/PBR_body_246.png ./out/Assets/PBR/PBR_body_246.png
cp ../images/PBR\ face/PBR_face_286.png ./out/Assets/PBR/PBR_face_286.png
cp ../images/PBR\ face/PBR_face_438.png ./out/Assets/PBR/PBR_face_438.png
cp ../images/PBR\ body/PBR_body_462.png ./out/Assets/PBR/PBR_body_462.png
cp ../images/PBR\ body/PBR_body_341.png ./out/Assets/PBR/PBR_body_341.png
cp ../images/PBR\ body/PBR_body_411.png ./out/Assets/PBR/PBR_body_411.png
cp ../images/PBR\ face/PBR_face_224.png ./out/Assets/PBR/PBR_face_224.png
cp ../images/PBR\ body/PBR_body_164.png ./out/Assets/PBR/PBR_body_164.png
cp ../images/PBR\ face/PBR_face_101.png ./out/Assets/PBR/PBR_face_101.png
cp ../images/PBR\ body/PBR_body_465.png ./out/Assets/PBR/PBR_body_465.png
cp ../images/PBR\ face/PBR_face_125.png ./out/Assets/PBR/PBR_face_125.png
cp ../images/PBR\ body/PBR_body_433.png ./out/Assets/PBR/PBR_body_433.png
cp ../images/PBR\ face/PBR_face_442.png ./out/Assets/PBR/PBR_face_442.png
cp ../images/PBR\ body/PBR_body_410.png ./out/Assets/PBR/PBR_body_410.png
cp ../images/PBR\ face/PBR_face_217.png ./out/Assets/PBR/PBR_face_217.png
cp ../images/PBR\ body/PBR_body_277.png ./out/Assets/PBR/PBR_body_277.png
cp ../images/PBR\ body/PBR_body_110.png ./out/Assets/PBR/PBR_body_110.png
cp ../images/PBR\ body/PBR_body_064.png ./out/Assets/PBR/PBR_body_064.png
cp ../images/PBR\ face/PBR_face_058.png ./out/Assets/PBR/PBR_face_058.png
cp ../images/PBR\ body/PBR_body_008.png ./out/Assets/PBR/PBR_body_008.png
cp ../images/PBR\ body/PBR_body_249.png ./out/Assets/PBR/PBR_body_249.png
cp ../images/PBR\ body/PBR_body_002.png ./out/Assets/PBR/PBR_body_002.png
cp ../images/PBR\ body/PBR_body_186.png ./out/Assets/PBR/PBR_body_186.png
cp ../images/PBR\ body/PBR_body_082.png ./out/Assets/PBR/PBR_body_082.png
cp ../images/PBR\ body/PBR_body_006.png ./out/Assets/PBR/PBR_body_006.png
cp ../images/PBR\ face/PBR_face_391.png ./out/Assets/PBR/PBR_face_391.png
cp ../images/PBR\ body/PBR_body_428.png ./out/Assets/PBR/PBR_body_428.png
cp ../images/PBR\ body/PBR_body_144.png ./out/Assets/PBR/PBR_body_144.png
cp ../images/PBR\ face/PBR_face_020.png ./out/Assets/PBR/PBR_face_020.png
cp ../images/PBR\ face/PBR_face_135.png ./out/Assets/PBR/PBR_face_135.png
cp ../images/PBR\ body/PBR_body_155.png ./out/Assets/PBR/PBR_body_155.png
cp ../images/PBR\ face/PBR_face_400.png ./out/Assets/PBR/PBR_face_400.png
cp ../images/PBR\ face/PBR_face_155.png ./out/Assets/PBR/PBR_face_155.png
cp ../images/PBR\ body/PBR_body_328.png ./out/Assets/PBR/PBR_body_328.png
cp ../images/Types/type_15.png ./out/Assets/PBR/type_15.png
cp ../images/PBR\ body/PBR_body_188.png ./out/Assets/PBR/PBR_body_188.png
cp ../images/PBR\ face/PBR_face_446.png ./out/Assets/PBR/PBR_face_446.png
cp ../images/PBR\ body/PBR_body_395.png ./out/Assets/PBR/PBR_body_395.png
cp ../images/PBR\ face/PBR_face_473.png ./out/Assets/PBR/PBR_face_473.png
cp ../images/PBR\ face/PBR_face_397.png ./out/Assets/PBR/PBR_face_397.png
cp ../images/PBR\ face/PBR_face_012.png ./out/Assets/PBR/PBR_face_012.png
cp ../images/PBR\ face/PBR_face_467.png ./out/Assets/PBR/PBR_face_467.png
cp ../images/PBR\ face/PBR_face_095.png ./out/Assets/PBR/PBR_face_095.png
cp ../images/PokeBalls/ball\ red.png ./out/Assets/PBR/ball\ red.png
cp ../images/PBR\ face/PBR_face_140.png ./out/Assets/PBR/PBR_face_140.png
cp ../images/PBR\ body/PBR_body_184.png ./out/Assets/PBR/PBR_body_184.png
cp ../images/PBR\ face/PBR_face_323.png ./out/Assets/PBR/PBR_face_323.png
cp ../images/PBR\ face/PBR_face_064.png ./out/Assets/PBR/PBR_face_064.png
cp ../images/PBR\ face/PBR_face_242.png ./out/Assets/PBR/PBR_face_242.png
cp ../images/PBR\ body/PBR_body_266.png ./out/Assets/PBR/PBR_body_266.png
cp ../images/PBR\ body/PBR_body_179.png ./out/Assets/PBR/PBR_body_179.png
cp ../images/PBR\ body/PBR_body_086.png ./out/Assets/PBR/PBR_body_086.png
cp ../images/PBR\ body/PBR_body_473.png ./out/Assets/PBR/PBR_body_473.png
cp ../images/PBR\ face/PBR_face_179.png ./out/Assets/PBR/PBR_face_179.png
cp ../images/PBR\ body/PBR_body_495.png ./out/Assets/PBR/PBR_body_495.png
cp ../images/PBR\ body/PBR_body_135.png ./out/Assets/PBR/PBR_body_135.png
cp ../images/PBR\ face/PBR_face_255.png ./out/Assets/PBR/PBR_face_255.png
cp ../images/PBR\ face/PBR_face_161.png ./out/Assets/PBR/PBR_face_161.png
cp ../images/PBR\ body/PBR_body_267.png ./out/Assets/PBR/PBR_body_267.png
cp ../images/PBR\ body/PBR_body_160.png ./out/Assets/PBR/PBR_body_160.png
cp ../images/PBR\ face/PBR_face_026.png ./out/Assets/PBR/PBR_face_026.png
cp ../images/PBR\ face/PBR_face_011.png ./out/Assets/PBR/PBR_face_011.png
cp ../images/PBR\ body/PBR_body_105.png ./out/Assets/PBR/PBR_body_105.png
cp ../images/PBR\ body/PBR_body_052.png ./out/Assets/PBR/PBR_body_052.png
cp ../images/PBR\ face/PBR_face_111.png ./out/Assets/PBR/PBR_face_111.png
cp ../images/PBR\ body/PBR_body_307.png ./out/Assets/PBR/PBR_body_307.png
cp ../images/PBR\ face/PBR_face_287.png ./out/Assets/PBR/PBR_face_287.png
cp ../images/PBR\ face/PBR_face_373.png ./out/Assets/PBR/PBR_face_373.png
cp ../images/PBR\ body/PBR_body_292.png ./out/Assets/PBR/PBR_body_292.png
cp ../images/PBR\ face/PBR_face_443.png ./out/Assets/PBR/PBR_face_443.png
cp ../images/PBR\ body/PBR_body_031.png ./out/Assets/PBR/PBR_body_031.png
cp ../images/PBR\ body/PBR_body_251.png ./out/Assets/PBR/PBR_body_251.png
cp ../images/PBR\ body/PBR_body_077.png ./out/Assets/PBR/PBR_body_077.png
cp ../images/PBR\ face/PBR_face_327.png ./out/Assets/PBR/PBR_face_327.png
cp ../images/PBR\ face/PBR_face_380.png ./out/Assets/PBR/PBR_face_380.png
cp ../images/PBR\ body/PBR_body_305.png ./out/Assets/PBR/PBR_body_305.png
cp ../images/PBR\ face/PBR_face_129.png ./out/Assets/PBR/PBR_face_129.png
cp ../images/PBR\ body/PBR_body_243.png ./out/Assets/PBR/PBR_body_243.png
cp ../images/PBR\ face/PBR_face_401.png ./out/Assets/PBR/PBR_face_401.png
cp ../images/PBR\ face/PBR_face_480.png ./out/Assets/PBR/PBR_face_480.png
cp ../images/PBR\ body/PBR_body_311.png ./out/Assets/PBR/PBR_body_311.png
cp ../images/PBR\ face/PBR_face_008.png ./out/Assets/PBR/PBR_face_008.png
cp ../images/PBR\ face/PBR_face_053.png ./out/Assets/PBR/PBR_face_053.png
cp ../images/PBR\ face/PBR_face_040.png ./out/Assets/PBR/PBR_face_040.png
cp ../images/PBR\ body/PBR_body_156.png ./out/Assets/PBR/PBR_body_156.png
cp ../images/PBR\ face/PBR_face_427.png ./out/Assets/PBR/PBR_face_427.png
cp ../images/PBR\ face/PBR_face_402.png ./out/Assets/PBR/PBR_face_402.png
cp ../images/PBR\ body/PBR_body_403.png ./out/Assets/PBR/PBR_body_403.png
cp ../images/PBR\ body/PBR_body_323.png ./out/Assets/PBR/PBR_body_323.png
cp ../images/PBR\ face/PBR_face_483.png ./out/Assets/PBR/PBR_face_483.png
cp ../images/PBR\ face/PBR_face_366.png ./out/Assets/PBR/PBR_face_366.png
cp ../images/PBR\ face/PBR_face_150.png ./out/Assets/PBR/PBR_face_150.png
cp ../images/PBR\ body/PBR_body_250.png ./out/Assets/PBR/PBR_body_250.png
cp ../images/PBR\ face/PBR_face_052.png ./out/Assets/PBR/PBR_face_052.png
cp ../images/PBR\ body/PBR_body_044.png ./out/Assets/PBR/PBR_body_044.png
cp ../images/PBR\ face/PBR_face_177.png ./out/Assets/PBR/PBR_face_177.png
cp ../images/PBR\ face/PBR_face_282.png ./out/Assets/PBR/PBR_face_282.png
cp ../images/PBR\ face/PBR_face_119.png ./out/Assets/PBR/PBR_face_119.png
cp ../images/PBR\ face/PBR_face_183.png ./out/Assets/PBR/PBR_face_183.png
cp ../images/PBR\ face/PBR_face_485.png ./out/Assets/PBR/PBR_face_485.png
cp ../images/PBR\ body/PBR_body_387.png ./out/Assets/PBR/PBR_body_387.png
cp ../images/PBR\ body/PBR_body_034.png ./out/Assets/PBR/PBR_body_034.png
cp ../images/PBR\ body/PBR_body_058.png ./out/Assets/PBR/PBR_body_058.png
cp ../images/PBR\ body/PBR_body_373.png ./out/Assets/PBR/PBR_body_373.png
cp ../images/PBR\ body/PBR_body_269.png ./out/Assets/PBR/PBR_body_269.png
cp ../images/PBR\ body/PBR_body_378.png ./out/Assets/PBR/PBR_body_378.png
cp ../images/PBR\ body/PBR_body_101.png ./out/Assets/PBR/PBR_body_101.png
cp ../images/PBR\ face/PBR_face_431.png ./out/Assets/PBR/PBR_face_431.png
cp ../images/PBR\ face/PBR_face_044.png ./out/Assets/PBR/PBR_face_044.png
cp ../images/PBR\ body/PBR_body_276.png ./out/Assets/PBR/PBR_body_276.png
cp ../images/PBR\ body/PBR_body_333.png ./out/Assets/PBR/PBR_body_333.png
cp ../images/PBR\ body/PBR_body_442.png ./out/Assets/PBR/PBR_body_442.png
cp ../images/Types/type_2.png ./out/Assets/PBR/type_2.png
cp ../images/PBR\ body/PBR_body_349.png ./out/Assets/PBR/PBR_body_349.png
cp ../images/PBR\ face/PBR_face_392.png ./out/Assets/PBR/PBR_face_392.png
cp ../images/PBR\ body/PBR_body_113.png ./out/Assets/PBR/PBR_body_113.png
cp ../images/PBR\ body/PBR_body_484.png ./out/Assets/PBR/PBR_body_484.png
cp ../images/PBR\ body/PBR_body_239.png ./out/Assets/PBR/PBR_body_239.png
cp ../images/PBR\ body/PBR_body_138.png ./out/Assets/PBR/PBR_body_138.png
cp ../images/PBR\ face/PBR_face_025.png ./out/Assets/PBR/PBR_face_025.png
cp ../images/PBR\ face/PBR_face_453.png ./out/Assets/PBR/PBR_face_453.png
cp ../images/PBR\ body/PBR_body_293.png ./out/Assets/PBR/PBR_body_293.png
cp ../images/PBR\ face/PBR_face_213.png ./out/Assets/PBR/PBR_face_213.png
cp ../images/PBR\ face/PBR_face_326.png ./out/Assets/PBR/PBR_face_326.png
cp ../images/PBR\ body/PBR_body_220.png ./out/Assets/PBR/PBR_body_220.png
cp ../images/PBR\ face/PBR_face_182.png ./out/Assets/PBR/PBR_face_182.png
cp ../images/PBR\ face/PBR_face_347.png ./out/Assets/PBR/PBR_face_347.png
cp ../images/PBR\ body/PBR_body_280.png ./out/Assets/PBR/PBR_body_280.png
cp ../images/PBR\ body/PBR_body_375.png ./out/Assets/PBR/PBR_body_375.png
cp ../images/PBR\ face/PBR_face_468.png ./out/Assets/PBR/PBR_face_468.png
cp ../images/Table\ View\ Cells/Tool\ Cell.png ./out/Assets/PBR/Tool\ Cell.png
cp ../images/PBR\ body/PBR_body_096.png ./out/Assets/PBR/PBR_body_096.png
cp ../images/PBR\ body/PBR_body_435.png ./out/Assets/PBR/PBR_body_435.png
cp ../images/PBR\ face/PBR_face_294.png ./out/Assets/PBR/PBR_face_294.png
cp ../images/PBR\ body/PBR_body_163.png ./out/Assets/PBR/PBR_body_163.png
cp ../images/PBR\ body/PBR_body_380.png ./out/Assets/PBR/PBR_body_380.png
cp ../images/PBR\ body/PBR_body_306.png ./out/Assets/PBR/PBR_body_306.png
cp ../images/Types/type_shadow.png ./out/Assets/PBR/type_shadow.png
cp ../images/PBR\ body/PBR_body_339.png ./out/Assets/PBR/PBR_body_339.png
cp ../images/PBR\ body/PBR_body_089.png ./out/Assets/PBR/PBR_body_089.png
cp ../images/PBR\ body/PBR_body_253.png ./out/Assets/PBR/PBR_body_253.png
cp ../images/PBR\ face/PBR_face_081.png ./out/Assets/PBR/PBR_face_081.png
cp ../images/PBR\ body/PBR_body_063.png ./out/Assets/PBR/PBR_body_063.png
cp ../images/PBR\ body/PBR_body_468.png ./out/Assets/PBR/PBR_body_468.png
cp ../images/PBR\ face/PBR_face_359.png ./out/Assets/PBR/PBR_face_359.png
cp ../images/PBR\ body/PBR_body_238.png ./out/Assets/PBR/PBR_body_238.png
cp ../images/PBR\ body/PBR_body_154.png ./out/Assets/PBR/PBR_body_154.png
cp ../images/PBR\ face/PBR_face_464.png ./out/Assets/PBR/PBR_face_464.png
cp ../images/PBR\ face/PBR_face_253.png ./out/Assets/PBR/PBR_face_253.png
cp ../images/PBR\ body/PBR_body_450.png ./out/Assets/PBR/PBR_body_450.png
cp ../images/PBR\ face/PBR_face_245.png ./out/Assets/PBR/PBR_face_245.png
cp ../images/PBR\ face/PBR_face_457.png ./out/Assets/PBR/PBR_face_457.png
cp ../images/PBR\ body/PBR_body_088.png ./out/Assets/PBR/PBR_body_088.png
cp ../images/PBR\ face/PBR_face_096.png ./out/Assets/PBR/PBR_face_096.png
cp ../images/PBR\ face/PBR_face_275.png ./out/Assets/PBR/PBR_face_275.png
cp ../images/PBR\ body/PBR_body_318.png ./out/Assets/PBR/PBR_body_318.png
cp ../images/PBR\ body/PBR_body_355.png ./out/Assets/PBR/PBR_body_355.png
cp ../images/PBR\ face/PBR_face_243.png ./out/Assets/PBR/PBR_face_243.png
cp ../images/PBR\ body/PBR_body_049.png ./out/Assets/PBR/PBR_body_049.png
cp ../images/PBR\ face/PBR_face_121.png ./out/Assets/PBR/PBR_face_121.png
cp ../images/PBR\ face/PBR_face_153.png ./out/Assets/PBR/PBR_face_153.png
cp ../images/PBR\ face/PBR_face_187.png ./out/Assets/PBR/PBR_face_187.png
cp ../images/PBR\ face/PBR_face_424.png ./out/Assets/PBR/PBR_face_424.png
cp ../JSON/PBR/Original\ Moves.json ./out/Assets/PBR/Original\ Moves.json
cp ../images/PBR\ body/PBR_body_227.png ./out/Assets/PBR/PBR_body_227.png
cp ../images/PBR\ body/PBR_body_109.png ./out/Assets/PBR/PBR_body_109.png
cp ../images/PBR\ body/PBR_body_039.png ./out/Assets/PBR/PBR_body_039.png
cp ../images/PBR\ body/PBR_body_371.png ./out/Assets/PBR/PBR_body_371.png
cp ../images/PBR\ face/PBR_face_456.png ./out/Assets/PBR/PBR_face_456.png
cp ../images/PBR\ body/PBR_body_274.png ./out/Assets/PBR/PBR_body_274.png
cp ../images/PBR\ body/PBR_body_259.png ./out/Assets/PBR/PBR_body_259.png
cp ../images/PBR\ body/PBR_body_400.png ./out/Assets/PBR/PBR_body_400.png
cp ../images/PBR\ face/PBR_face_317.png ./out/Assets/PBR/PBR_face_317.png
cp ../images/PBR\ face/PBR_face_214.png ./out/Assets/PBR/PBR_face_214.png
cp ../images/PBR\ face/PBR_face_212.png ./out/Assets/PBR/PBR_face_212.png
cp ../images/PBR\ face/PBR_face_378.png ./out/Assets/PBR/PBR_face_378.png
cp ../images/PBR\ face/PBR_face_076.png ./out/Assets/PBR/PBR_face_076.png
cp ../images/PBR\ body/PBR_body_133.png ./out/Assets/PBR/PBR_body_133.png
cp ../images/PBR\ face/PBR_face_216.png ./out/Assets/PBR/PBR_face_216.png
cp ../images/PBR\ face/PBR_face_290.png ./out/Assets/PBR/PBR_face_290.png
cp ../images/PBR\ body/PBR_body_152.png ./out/Assets/PBR/PBR_body_152.png
cp ../images/PBR\ face/PBR_face_087.png ./out/Assets/PBR/PBR_face_087.png
cp ../images/PBR\ body/PBR_body_379.png ./out/Assets/PBR/PBR_body_379.png
cp ../images/PBR\ body/PBR_body_185.png ./out/Assets/PBR/PBR_body_185.png
cp ../images/PBR\ body/PBR_body_040.png ./out/Assets/PBR/PBR_body_040.png
cp ../images/PBR\ body/PBR_body_331.png ./out/Assets/PBR/PBR_body_331.png
cp ../images/PBR\ body/PBR_body_368.png ./out/Assets/PBR/PBR_body_368.png
cp ../images/Types/type_fairy.png ./out/Assets/PBR/type_fairy.png
cp ../images/PBR\ body/PBR_body_346.png ./out/Assets/PBR/PBR_body_346.png
cp ../images/PBR\ body/PBR_body_391.png ./out/Assets/PBR/PBR_body_391.png
cp ../images/PBR\ body/PBR_body_009.png ./out/Assets/PBR/PBR_body_009.png
cp ../images/PBR\ body/PBR_body_136.png ./out/Assets/PBR/PBR_body_136.png
cp ../images/PBR\ face/PBR_face_109.png ./out/Assets/PBR/PBR_face_109.png
cp ../images/PBR\ face/PBR_face_288.png ./out/Assets/PBR/PBR_face_288.png
cp ../images/PBR\ body/PBR_body_153.png ./out/Assets/PBR/PBR_body_153.png
cp ../images/PBR\ body/PBR_body_094.png ./out/Assets/PBR/PBR_body_094.png
cp ../images/PBR\ body/PBR_body_221.png ./out/Assets/PBR/PBR_body_221.png
cp ../images/PBR\ face/PBR_face_126.png ./out/Assets/PBR/PBR_face_126.png
cp ../images/PBR\ body/PBR_body_486.png ./out/Assets/PBR/PBR_body_486.png
cp ../images/PBR\ face/PBR_face_471.png ./out/Assets/PBR/PBR_face_471.png
cp ../images/PBR\ body/PBR_body_423.png ./out/Assets/PBR/PBR_body_423.png
cp ../images/PBR\ body/PBR_body_035.png ./out/Assets/PBR/PBR_body_035.png
cp ../images/PBR\ body/PBR_body_284.png ./out/Assets/PBR/PBR_body_284.png
cp ../images/PBR\ body/PBR_body_367.png ./out/Assets/PBR/PBR_body_367.png
cp ../images/PBR\ body/PBR_body_132.png ./out/Assets/PBR/PBR_body_132.png
cp ../images/Types/type_8.png ./out/Assets/PBR/type_8.png
cp ../images/PBR\ face/PBR_face_264.png ./out/Assets/PBR/PBR_face_264.png
cp ../images/PBR\ body/PBR_body_124.png ./out/Assets/PBR/PBR_body_124.png
cp ../images/Types/type_14.png ./out/Assets/PBR/type_14.png
cp ../images/PBR\ face/PBR_face_097.png ./out/Assets/PBR/PBR_face_097.png
cp ../images/PBR\ face/PBR_face_238.png ./out/Assets/PBR/PBR_face_238.png
cp ../images/PBR\ face/PBR_face_246.png ./out/Assets/PBR/PBR_face_246.png
cp ../images/PBR\ body/PBR_body_021.png ./out/Assets/PBR/PBR_body_021.png
cp ../images/PBR\ face/PBR_face_185.png ./out/Assets/PBR/PBR_face_185.png
cp ../images/PBR\ face/PBR_face_120.png ./out/Assets/PBR/PBR_face_120.png
cp ../images/PBR\ body/PBR_body_038.png ./out/Assets/PBR/PBR_body_038.png
cp ../images/PBR\ face/PBR_face_127.png ./out/Assets/PBR/PBR_face_127.png
cp ../images/PBR\ face/PBR_face_200.png ./out/Assets/PBR/PBR_face_200.png
cp ../images/PBR\ body/PBR_body_130.png ./out/Assets/PBR/PBR_body_130.png
cp ../images/PBR\ face/PBR_face_105.png ./out/Assets/PBR/PBR_face_105.png
cp ../images/PBR\ face/PBR_face_389.png ./out/Assets/PBR/PBR_face_389.png
cp ../images/PBR\ face/PBR_face_090.png ./out/Assets/PBR/PBR_face_090.png
cp ../images/PBR\ face/PBR_face_419.png ./out/Assets/PBR/PBR_face_419.png
cp ../images/PBR\ face/PBR_face_116.png ./out/Assets/PBR/PBR_face_116.png
cp ../images/PBR\ body/PBR_body_022.png ./out/Assets/PBR/PBR_body_022.png
cp ../images/PBR\ face/PBR_face_007.png ./out/Assets/PBR/PBR_face_007.png
cp ../images/PBR\ face/PBR_face_203.png ./out/Assets/PBR/PBR_face_203.png
cp ../images/PBR\ body/PBR_body_080.png ./out/Assets/PBR/PBR_body_080.png
cp ../images/PBR\ face/PBR_face_139.png ./out/Assets/PBR/PBR_face_139.png
cp ../images/PBR\ body/PBR_body_419.png ./out/Assets/PBR/PBR_body_419.png
cp ../images/PBR\ face/PBR_face_460.png ./out/Assets/PBR/PBR_face_460.png
cp ../images/PBR\ face/PBR_face_114.png ./out/Assets/PBR/PBR_face_114.png
cp ../images/PBR\ face/PBR_face_077.png ./out/Assets/PBR/PBR_face_077.png
cp ../images/PBR\ body/PBR_body_463.png ./out/Assets/PBR/PBR_body_463.png
cp ../images/PBR\ body/PBR_body_342.png ./out/Assets/PBR/PBR_body_342.png
cp ../images/PBR\ body/PBR_body_196.png ./out/Assets/PBR/PBR_body_196.png
cp ../images/PBR\ body/PBR_body_389.png ./out/Assets/PBR/PBR_body_389.png
cp ../images/PBR\ face/PBR_face_241.png ./out/Assets/PBR/PBR_face_241.png
cp ../images/PBR\ face/PBR_face_500.png ./out/Assets/PBR/PBR_face_500.png
cp ../images/PBR\ face/PBR_face_262.png ./out/Assets/PBR/PBR_face_262.png
cp ../images/PBR\ face/PBR_face_098.png ./out/Assets/PBR/PBR_face_098.png
cp ../images/PBR\ face/PBR_face_193.png ./out/Assets/PBR/PBR_face_193.png
cp ../images/PBR\ face/PBR_face_146.png ./out/Assets/PBR/PBR_face_146.png
cp ../images/PBR\ face/PBR_face_361.png ./out/Assets/PBR/PBR_face_361.png
cp ../images/PBR\ body/PBR_body_047.png ./out/Assets/PBR/PBR_body_047.png
cp ../images/PBR\ face/PBR_face_176.png ./out/Assets/PBR/PBR_face_176.png
cp ../images/PBR\ body/PBR_body_347.png ./out/Assets/PBR/PBR_body_347.png
cp ../images/PBR\ face/PBR_face_190.png ./out/Assets/PBR/PBR_face_190.png
cp ../images/PBR\ body/PBR_body_095.png ./out/Assets/PBR/PBR_body_095.png
cp ../images/PBR\ face/PBR_face_272.png ./out/Assets/PBR/PBR_face_272.png
cp ../images/PBR\ face/PBR_face_133.png ./out/Assets/PBR/PBR_face_133.png
cp ../images/PBR\ face/PBR_face_478.png ./out/Assets/PBR/PBR_face_478.png
cp ../images/PBR\ body/PBR_body_242.png ./out/Assets/PBR/PBR_body_242.png
cp ../images/PBR\ body/PBR_body_271.png ./out/Assets/PBR/PBR_body_271.png
cp ../images/PBR\ body/PBR_body_309.png ./out/Assets/PBR/PBR_body_309.png
cp ../images/PBR\ face/PBR_face_158.png ./out/Assets/PBR/PBR_face_158.png
cp ../images/PBR\ face/PBR_face_234.png ./out/Assets/PBR/PBR_face_234.png
cp ../images/PBR\ body/PBR_body_214.png ./out/Assets/PBR/PBR_body_214.png
cp ../images/PBR\ face/PBR_face_318.png ./out/Assets/PBR/PBR_face_318.png
cp ../images/PBR\ face/PBR_face_299.png ./out/Assets/PBR/PBR_face_299.png
cp ../images/PBR\ body/PBR_body_273.png ./out/Assets/PBR/PBR_body_273.png
cp ../images/PBR\ face/PBR_face_022.png ./out/Assets/PBR/PBR_face_022.png
cp ../images/PBR\ body/PBR_body_487.png ./out/Assets/PBR/PBR_body_487.png
cp ../images/PBR\ face/PBR_face_103.png ./out/Assets/PBR/PBR_face_103.png
cp ../images/PBR\ face/PBR_face_219.png ./out/Assets/PBR/PBR_face_219.png
cp ../images/PBR\ face/PBR_face_115.png ./out/Assets/PBR/PBR_face_115.png
cp ../images/PBR\ face/PBR_face_032.png ./out/Assets/PBR/PBR_face_032.png
cp ../images/PBR\ body/PBR_body_457.png ./out/Assets/PBR/PBR_body_457.png
cp ../images/PBR\ body/PBR_body_490.png ./out/Assets/PBR/PBR_body_490.png
cp ../images/PBR\ face/PBR_face_142.png ./out/Assets/PBR/PBR_face_142.png
cp ../images/PBR\ face/PBR_face_369.png ./out/Assets/PBR/PBR_face_369.png
cp ../images/PBR\ body/PBR_body_032.png ./out/Assets/PBR/PBR_body_032.png
cp ../images/PBR\ body/PBR_body_278.png ./out/Assets/PBR/PBR_body_278.png
cp ../images/PBR\ body/PBR_body_165.png ./out/Assets/PBR/PBR_body_165.png
cp ../images/PBR\ body/PBR_body_326.png ./out/Assets/PBR/PBR_body_326.png
cp ../images/PBR\ face/PBR_face_454.png ./out/Assets/PBR/PBR_face_454.png
cp ../images/PBR\ face/PBR_face_149.png ./out/Assets/PBR/PBR_face_149.png
cp ../images/PBR\ body/PBR_body_466.png ./out/Assets/PBR/PBR_body_466.png
cp ../images/PBR\ body/PBR_body_420.png ./out/Assets/PBR/PBR_body_420.png
cp ../images/PBR\ body/PBR_body_340.png ./out/Assets/PBR/PBR_body_340.png
cp ../images/PBR\ body/PBR_body_013.png ./out/Assets/PBR/PBR_body_013.png
cp ../images/PBR\ body/PBR_body_041.png ./out/Assets/PBR/PBR_body_041.png
cp ../images/Types/type_3.png ./out/Assets/PBR/type_3.png
cp ../images/PBR\ body/PBR_body_496.png ./out/Assets/PBR/PBR_body_496.png
cp ../images/PBR\ face/PBR_face_300.png ./out/Assets/PBR/PBR_face_300.png
cp ../images/PBR\ face/PBR_face_104.png ./out/Assets/PBR/PBR_face_104.png
cp ../images/PBR\ face/PBR_face_398.png ./out/Assets/PBR/PBR_face_398.png
cp ../images/PBR\ face/PBR_face_296.png ./out/Assets/PBR/PBR_face_296.png
cp ../images/PBR\ body/PBR_body_444.png ./out/Assets/PBR/PBR_body_444.png
cp ../images/PBR\ face/PBR_face_042.png ./out/Assets/PBR/PBR_face_042.png
cp ../images/PBR\ face/PBR_face_497.png ./out/Assets/PBR/PBR_face_497.png
cp ../images/PBR\ body/PBR_body_122.png ./out/Assets/PBR/PBR_body_122.png
cp ../images/PBR\ face/PBR_face_274.png ./out/Assets/PBR/PBR_face_274.png
cp ../images/PBR\ face/PBR_face_448.png ./out/Assets/PBR/PBR_face_448.png
cp ../images/PBR\ body/PBR_body_327.png ./out/Assets/PBR/PBR_body_327.png
cp ../images/PBR\ body/PBR_body_377.png ./out/Assets/PBR/PBR_body_377.png
cp ../images/PBR\ body/PBR_body_183.png ./out/Assets/PBR/PBR_body_183.png
cp ../images/PBR\ body/PBR_body_053.png ./out/Assets/PBR/PBR_body_053.png
cp ../images/PBR\ body/PBR_body_388.png ./out/Assets/PBR/PBR_body_388.png
cp ../images/PBR\ body/PBR_body_252.png ./out/Assets/PBR/PBR_body_252.png
cp ../images/PBR\ face/PBR_face_476.png ./out/Assets/PBR/PBR_face_476.png
cp ../images/PBR\ body/PBR_body_128.png ./out/Assets/PBR/PBR_body_128.png
cp ../images/PBR\ body/PBR_body_474.png ./out/Assets/PBR/PBR_body_474.png
cp ../images/PBR\ face/PBR_face_027.png ./out/Assets/PBR/PBR_face_027.png
cp ../images/PBR\ body/PBR_body_059.png ./out/Assets/PBR/PBR_body_059.png
cp ../images/PBR\ body/PBR_body_254.png ./out/Assets/PBR/PBR_body_254.png
cp ../images/PBR\ body/PBR_body_301.png ./out/Assets/PBR/PBR_body_301.png
cp ../images/PBR\ body/PBR_body_257.png ./out/Assets/PBR/PBR_body_257.png
cp ../images/PBR\ body/PBR_body_424.png ./out/Assets/PBR/PBR_body_424.png
cp ../images/PBR\ body/PBR_body_431.png ./out/Assets/PBR/PBR_body_431.png
cp ../images/PBR\ face/PBR_face_499.png ./out/Assets/PBR/PBR_face_499.png
cp ../images/PBR\ body/PBR_body_264.png ./out/Assets/PBR/PBR_body_264.png
cp ../images/PBR\ face/PBR_face_048.png ./out/Assets/PBR/PBR_face_048.png
cp ../images/PBR\ face/PBR_face_015.png ./out/Assets/PBR/PBR_face_015.png
cp ../images/PBR\ face/PBR_face_441.png ./out/Assets/PBR/PBR_face_441.png
cp ../images/PBR\ face/PBR_face_313.png ./out/Assets/PBR/PBR_face_313.png
cp ../images/PBR\ face/PBR_face_350.png ./out/Assets/PBR/PBR_face_350.png
cp ../images/PBR\ face/PBR_face_005.png ./out/Assets/PBR/PBR_face_005.png
cp ../images/PBR\ face/PBR_face_173.png ./out/Assets/PBR/PBR_face_173.png
cp ../images/PBR\ face/PBR_face_340.png ./out/Assets/PBR/PBR_face_340.png
cp ../images/PBR\ face/PBR_face_033.png ./out/Assets/PBR/PBR_face_033.png
cp ../images/PBR\ body/PBR_body_111.png ./out/Assets/PBR/PBR_body_111.png
cp ../images/PBR\ body/PBR_body_281.png ./out/Assets/PBR/PBR_body_281.png
cp ../images/PBR\ body/PBR_body_148.png ./out/Assets/PBR/PBR_body_148.png
cp ../images/PBR\ face/PBR_face_000.png ./out/Assets/PBR/PBR_face_000.png
cp ../images/PBR\ face/PBR_face_445.png ./out/Assets/PBR/PBR_face_445.png
cp ../images/Types/type_11.png ./out/Assets/PBR/type_11.png
cp ../images/PBR\ body/PBR_body_452.png ./out/Assets/PBR/PBR_body_452.png
cp ../images/PBR\ face/PBR_face_244.png ./out/Assets/PBR/PBR_face_244.png
cp ../images/PBR\ face/PBR_face_131.png ./out/Assets/PBR/PBR_face_131.png
cp ../images/PBR\ body/PBR_body_472.png ./out/Assets/PBR/PBR_body_472.png
cp ../images/PBR\ face/PBR_face_328.png ./out/Assets/PBR/PBR_face_328.png
cp ../images/PBR\ body/PBR_body_017.png ./out/Assets/PBR/PBR_body_017.png
cp ../images/PBR\ face/PBR_face_178.png ./out/Assets/PBR/PBR_face_178.png
cp ../images/PBR\ face/PBR_face_049.png ./out/Assets/PBR/PBR_face_049.png
cp ../images/PBR\ body/PBR_body_441.png ./out/Assets/PBR/PBR_body_441.png
cp ../images/PBR\ face/PBR_face_330.png ./out/Assets/PBR/PBR_face_330.png
cp ../images/PBR\ face/PBR_face_266.png ./out/Assets/PBR/PBR_face_266.png
cp ../images/PBR\ face/PBR_face_192.png ./out/Assets/PBR/PBR_face_192.png
cp ../images/PBR\ face/PBR_face_215.png ./out/Assets/PBR/PBR_face_215.png
cp ../images/PBR\ body/PBR_body_256.png ./out/Assets/PBR/PBR_body_256.png
cp ../images/PBR\ face/PBR_face_428.png ./out/Assets/PBR/PBR_face_428.png
cp ../images/PBR\ face/PBR_face_447.png ./out/Assets/PBR/PBR_face_447.png
cp ../images/PBR\ face/PBR_face_306.png ./out/Assets/PBR/PBR_face_306.png
cp ../images/PBR\ face/PBR_face_495.png ./out/Assets/PBR/PBR_face_495.png
cp ../images/PBR\ body/PBR_body_061.png ./out/Assets/PBR/PBR_body_061.png
cp ../images/Types/type_1.png ./out/Assets/PBR/type_1.png
cp ../images/PBR\ face/PBR_face_132.png ./out/Assets/PBR/PBR_face_132.png
cp ../images/PBR\ body/PBR_body_374.png ./out/Assets/PBR/PBR_body_374.png
cp ../images/PBR\ face/PBR_face_412.png ./out/Assets/PBR/PBR_face_412.png
cp ../images/PBR\ body/PBR_body_191.png ./out/Assets/PBR/PBR_body_191.png
cp ../images/PBR\ face/PBR_face_474.png ./out/Assets/PBR/PBR_face_474.png
cp ../images/PBR\ face/PBR_face_130.png ./out/Assets/PBR/PBR_face_130.png
cp ../images/PBR\ body/PBR_body_223.png ./out/Assets/PBR/PBR_body_223.png
cp ../images/PBR\ face/PBR_face_174.png ./out/Assets/PBR/PBR_face_174.png
cp ../images/PBR\ body/PBR_body_244.png ./out/Assets/PBR/PBR_body_244.png
cp ../images/PBR\ face/PBR_face_170.png ./out/Assets/PBR/PBR_face_170.png
cp ../images/PBR\ body/PBR_body_483.png ./out/Assets/PBR/PBR_body_483.png
cp ../images/PBR\ face/PBR_face_037.png ./out/Assets/PBR/PBR_face_037.png
cp ../images/PBR\ body/PBR_body_162.png ./out/Assets/PBR/PBR_body_162.png
cp ../images/PBR\ body/PBR_body_415.png ./out/Assets/PBR/PBR_body_415.png
cp ../images/PBR\ face/PBR_face_309.png ./out/Assets/PBR/PBR_face_309.png
cp ../images/PBR\ body/PBR_body_181.png ./out/Assets/PBR/PBR_body_181.png
cp ../images/PBR\ body/PBR_body_117.png ./out/Assets/PBR/PBR_body_117.png
cp ../images/PBR\ body/PBR_body_104.png ./out/Assets/PBR/PBR_body_104.png
cp ../images/PBR\ face/PBR_face_430.png ./out/Assets/PBR/PBR_face_430.png
cp ../images/PBR\ body/PBR_body_248.png ./out/Assets/PBR/PBR_body_248.png
cp ../images/PBR\ face/PBR_face_277.png ./out/Assets/PBR/PBR_face_277.png
cp ../images/PBR\ body/PBR_body_050.png ./out/Assets/PBR/PBR_body_050.png
cp ../images/PBR\ body/PBR_body_177.png ./out/Assets/PBR/PBR_body_177.png
cp ../images/PBR\ body/PBR_body_033.png ./out/Assets/PBR/PBR_body_033.png
cp ../images/PBR\ body/PBR_body_129.png ./out/Assets/PBR/PBR_body_129.png
cp ../images/PBR\ face/PBR_face_407.png ./out/Assets/PBR/PBR_face_407.png
cp ../images/PBR\ face/PBR_face_047.png ./out/Assets/PBR/PBR_face_047.png
cp ../images/PBR\ face/PBR_face_488.png ./out/Assets/PBR/PBR_face_488.png
cp ../images/PBR\ face/PBR_face_329.png ./out/Assets/PBR/PBR_face_329.png
cp ../images/PBR\ face/PBR_face_210.png ./out/Assets/PBR/PBR_face_210.png
cp ../images/PBR\ body/PBR_body_417.png ./out/Assets/PBR/PBR_body_417.png
cp ../images/PBR\ body/PBR_body_056.png ./out/Assets/PBR/PBR_body_056.png
cp ../images/PBR\ face/PBR_face_265.png ./out/Assets/PBR/PBR_face_265.png
cp ../images/PBR\ face/PBR_face_186.png ./out/Assets/PBR/PBR_face_186.png
cp ../images/PBR\ face/PBR_face_191.png ./out/Assets/PBR/PBR_face_191.png
cp ../images/PBR\ body/PBR_body_127.png ./out/Assets/PBR/PBR_body_127.png
cp ../images/PBR\ body/PBR_body_204.png ./out/Assets/PBR/PBR_body_204.png
cp ../images/PBR\ body/PBR_body_314.png ./out/Assets/PBR/PBR_body_314.png
cp ../images/PBR\ face/PBR_face_342.png ./out/Assets/PBR/PBR_face_342.png
cp ../images/PBR\ face/PBR_face_137.png ./out/Assets/PBR/PBR_face_137.png
cp ../images/PBR\ face/PBR_face_320.png ./out/Assets/PBR/PBR_face_320.png
cp ../images/PBR\ face/PBR_face_336.png ./out/Assets/PBR/PBR_face_336.png
cp ../images/PBR\ body/PBR_body_029.png ./out/Assets/PBR/PBR_body_029.png
cp ../images/PBR\ face/PBR_face_343.png ./out/Assets/PBR/PBR_face_343.png
cp ../images/PBR\ face/PBR_face_070.png ./out/Assets/PBR/PBR_face_070.png
cp ../images/PBR\ face/PBR_face_321.png ./out/Assets/PBR/PBR_face_321.png
cp ../images/PBR\ face/PBR_face_260.png ./out/Assets/PBR/PBR_face_260.png
cp ../images/PBR\ face/PBR_face_257.png ./out/Assets/PBR/PBR_face_257.png
cp ../images/PBR\ face/PBR_face_043.png ./out/Assets/PBR/PBR_face_043.png
cp ../images/PBR\ body/PBR_body_145.png ./out/Assets/PBR/PBR_body_145.png
cp ../images/PBR\ body/PBR_body_098.png ./out/Assets/PBR/PBR_body_098.png
cp ../images/PBR\ face/PBR_face_311.png ./out/Assets/PBR/PBR_face_311.png
cp ../images/PBR\ face/PBR_face_381.png ./out/Assets/PBR/PBR_face_381.png
cp ../images/PBR\ body/PBR_body_398.png ./out/Assets/PBR/PBR_body_398.png
cp ../images/PBR\ face/PBR_face_314.png ./out/Assets/PBR/PBR_face_314.png
cp ../images/PBR\ face/PBR_face_151.png ./out/Assets/PBR/PBR_face_151.png
cp ../images/PBR\ body/PBR_body_060.png ./out/Assets/PBR/PBR_body_060.png
cp ../images/PBR\ face/PBR_face_490.png ./out/Assets/PBR/PBR_face_490.png
cp ../images/PBR\ body/PBR_body_182.png ./out/Assets/PBR/PBR_body_182.png
cp ../images/PBR\ body/PBR_body_043.png ./out/Assets/PBR/PBR_body_043.png
cp ../images/PBR\ body/PBR_body_118.png ./out/Assets/PBR/PBR_body_118.png
cp ../images/PBR\ body/PBR_body_247.png ./out/Assets/PBR/PBR_body_247.png
cp ../images/PBR\ face/PBR_face_084.png ./out/Assets/PBR/PBR_face_084.png
cp ../images/PBR\ body/PBR_body_131.png ./out/Assets/PBR/PBR_body_131.png
cp ../images/PBR\ face/PBR_face_461.png ./out/Assets/PBR/PBR_face_461.png
cp ../images/PBR\ face/PBR_face_233.png ./out/Assets/PBR/PBR_face_233.png
cp ../images/PBR\ body/PBR_body_235.png ./out/Assets/PBR/PBR_body_235.png
cp ../images/PBR\ body/PBR_body_351.png ./out/Assets/PBR/PBR_body_351.png
cp ../images/PBR\ face/PBR_face_227.png ./out/Assets/PBR/PBR_face_227.png
cp ../images/PBR\ body/PBR_body_282.png ./out/Assets/PBR/PBR_body_282.png
cp ../images/PBR\ body/PBR_body_436.png ./out/Assets/PBR/PBR_body_436.png
cp ../images/PBR\ body/PBR_body_074.png ./out/Assets/PBR/PBR_body_074.png
cp ../images/PBR\ body/PBR_body_356.png ./out/Assets/PBR/PBR_body_356.png
cp ../images/PBR\ face/PBR_face_237.png ./out/Assets/PBR/PBR_face_237.png
cp ../images/PBR\ body/PBR_body_066.png ./out/Assets/PBR/PBR_body_066.png
cp ../images/PBR\ body/PBR_body_149.png ./out/Assets/PBR/PBR_body_149.png
cp ../images/PBR\ face/PBR_face_348.png ./out/Assets/PBR/PBR_face_348.png
cp ../images/PBR\ face/PBR_face_267.png ./out/Assets/PBR/PBR_face_267.png
cp ../images/PBR\ body/PBR_body_241.png ./out/Assets/PBR/PBR_body_241.png
cp ../images/PBR\ body/PBR_body_233.png ./out/Assets/PBR/PBR_body_233.png
cp ../images/PBR\ face/PBR_face_319.png ./out/Assets/PBR/PBR_face_319.png
cp ../images/PBR\ body/PBR_body_000.png ./out/Assets/PBR/PBR_body_000.png
cp ../images/PBR\ body/PBR_body_336.png ./out/Assets/PBR/PBR_body_336.png
cp ../images/Types/type_16.png ./out/Assets/PBR/type_16.png
cp ../images/Table\ View\ Cells/File\ Cell.png ./out/Assets/PBR/File\ Cell.png
cp ../images/PBR\ body/PBR_body_383.png ./out/Assets/PBR/PBR_body_383.png
cp ../images/PBR\ body/PBR_body_140.png ./out/Assets/PBR/PBR_body_140.png
cp ../images/PBR\ face/PBR_face_194.png ./out/Assets/PBR/PBR_face_194.png
cp ../images/PBR\ face/PBR_face_414.png ./out/Assets/PBR/PBR_face_414.png
cp ../images/PBR\ body/PBR_body_329.png ./out/Assets/PBR/PBR_body_329.png
cp ../images/PBR\ face/PBR_face_078.png ./out/Assets/PBR/PBR_face_078.png
cp ../images/PBR\ body/PBR_body_003.png ./out/Assets/PBR/PBR_body_003.png
cp ../images/PBR\ body/PBR_body_343.png ./out/Assets/PBR/PBR_body_343.png
cp ../images/PBR\ body/PBR_body_332.png ./out/Assets/PBR/PBR_body_332.png
cp ../images/PBR\ body/PBR_body_212.png ./out/Assets/PBR/PBR_body_212.png
cp ../images/PBR\ body/PBR_body_426.png ./out/Assets/PBR/PBR_body_426.png
cp ../images/PBR\ body/PBR_body_416.png ./out/Assets/PBR/PBR_body_416.png
cp ../images/PBR\ body/PBR_body_232.png ./out/Assets/PBR/PBR_body_232.png
cp ../images/PBR\ face/PBR_face_293.png ./out/Assets/PBR/PBR_face_293.png
cp ../images/PBR\ body/PBR_body_268.png ./out/Assets/PBR/PBR_body_268.png
cp ../images/PBR\ face/PBR_face_383.png ./out/Assets/PBR/PBR_face_383.png
cp ../images/PBR\ face/PBR_face_377.png ./out/Assets/PBR/PBR_face_377.png
cp ../images/PBR\ face/PBR_face_110.png ./out/Assets/PBR/PBR_face_110.png
cp ../images/PBR\ face/PBR_face_413.png ./out/Assets/PBR/PBR_face_413.png
cp ../images/PBR\ face/PBR_face_462.png ./out/Assets/PBR/PBR_face_462.png
cp ../images/PBR\ face/PBR_face_206.png ./out/Assets/PBR/PBR_face_206.png
cp ../images/PBR\ body/PBR_body_222.png ./out/Assets/PBR/PBR_body_222.png
cp ../images/PBR\ body/PBR_body_051.png ./out/Assets/PBR/PBR_body_051.png
cp ../images/PBR\ body/PBR_body_157.png ./out/Assets/PBR/PBR_body_157.png
cp ../images/PBR\ face/PBR_face_335.png ./out/Assets/PBR/PBR_face_335.png
cp ../images/PBR\ body/PBR_body_226.png ./out/Assets/PBR/PBR_body_226.png
cp ../images/PBR\ body/PBR_body_237.png ./out/Assets/PBR/PBR_body_237.png
cp ../images/PBR\ body/PBR_body_102.png ./out/Assets/PBR/PBR_body_102.png
cp ../images/PBR\ face/PBR_face_196.png ./out/Assets/PBR/PBR_face_196.png
cp ../images/PBR\ face/PBR_face_384.png ./out/Assets/PBR/PBR_face_384.png
cp ../images/PBR\ face/PBR_face_250.png ./out/Assets/PBR/PBR_face_250.png
cp ../images/PBR\ body/PBR_body_209.png ./out/Assets/PBR/PBR_body_209.png
cp ../images/PBR\ face/PBR_face_451.png ./out/Assets/PBR/PBR_face_451.png
cp ../JSON/PBR/Original\ Items.json ./out/Assets/PBR/Original\ Items.json
cp ../images/PBR\ body/PBR_body_397.png ./out/Assets/PBR/PBR_body_397.png
cp ../images/PBR\ body/PBR_body_279.png ./out/Assets/PBR/PBR_body_279.png
cp ../images/PBR\ face/PBR_face_308.png ./out/Assets/PBR/PBR_face_308.png
cp ../images/PBR\ body/PBR_body_286.png ./out/Assets/PBR/PBR_body_286.png
cp ../images/PBR\ face/PBR_face_337.png ./out/Assets/PBR/PBR_face_337.png
cp ../images/PBR\ face/PBR_face_017.png ./out/Assets/PBR/PBR_face_017.png
cp ../images/PBR\ face/PBR_face_439.png ./out/Assets/PBR/PBR_face_439.png
cp ../images/PBR\ face/PBR_face_218.png ./out/Assets/PBR/PBR_face_218.png
cp ../images/PBR\ body/PBR_body_295.png ./out/Assets/PBR/PBR_body_295.png
cp ../images/PBR\ face/PBR_face_240.png ./out/Assets/PBR/PBR_face_240.png
cp ../images/PBR\ body/PBR_body_358.png ./out/Assets/PBR/PBR_body_358.png
cp ../images/PBR\ face/PBR_face_349.png ./out/Assets/PBR/PBR_face_349.png
cp ../images/PBR\ body/PBR_body_189.png ./out/Assets/PBR/PBR_body_189.png
cp ../images/PBR\ body/PBR_body_211.png ./out/Assets/PBR/PBR_body_211.png
cp ../images/PBR\ face/PBR_face_370.png ./out/Assets/PBR/PBR_face_370.png
cp ../images/PBR\ body/PBR_body_418.png ./out/Assets/PBR/PBR_body_418.png
cp ../images/PBR\ body/PBR_body_312.png ./out/Assets/PBR/PBR_body_312.png
cp ../images/PBR\ face/PBR_face_368.png ./out/Assets/PBR/PBR_face_368.png
cp ../images/PBR\ body/PBR_body_401.png ./out/Assets/PBR/PBR_body_401.png
cp ../JSON/PBR/Original\ Pokemon.json ./out/Assets/PBR/Original\ Pokemon.json
cp ../images/PBR\ body/PBR_body_192.png ./out/Assets/PBR/PBR_body_192.png
cp ../images/PBR\ body/PBR_body_480.png ./out/Assets/PBR/PBR_body_480.png
cp ../images/PBR\ face/PBR_face_268.png ./out/Assets/PBR/PBR_face_268.png
cp ../images/PBR\ face/PBR_face_273.png ./out/Assets/PBR/PBR_face_273.png
cp ../images/PBR\ body/PBR_body_202.png ./out/Assets/PBR/PBR_body_202.png
cp ../images/PBR\ face/PBR_face_494.png ./out/Assets/PBR/PBR_face_494.png
cp ../images/PokeBalls/ball\ purple.png ./out/Assets/PBR/ball\ purple.png
cp ../images/PBR\ face/PBR_face_258.png ./out/Assets/PBR/PBR_face_258.png
cp ../images/PBR\ face/PBR_face_079.png ./out/Assets/PBR/PBR_face_079.png
cp ../images/PBR\ face/PBR_face_030.png ./out/Assets/PBR/PBR_face_030.png
cp ../images/PBR\ face/PBR_face_164.png ./out/Assets/PBR/PBR_face_164.png
cp ../images/PBR\ face/PBR_face_291.png ./out/Assets/PBR/PBR_face_291.png
cp ../images/PBR\ body/PBR_body_146.png ./out/Assets/PBR/PBR_body_146.png
cp ../images/PBR\ face/PBR_face_315.png ./out/Assets/PBR/PBR_face_315.png
cp ../images/PBR\ face/PBR_face_167.png ./out/Assets/PBR/PBR_face_167.png
cp ../images/PBR\ body/PBR_body_119.png ./out/Assets/PBR/PBR_body_119.png
cp ../images/PBR\ body/PBR_body_139.png ./out/Assets/PBR/PBR_body_139.png
cp ../images/PBR\ face/PBR_face_279.png ./out/Assets/PBR/PBR_face_279.png
cp ../images/PBR\ body/PBR_body_392.png ./out/Assets/PBR/PBR_body_392.png
cp ../images/PBR\ body/PBR_body_023.png ./out/Assets/PBR/PBR_body_023.png
cp ../images/PBR\ body/PBR_body_350.png ./out/Assets/PBR/PBR_body_350.png
cp ../images/PBR\ face/PBR_face_229.png ./out/Assets/PBR/PBR_face_229.png
cp ../images/PBR\ body/PBR_body_258.png ./out/Assets/PBR/PBR_body_258.png
cp ../images/PBR\ face/PBR_face_147.png ./out/Assets/PBR/PBR_face_147.png
cp ../images/PBR\ face/PBR_face_410.png ./out/Assets/PBR/PBR_face_410.png
cp ../images/PBR\ body/PBR_body_459.png ./out/Assets/PBR/PBR_body_459.png
cp ../images/PBR\ body/PBR_body_319.png ./out/Assets/PBR/PBR_body_319.png
cp ../images/PBR\ body/PBR_body_071.png ./out/Assets/PBR/PBR_body_071.png
cp ../images/Types/type_5.png ./out/Assets/PBR/type_5.png
cp ../images/PBR\ face/PBR_face_270.png ./out/Assets/PBR/PBR_face_270.png
cp ../images/PBR\ face/PBR_face_197.png ./out/Assets/PBR/PBR_face_197.png
cp ../images/PBR\ face/PBR_face_088.png ./out/Assets/PBR/PBR_face_088.png
cp ../images/PBR\ body/PBR_body_430.png ./out/Assets/PBR/PBR_body_430.png
cp ../images/PBR\ body/PBR_body_296.png ./out/Assets/PBR/PBR_body_296.png
cp ../images/PBR\ face/PBR_face_481.png ./out/Assets/PBR/PBR_face_481.png
cp ../images/PBR\ face/PBR_face_280.png ./out/Assets/PBR/PBR_face_280.png
cp ../images/PBR\ body/PBR_body_103.png ./out/Assets/PBR/PBR_body_103.png
cp ../images/PBR\ body/PBR_body_055.png ./out/Assets/PBR/PBR_body_055.png
cp ../images/PBR\ face/PBR_face_278.png ./out/Assets/PBR/PBR_face_278.png
cp ../images/PBR\ body/PBR_body_300.png ./out/Assets/PBR/PBR_body_300.png
cp ../images/PBR\ face/PBR_face_382.png ./out/Assets/PBR/PBR_face_382.png
cp ../images/PBR\ body/PBR_body_299.png ./out/Assets/PBR/PBR_body_299.png
cp ../images/PBR\ face/PBR_face_409.png ./out/Assets/PBR/PBR_face_409.png
cp ../images/PBR\ body/PBR_body_298.png ./out/Assets/PBR/PBR_body_298.png
cp ../images/PBR\ face/PBR_face_134.png ./out/Assets/PBR/PBR_face_134.png
cp ../images/PBR\ face/PBR_face_406.png ./out/Assets/PBR/PBR_face_406.png
cp ../images/PBR\ body/PBR_body_288.png ./out/Assets/PBR/PBR_body_288.png
cp ../images/PBR\ face/PBR_face_281.png ./out/Assets/PBR/PBR_face_281.png
cp ../images/PBR\ body/PBR_body_215.png ./out/Assets/PBR/PBR_body_215.png
cp ../images/PBR\ face/PBR_face_251.png ./out/Assets/PBR/PBR_face_251.png
cp ../images/PBR\ face/PBR_face_312.png ./out/Assets/PBR/PBR_face_312.png
cp ../images/PBR\ face/PBR_face_014.png ./out/Assets/PBR/PBR_face_014.png
cp ../images/PBR\ face/PBR_face_354.png ./out/Assets/PBR/PBR_face_354.png
cp ../images/PBR\ face/PBR_face_189.png ./out/Assets/PBR/PBR_face_189.png
cp ../images/PBR\ face/PBR_face_305.png ./out/Assets/PBR/PBR_face_305.png
cp ../images/PBR\ face/PBR_face_324.png ./out/Assets/PBR/PBR_face_324.png
cp ../images/PBR\ body/PBR_body_231.png ./out/Assets/PBR/PBR_body_231.png
cp ../images/PBR\ face/PBR_face_225.png ./out/Assets/PBR/PBR_face_225.png
cp ../images/PBR\ face/PBR_face_429.png ./out/Assets/PBR/PBR_face_429.png
cp ../images/PBR\ body/PBR_body_116.png ./out/Assets/PBR/PBR_body_116.png
cp ../images/PBR\ body/PBR_body_448.png ./out/Assets/PBR/PBR_body_448.png
cp ../images/PBR\ body/PBR_body_362.png ./out/Assets/PBR/PBR_body_362.png
cp ../images/PBR\ body/PBR_body_174.png ./out/Assets/PBR/PBR_body_174.png
cp ../images/PBR\ body/PBR_body_067.png ./out/Assets/PBR/PBR_body_067.png
cp ../images/PBR\ body/PBR_body_291.png ./out/Assets/PBR/PBR_body_291.png
cp ../images/PBR\ body/PBR_body_432.png ./out/Assets/PBR/PBR_body_432.png
cp ../images/PBR\ face/PBR_face_436.png ./out/Assets/PBR/PBR_face_436.png
cp ../images/PBR\ body/PBR_body_199.png ./out/Assets/PBR/PBR_body_199.png
cp ../images/PBR\ body/PBR_body_467.png ./out/Assets/PBR/PBR_body_467.png
cp ../images/PBR\ face/PBR_face_345.png ./out/Assets/PBR/PBR_face_345.png
cp ../images/PBR\ body/PBR_body_225.png ./out/Assets/PBR/PBR_body_225.png
cp ../images/PBR\ face/PBR_face_145.png ./out/Assets/PBR/PBR_face_145.png
cp ../images/PBR\ body/PBR_body_310.png ./out/Assets/PBR/PBR_body_310.png
cp ../images/PBR\ face/PBR_face_059.png ./out/Assets/PBR/PBR_face_059.png
cp ../images/PBR\ face/PBR_face_024.png ./out/Assets/PBR/PBR_face_024.png
cp ../images/PBR\ body/PBR_body_245.png ./out/Assets/PBR/PBR_body_245.png
cp ../images/PBR\ body/PBR_body_460.png ./out/Assets/PBR/PBR_body_460.png
cp ../images/PBR\ body/PBR_body_075.png ./out/Assets/PBR/PBR_body_075.png
cp ../images/PBR\ face/PBR_face_080.png ./out/Assets/PBR/PBR_face_080.png
cp ../images/PBR\ body/PBR_body_320.png ./out/Assets/PBR/PBR_body_320.png
cp ../images/PBR\ face/PBR_face_415.png ./out/Assets/PBR/PBR_face_415.png
cp ../images/PBR\ face/PBR_face_235.png ./out/Assets/PBR/PBR_face_235.png
cp ../images/PBR\ body/PBR_body_260.png ./out/Assets/PBR/PBR_body_260.png
cp ../images/PBR\ body/PBR_body_337.png ./out/Assets/PBR/PBR_body_337.png
cp ../images/PBR\ face/PBR_face_202.png ./out/Assets/PBR/PBR_face_202.png
cp ../images/PBR\ face/PBR_face_367.png ./out/Assets/PBR/PBR_face_367.png
cp ../images/PBR\ face/PBR_face_148.png ./out/Assets/PBR/PBR_face_148.png
cp ../images/PBR\ body/PBR_body_004.png ./out/Assets/PBR/PBR_body_004.png
cp ../images/PBR\ face/PBR_face_057.png ./out/Assets/PBR/PBR_face_057.png
cp ../images/PBR\ body/PBR_body_150.png ./out/Assets/PBR/PBR_body_150.png
cp ../images/PBR\ face/PBR_face_341.png ./out/Assets/PBR/PBR_face_341.png
cp ../images/PBR\ face/PBR_face_423.png ./out/Assets/PBR/PBR_face_423.png
cp ../images/PBR\ face/PBR_face_232.png ./out/Assets/PBR/PBR_face_232.png
cp ../images/PBR\ face/PBR_face_331.png ./out/Assets/PBR/PBR_face_331.png
cp ../images/PBR\ body/PBR_body_108.png ./out/Assets/PBR/PBR_body_108.png
cp ../images/PBR\ face/PBR_face_002.png ./out/Assets/PBR/PBR_face_002.png
cp ../images/PBR\ face/PBR_face_019.png ./out/Assets/PBR/PBR_face_019.png
cp ../images/PBR\ body/PBR_body_218.png ./out/Assets/PBR/PBR_body_218.png
cp ../images/PBR\ face/PBR_face_152.png ./out/Assets/PBR/PBR_face_152.png
cp ../images/PBR\ face/PBR_face_118.png ./out/Assets/PBR/PBR_face_118.png
cp ../images/PBR\ body/PBR_body_190.png ./out/Assets/PBR/PBR_body_190.png
cp ../images/PBR\ body/PBR_body_283.png ./out/Assets/PBR/PBR_body_283.png
cp ../images/PBR\ body/PBR_body_205.png ./out/Assets/PBR/PBR_body_205.png
cp ../images/PBR\ body/PBR_body_216.png ./out/Assets/PBR/PBR_body_216.png
cp ../images/PBR\ body/PBR_body_353.png ./out/Assets/PBR/PBR_body_353.png
cp ../images/PBR\ body/PBR_body_062.png ./out/Assets/PBR/PBR_body_062.png
cp ../images/PBR\ face/PBR_face_452.png ./out/Assets/PBR/PBR_face_452.png
cp ../images/PBR\ face/PBR_face_066.png ./out/Assets/PBR/PBR_face_066.png
cp ../images/PBR\ face/PBR_face_061.png ./out/Assets/PBR/PBR_face_061.png
cp ../images/PBR\ face/PBR_face_477.png ./out/Assets/PBR/PBR_face_477.png
cp ../images/PBR\ body/PBR_body_325.png ./out/Assets/PBR/PBR_body_325.png
cp ../images/PBR\ face/PBR_face_230.png ./out/Assets/PBR/PBR_face_230.png
cp ../images/PBR\ face/PBR_face_157.png ./out/Assets/PBR/PBR_face_157.png
cp ../images/PBR\ face/PBR_face_458.png ./out/Assets/PBR/PBR_face_458.png
cp ../JSON/PBR/Move\ Effects.json ./out/Assets/PBR/Move\ Effects.json
cp ../images/PBR\ body/PBR_body_045.png ./out/Assets/PBR/PBR_body_045.png
cp ../images/PBR\ face/PBR_face_356.png ./out/Assets/PBR/PBR_face_356.png
cp ../images/PBR\ face/PBR_face_124.png ./out/Assets/PBR/PBR_face_124.png
cp ../images/PBR\ body/PBR_body_393.png ./out/Assets/PBR/PBR_body_393.png
cp ../images/PBR\ body/PBR_body_091.png ./out/Assets/PBR/PBR_body_091.png
cp ../images/PBR\ body/PBR_body_169.png ./out/Assets/PBR/PBR_body_169.png
cp ../images/PBR\ face/PBR_face_163.png ./out/Assets/PBR/PBR_face_163.png
cp ../images/PBR\ face/PBR_face_271.png ./out/Assets/PBR/PBR_face_271.png
cp ../images/PBR\ face/PBR_face_259.png ./out/Assets/PBR/PBR_face_259.png
cp ../images/PBR\ face/PBR_face_449.png ./out/Assets/PBR/PBR_face_449.png
cp ../images/PBR\ face/PBR_face_041.png ./out/Assets/PBR/PBR_face_041.png
cp ../images/PBR\ body/PBR_body_048.png ./out/Assets/PBR/PBR_body_048.png
cp ../images/PBR\ body/PBR_body_406.png ./out/Assets/PBR/PBR_body_406.png
cp ../images/PBR\ face/PBR_face_363.png ./out/Assets/PBR/PBR_face_363.png
cp ../images/PBR\ body/PBR_body_070.png ./out/Assets/PBR/PBR_body_070.png
cp ../images/PBR\ face/PBR_face_209.png ./out/Assets/PBR/PBR_face_209.png
cp ../images/PBR\ body/PBR_body_434.png ./out/Assets/PBR/PBR_body_434.png
cp ../images/PBR\ body/PBR_body_427.png ./out/Assets/PBR/PBR_body_427.png
cp ../images/PBR\ body/PBR_body_262.png ./out/Assets/PBR/PBR_body_262.png
cp ../images/PBR\ face/PBR_face_466.png ./out/Assets/PBR/PBR_face_466.png
cp ../images/PBR\ body/PBR_body_464.png ./out/Assets/PBR/PBR_body_464.png
cp ../images/PBR\ body/PBR_body_461.png ./out/Assets/PBR/PBR_body_461.png
cp ../images/PBR\ body/PBR_body_016.png ./out/Assets/PBR/PBR_body_016.png
cp ../images/PBR\ face/PBR_face_055.png ./out/Assets/PBR/PBR_face_055.png
cp ../images/PBR\ face/PBR_face_393.png ./out/Assets/PBR/PBR_face_393.png
cp ../images/PBR\ body/PBR_body_499.png ./out/Assets/PBR/PBR_body_499.png
cp ../images/PBR\ body/PBR_body_357.png ./out/Assets/PBR/PBR_body_357.png
cp ../images/PBR\ body/PBR_body_018.png ./out/Assets/PBR/PBR_body_018.png
cp ../images/PBR\ body/PBR_body_304.png ./out/Assets/PBR/PBR_body_304.png
cp ../images/PBR\ body/PBR_body_255.png ./out/Assets/PBR/PBR_body_255.png
cp ../images/PBR\ body/PBR_body_302.png ./out/Assets/PBR/PBR_body_302.png
cp ../images/PBR\ face/PBR_face_472.png ./out/Assets/PBR/PBR_face_472.png
cp ../images/PBR\ face/PBR_face_018.png ./out/Assets/PBR/PBR_face_018.png
cp ../images/PBR\ face/PBR_face_201.png ./out/Assets/PBR/PBR_face_201.png
cp ../images/PBR\ face/PBR_face_396.png ./out/Assets/PBR/PBR_face_396.png
cp ../images/PBR\ face/PBR_face_417.png ./out/Assets/PBR/PBR_face_417.png
cp ../images/PBR\ face/PBR_face_405.png ./out/Assets/PBR/PBR_face_405.png
cp ../images/PBR\ body/PBR_body_206.png ./out/Assets/PBR/PBR_body_206.png
cp ../images/PBR\ body/PBR_body_479.png ./out/Assets/PBR/PBR_body_479.png
cp ../images/PBR\ body/PBR_body_458.png ./out/Assets/PBR/PBR_body_458.png
cp ../images/PBR\ face/PBR_face_056.png ./out/Assets/PBR/PBR_face_056.png
cp ../images/PBR\ body/PBR_body_402.png ./out/Assets/PBR/PBR_body_402.png
cp ../images/PBR\ face/PBR_face_083.png ./out/Assets/PBR/PBR_face_083.png
cp ../images/PBR\ body/PBR_body_421.png ./out/Assets/PBR/PBR_body_421.png
cp ../images/PBR\ body/PBR_body_285.png ./out/Assets/PBR/PBR_body_285.png
cp ../images/PBR\ face/PBR_face_085.png ./out/Assets/PBR/PBR_face_085.png
cp ../images/PBR\ body/PBR_body_289.png ./out/Assets/PBR/PBR_body_289.png
cp ../images/PBR\ body/PBR_body_263.png ./out/Assets/PBR/PBR_body_263.png
cp ../images/PBR\ body/PBR_body_007.png ./out/Assets/PBR/PBR_body_007.png
cp ../images/PBR\ face/PBR_face_493.png ./out/Assets/PBR/PBR_face_493.png
cp ../images/PBR\ body/PBR_body_330.png ./out/Assets/PBR/PBR_body_330.png
cp ../images/PBR\ face/PBR_face_204.png ./out/Assets/PBR/PBR_face_204.png
cp ../images/PBR\ body/PBR_body_028.png ./out/Assets/PBR/PBR_body_028.png
cp ../images/PBR\ body/PBR_body_324.png ./out/Assets/PBR/PBR_body_324.png
cp ../images/PBR\ face/PBR_face_387.png ./out/Assets/PBR/PBR_face_387.png
cp ../images/PBR\ body/PBR_body_494.png ./out/Assets/PBR/PBR_body_494.png
cp ../images/PBR\ body/PBR_body_093.png ./out/Assets/PBR/PBR_body_093.png
cp ../images/PBR\ body/PBR_body_425.png ./out/Assets/PBR/PBR_body_425.png
cp ../images/PBR\ face/PBR_face_184.png ./out/Assets/PBR/PBR_face_184.png
cp ../images/PBR\ body/PBR_body_294.png ./out/Assets/PBR/PBR_body_294.png
cp ../images/PBR\ body/PBR_body_447.png ./out/Assets/PBR/PBR_body_447.png
cp ../images/PBR\ face/PBR_face_108.png ./out/Assets/PBR/PBR_face_108.png
cp ../images/PBR\ body/PBR_body_443.png ./out/Assets/PBR/PBR_body_443.png
cp ../images/PBR\ body/PBR_body_234.png ./out/Assets/PBR/PBR_body_234.png
cp ../images/PBR\ face/PBR_face_386.png ./out/Assets/PBR/PBR_face_386.png
cp ../images/PBR\ body/PBR_body_198.png ./out/Assets/PBR/PBR_body_198.png
cp ../images/PBR\ face/PBR_face_199.png ./out/Assets/PBR/PBR_face_199.png
cp ../images/PBR\ face/PBR_face_444.png ./out/Assets/PBR/PBR_face_444.png
cp ../images/PBR\ face/PBR_face_283.png ./out/Assets/PBR/PBR_face_283.png
cp ../images/PBR\ body/PBR_body_272.png ./out/Assets/PBR/PBR_body_272.png
cp ../images/PBR\ body/PBR_body_352.png ./out/Assets/PBR/PBR_body_352.png
cp ../images/PBR\ face/PBR_face_475.png ./out/Assets/PBR/PBR_face_475.png
cp ../images/PBR\ body/PBR_body_344.png ./out/Assets/PBR/PBR_body_344.png
cp ../images/PBR\ body/PBR_body_114.png ./out/Assets/PBR/PBR_body_114.png
cp ../images/PBR\ body/PBR_body_348.png ./out/Assets/PBR/PBR_body_348.png
cp ../images/PBR\ face/PBR_face_221.png ./out/Assets/PBR/PBR_face_221.png
cp ../images/PBR\ body/PBR_body_065.png ./out/Assets/PBR/PBR_body_065.png
cp ../images/PBR\ face/PBR_face_159.png ./out/Assets/PBR/PBR_face_159.png
cp ../images/PBR\ body/PBR_body_068.png ./out/Assets/PBR/PBR_body_068.png
cp ../images/PBR\ body/PBR_body_338.png ./out/Assets/PBR/PBR_body_338.png
cp ../images/PBR\ face/PBR_face_172.png ./out/Assets/PBR/PBR_face_172.png
cp ../images/PBR\ body/PBR_body_024.png ./out/Assets/PBR/PBR_body_024.png
cp ../images/PBR\ face/PBR_face_498.png ./out/Assets/PBR/PBR_face_498.png
cp ../images/PBR\ face/PBR_face_388.png ./out/Assets/PBR/PBR_face_388.png
cp ../images/PBR\ face/PBR_face_039.png ./out/Assets/PBR/PBR_face_039.png
cp ../images/PBR\ face/PBR_face_379.png ./out/Assets/PBR/PBR_face_379.png
cp ../images/PBR\ body/PBR_body_414.png ./out/Assets/PBR/PBR_body_414.png
cp ../images/Table\ View\ Cells/Selected\ Cell.png ./out/Assets/PBR/Selected\ Cell.png
cp ../images/PBR\ face/PBR_face_003.png ./out/Assets/PBR/PBR_face_003.png
cp ../images/PBR\ body/PBR_body_369.png ./out/Assets/PBR/PBR_body_369.png
cp ../images/PBR\ face/PBR_face_421.png ./out/Assets/PBR/PBR_face_421.png
cp ../images/PBR\ face/PBR_face_351.png ./out/Assets/PBR/PBR_face_351.png
cp ../images/PBR\ body/PBR_body_303.png ./out/Assets/PBR/PBR_body_303.png
cp ../images/PBR\ face/PBR_face_346.png ./out/Assets/PBR/PBR_face_346.png
cp ../images/PBR\ face/PBR_face_432.png ./out/Assets/PBR/PBR_face_432.png
cp ../images/PBR\ body/PBR_body_454.png ./out/Assets/PBR/PBR_body_454.png
cp ../images/PBR\ face/PBR_face_302.png ./out/Assets/PBR/PBR_face_302.png
cp ../images/PBR\ body/PBR_body_409.png ./out/Assets/PBR/PBR_body_409.png
cp ../images/PBR\ face/PBR_face_252.png ./out/Assets/PBR/PBR_face_252.png
cp ../images/PBR\ face/PBR_face_141.png ./out/Assets/PBR/PBR_face_141.png
cp ../images/PBR\ face/PBR_face_469.png ./out/Assets/PBR/PBR_face_469.png
cp ../images/PBR\ body/PBR_body_407.png ./out/Assets/PBR/PBR_body_407.png
cp ../images/PBR\ face/PBR_face_276.png ./out/Assets/PBR/PBR_face_276.png
cp ../images/PBR\ body/PBR_body_275.png ./out/Assets/PBR/PBR_body_275.png
cp ../images/PBR\ face/PBR_face_248.png ./out/Assets/PBR/PBR_face_248.png
cp ../images/PBR\ face/PBR_face_434.png ./out/Assets/PBR/PBR_face_434.png
cp ../images/PBR\ face/PBR_face_009.png ./out/Assets/PBR/PBR_face_009.png
cp ../images/PBR\ face/PBR_face_160.png ./out/Assets/PBR/PBR_face_160.png
cp ../images/PBR\ body/PBR_body_166.png ./out/Assets/PBR/PBR_body_166.png
cp ../images/PBR\ body/PBR_body_470.png ./out/Assets/PBR/PBR_body_470.png
cp ../images/PBR\ body/PBR_body_224.png ./out/Assets/PBR/PBR_body_224.png
cp ../images/PBR\ body/PBR_body_193.png ./out/Assets/PBR/PBR_body_193.png
cp ../images/PBR\ body/PBR_body_084.png ./out/Assets/PBR/PBR_body_084.png
cp ../images/PBR\ body/PBR_body_413.png ./out/Assets/PBR/PBR_body_413.png
cp ../images/Types/type_4.png ./out/Assets/PBR/type_4.png
cp ../images/PBR\ face/PBR_face_169.png ./out/Assets/PBR/PBR_face_169.png
cp ../images/PBR\ face/PBR_face_223.png ./out/Assets/PBR/PBR_face_223.png
cp ../images/PBR\ body/PBR_body_085.png ./out/Assets/PBR/PBR_body_085.png
cp ../images/PBR\ body/PBR_body_381.png ./out/Assets/PBR/PBR_body_381.png
cp ../images/PBR\ body/PBR_body_354.png ./out/Assets/PBR/PBR_body_354.png
cp ../images/PBR\ body/PBR_body_141.png ./out/Assets/PBR/PBR_body_141.png
cp ../images/PBR\ body/PBR_body_493.png ./out/Assets/PBR/PBR_body_493.png
cp ../images/PBR\ body/PBR_body_123.png ./out/Assets/PBR/PBR_body_123.png
cp ../images/PBR\ face/PBR_face_075.png ./out/Assets/PBR/PBR_face_075.png
cp ../images/PBR\ face/PBR_face_122.png ./out/Assets/PBR/PBR_face_122.png
cp ../images/PBR\ face/PBR_face_338.png ./out/Assets/PBR/PBR_face_338.png
cp ../images/PBR\ face/PBR_face_333.png ./out/Assets/PBR/PBR_face_333.png
cp ../images/PBR\ body/PBR_body_097.png ./out/Assets/PBR/PBR_body_097.png
cp ../images/PBR\ body/PBR_body_335.png ./out/Assets/PBR/PBR_body_335.png
cp ../images/PBR\ face/PBR_face_297.png ./out/Assets/PBR/PBR_face_297.png
cp ../images/PBR\ body/PBR_body_297.png ./out/Assets/PBR/PBR_body_297.png
cp ../images/PBR\ face/PBR_face_001.png ./out/Assets/PBR/PBR_face_001.png
cp ../images/PBR\ body/PBR_body_030.png ./out/Assets/PBR/PBR_body_030.png
cp ../images/PBR\ body/PBR_body_451.png ./out/Assets/PBR/PBR_body_451.png
cp ../images/PBR\ face/PBR_face_489.png ./out/Assets/PBR/PBR_face_489.png
cp ../images/PBR\ face/PBR_face_021.png ./out/Assets/PBR/PBR_face_021.png
cp ../images/PBR\ body/PBR_body_287.png ./out/Assets/PBR/PBR_body_287.png
cp ../images/Types/type_10.png ./out/Assets/PBR/type_10.png
cp ../images/PBR\ face/PBR_face_123.png ./out/Assets/PBR/PBR_face_123.png
cp ../images/PBR\ face/PBR_face_249.png ./out/Assets/PBR/PBR_face_249.png
cp ../images/PBR\ face/PBR_face_425.png ./out/Assets/PBR/PBR_face_425.png
cp ../images/Types/type_13.png ./out/Assets/PBR/type_13.png
cp ../images/Types/type_17.png ./out/Assets/PBR/type_17.png
cp ../images/PBR\ face/PBR_face_093.png ./out/Assets/PBR/PBR_face_093.png
cp ../images/PBR\ body/PBR_body_315.png ./out/Assets/PBR/PBR_body_315.png
cp ../images/PBR\ face/PBR_face_031.png ./out/Assets/PBR/PBR_face_031.png
cp ../images/PBR\ body/PBR_body_437.png ./out/Assets/PBR/PBR_body_437.png
cp ../images/Types/type_9.png ./out/Assets/PBR/type_9.png
cp ../images/PBR\ face/PBR_face_465.png ./out/Assets/PBR/PBR_face_465.png
cp ../images/PBR\ face/PBR_face_036.png ./out/Assets/PBR/PBR_face_036.png
cp ../images/PBR\ face/PBR_face_228.png ./out/Assets/PBR/PBR_face_228.png
cp ../images/PBR\ body/PBR_body_489.png ./out/Assets/PBR/PBR_body_489.png
cp ../images/PBR\ body/PBR_body_200.png ./out/Assets/PBR/PBR_body_200.png
cp ../images/PBR\ body/PBR_body_010.png ./out/Assets/PBR/PBR_body_010.png
cp ../images/PBR\ body/PBR_body_476.png ./out/Assets/PBR/PBR_body_476.png
cp ../images/PBR\ face/PBR_face_360.png ./out/Assets/PBR/PBR_face_360.png
cp ../images/PBR\ face/PBR_face_086.png ./out/Assets/PBR/PBR_face_086.png
cp ../images/PBR\ body/PBR_body_187.png ./out/Assets/PBR/PBR_body_187.png
cp ../images/PBR\ face/PBR_face_399.png ./out/Assets/PBR/PBR_face_399.png
cp ../images/PBR\ body/PBR_body_376.png ./out/Assets/PBR/PBR_body_376.png
cp ../images/PBR\ face/PBR_face_403.png ./out/Assets/PBR/PBR_face_403.png
cp ../images/PBR\ face/PBR_face_092.png ./out/Assets/PBR/PBR_face_092.png
cp ../images/PBR\ face/PBR_face_459.png ./out/Assets/PBR/PBR_face_459.png
cp ../images/PBR\ face/PBR_face_205.png ./out/Assets/PBR/PBR_face_205.png
cp ../images/PBR\ body/PBR_body_001.png ./out/Assets/PBR/PBR_body_001.png
cp ../images/PBR\ face/PBR_face_292.png ./out/Assets/PBR/PBR_face_292.png
cp ../images/PBR\ face/PBR_face_352.png ./out/Assets/PBR/PBR_face_352.png
cp ../images/PBR\ body/PBR_body_079.png ./out/Assets/PBR/PBR_body_079.png
cp ../images/PBR\ body/PBR_body_229.png ./out/Assets/PBR/PBR_body_229.png
cp ../images/PBR\ body/PBR_body_382.png ./out/Assets/PBR/PBR_body_382.png
cp ../images/PBR\ body/PBR_body_359.png ./out/Assets/PBR/PBR_body_359.png
cp ../images/PBR\ body/PBR_body_176.png ./out/Assets/PBR/PBR_body_176.png
cp ../images/PBR\ face/PBR_face_455.png ./out/Assets/PBR/PBR_face_455.png
cp ../images/PBR\ face/PBR_face_496.png ./out/Assets/PBR/PBR_face_496.png
cp ../images/PBR\ body/PBR_body_197.png ./out/Assets/PBR/PBR_body_197.png
cp ../images/PBR\ face/PBR_face_023.png ./out/Assets/PBR/PBR_face_023.png
cp ../images/PBR\ body/PBR_body_404.png ./out/Assets/PBR/PBR_body_404.png
cp ../images/PBR\ face/PBR_face_100.png ./out/Assets/PBR/PBR_face_100.png
cp ../images/PBR\ face/PBR_face_207.png ./out/Assets/PBR/PBR_face_207.png
cp ../images/PBR\ face/PBR_face_310.png ./out/Assets/PBR/PBR_face_310.png
cp ../images/PBR\ body/PBR_body_078.png ./out/Assets/PBR/PBR_body_078.png
cp ../images/PBR\ body/PBR_body_107.png ./out/Assets/PBR/PBR_body_107.png
cp ../images/PBR\ body/PBR_body_394.png ./out/Assets/PBR/PBR_body_394.png
cp ../images/PBR\ body/PBR_body_121.png ./out/Assets/PBR/PBR_body_121.png
cp ../images/PBR\ face/PBR_face_426.png ./out/Assets/PBR/PBR_face_426.png
cp ../images/PBR\ face/PBR_face_181.png ./out/Assets/PBR/PBR_face_181.png
cp ../images/PBR\ body/PBR_body_370.png ./out/Assets/PBR/PBR_body_370.png
cp ../images/PBR\ face/PBR_face_102.png ./out/Assets/PBR/PBR_face_102.png
cp ../images/PBR\ face/PBR_face_339.png ./out/Assets/PBR/PBR_face_339.png
cp ../images/PBR\ body/PBR_body_477.png ./out/Assets/PBR/PBR_body_477.png
cp ../images/PBR\ body/PBR_body_439.png ./out/Assets/PBR/PBR_body_439.png
cp ../images/PBR\ face/PBR_face_289.png ./out/Assets/PBR/PBR_face_289.png
cp ../images/PBR\ face/PBR_face_062.png ./out/Assets/PBR/PBR_face_062.png
cp ../images/PBR\ body/PBR_body_313.png ./out/Assets/PBR/PBR_body_313.png
cp ../images/PBR\ body/PBR_body_345.png ./out/Assets/PBR/PBR_body_345.png
cp ../images/PBR\ body/PBR_body_236.png ./out/Assets/PBR/PBR_body_236.png
cp ../images/PBR\ body/PBR_body_399.png ./out/Assets/PBR/PBR_body_399.png
cp ../images/Types/type_12.png ./out/Assets/PBR/type_12.png
cp ../images/PBR\ body/PBR_body_076.png ./out/Assets/PBR/PBR_body_076.png
cp ../images/PBR\ face/PBR_face_404.png ./out/Assets/PBR/PBR_face_404.png
cp ../images/PBR\ face/PBR_face_394.png ./out/Assets/PBR/PBR_face_394.png
cp ../images/PBR\ face/PBR_face_208.png ./out/Assets/PBR/PBR_face_208.png
cp ../images/PBR\ body/PBR_body_014.png ./out/Assets/PBR/PBR_body_014.png
cp ../images/PBR\ body/PBR_body_090.png ./out/Assets/PBR/PBR_body_090.png
cp ../images/PBR\ face/PBR_face_094.png ./out/Assets/PBR/PBR_face_094.png
cp ../images/PBR\ face/PBR_face_175.png ./out/Assets/PBR/PBR_face_175.png
cp ../images/PBR\ body/PBR_body_210.png ./out/Assets/PBR/PBR_body_210.png
cp ../images/PBR\ face/PBR_face_435.png ./out/Assets/PBR/PBR_face_435.png
cp ../images/PBR\ face/PBR_face_013.png ./out/Assets/PBR/PBR_face_013.png
cp ../images/PBR\ body/PBR_body_363.png ./out/Assets/PBR/PBR_body_363.png
cp ../images/PBR\ body/PBR_body_194.png ./out/Assets/PBR/PBR_body_194.png
cp ../images/PBR\ face/PBR_face_303.png ./out/Assets/PBR/PBR_face_303.png
cp ../images/PBR\ face/PBR_face_162.png ./out/Assets/PBR/PBR_face_162.png
cp ../images/PBR\ face/PBR_face_067.png ./out/Assets/PBR/PBR_face_067.png
cp ../images/PBR\ body/PBR_body_491.png ./out/Assets/PBR/PBR_body_491.png
cp ../images/PBR\ body/PBR_body_180.png ./out/Assets/PBR/PBR_body_180.png
cp ../images/PBR\ face/PBR_face_099.png ./out/Assets/PBR/PBR_face_099.png
cp ../images/PBR\ face/PBR_face_486.png ./out/Assets/PBR/PBR_face_486.png
cp ../images/PBR\ face/PBR_face_236.png ./out/Assets/PBR/PBR_face_236.png
cp ../images/PBR\ body/PBR_body_019.png ./out/Assets/PBR/PBR_body_019.png
cp ../images/PBR\ body/PBR_body_422.png ./out/Assets/PBR/PBR_body_422.png
cp ../images/PBR\ face/PBR_face_254.png ./out/Assets/PBR/PBR_face_254.png
cp ../images/PBR\ body/PBR_body_112.png ./out/Assets/PBR/PBR_body_112.png
cp ../images/PBR\ body/PBR_body_178.png ./out/Assets/PBR/PBR_body_178.png
cp ../images/PBR\ face/PBR_face_344.png ./out/Assets/PBR/PBR_face_344.png
cp ../images/PBR\ face/PBR_face_154.png ./out/Assets/PBR/PBR_face_154.png
cp ../images/PBR\ body/PBR_body_492.png ./out/Assets/PBR/PBR_body_492.png
cp ../images/PBR\ body/PBR_body_170.png ./out/Assets/PBR/PBR_body_170.png
cp ../images/PBR\ face/PBR_face_198.png ./out/Assets/PBR/PBR_face_198.png
cp ../images/PBR\ face/PBR_face_220.png ./out/Assets/PBR/PBR_face_220.png
cp ../images/PBR\ body/PBR_body_203.png ./out/Assets/PBR/PBR_body_203.png
cp ../images/PBR\ face/PBR_face_106.png ./out/Assets/PBR/PBR_face_106.png
cp ../images/PBR\ face/PBR_face_433.png ./out/Assets/PBR/PBR_face_433.png
cp ../images/PBR\ face/PBR_face_247.png ./out/Assets/PBR/PBR_face_247.png
cp ../images/PBR\ body/PBR_body_488.png ./out/Assets/PBR/PBR_body_488.png
cp ../images/PBR\ face/PBR_face_295.png ./out/Assets/PBR/PBR_face_295.png
cp ../images/Types/type_6.png ./out/Assets/PBR/type_6.png
cp ../images/PBR\ body/PBR_body_317.png ./out/Assets/PBR/PBR_body_317.png
cp ../images/PBR\ body/PBR_body_015.png ./out/Assets/PBR/PBR_body_015.png
cp ../images/PBR\ face/PBR_face_004.png ./out/Assets/PBR/PBR_face_004.png
cp ../images/PBR\ face/PBR_face_029.png ./out/Assets/PBR/PBR_face_029.png
cp ../images/PBR\ face/PBR_face_045.png ./out/Assets/PBR/PBR_face_045.png
cp ../images/PBR\ face/PBR_face_166.png ./out/Assets/PBR/PBR_face_166.png
cp ../images/PBR\ body/PBR_body_158.png ./out/Assets/PBR/PBR_body_158.png
cp ../images/PBR\ body/PBR_body_321.png ./out/Assets/PBR/PBR_body_321.png
cp ../images/PBR\ face/PBR_face_416.png ./out/Assets/PBR/PBR_face_416.png
cp ../images/PBR\ body/PBR_body_265.png ./out/Assets/PBR/PBR_body_265.png
cp ../images/PBR\ face/PBR_face_492.png ./out/Assets/PBR/PBR_face_492.png
cp ../images/PBR\ body/PBR_body_012.png ./out/Assets/PBR/PBR_body_012.png
cp ../images/PBR\ body/PBR_body_316.png ./out/Assets/PBR/PBR_body_316.png
cp ../images/PBR\ face/PBR_face_071.png ./out/Assets/PBR/PBR_face_071.png
cp ../images/PBR\ face/PBR_face_307.png ./out/Assets/PBR/PBR_face_307.png
cp ../images/PBR\ body/PBR_body_081.png ./out/Assets/PBR/PBR_body_081.png
cp ../images/PBR\ face/PBR_face_358.png ./out/Assets/PBR/PBR_face_358.png
cp ../images/PBR\ face/PBR_face_479.png ./out/Assets/PBR/PBR_face_479.png
cp ../images/PBR\ face/PBR_face_138.png ./out/Assets/PBR/PBR_face_138.png
cp ../images/PBR\ body/PBR_body_147.png ./out/Assets/PBR/PBR_body_147.png
cp ../images/PBR\ face/PBR_face_195.png ./out/Assets/PBR/PBR_face_195.png
cp ../images/PBR\ face/PBR_face_437.png ./out/Assets/PBR/PBR_face_437.png
cp ../images/PBR\ face/PBR_face_332.png ./out/Assets/PBR/PBR_face_332.png
cp ../images/PBR\ face/PBR_face_304.png ./out/Assets/PBR/PBR_face_304.png
cp ../images/PBR\ body/PBR_body_134.png ./out/Assets/PBR/PBR_body_134.png
cp ../images/PBR\ body/PBR_body_037.png ./out/Assets/PBR/PBR_body_037.png
cp ../images/PBR\ face/PBR_face_136.png ./out/Assets/PBR/PBR_face_136.png
cp ../images/PBR\ body/PBR_body_173.png ./out/Assets/PBR/PBR_body_173.png
cp ../images/PBR\ body/PBR_body_057.png ./out/Assets/PBR/PBR_body_057.png
cp ../images/PBR\ body/PBR_body_092.png ./out/Assets/PBR/PBR_body_092.png
cp ../images/PBR\ body/PBR_body_219.png ./out/Assets/PBR/PBR_body_219.png
cp ../images/PBR\ face/PBR_face_168.png ./out/Assets/PBR/PBR_face_168.png
cp ../images/PBR\ face/PBR_face_074.png ./out/Assets/PBR/PBR_face_074.png
cp ../images/PBR\ face/PBR_face_450.png ./out/Assets/PBR/PBR_face_450.png
cp ../images/PBR\ body/PBR_body_390.png ./out/Assets/PBR/PBR_body_390.png
cp ../images/PokeBalls/ball\ grey.png ./out/Assets/PBR/ball\ grey.png
cp ../images/PBR\ body/PBR_body_228.png ./out/Assets/PBR/PBR_body_228.png
cp ../images/PBR\ face/PBR_face_144.png ./out/Assets/PBR/PBR_face_144.png
cp ../images/PBR\ body/PBR_body_207.png ./out/Assets/PBR/PBR_body_207.png
cp ../images/PBR\ body/PBR_body_412.png ./out/Assets/PBR/PBR_body_412.png
cp ../images/PBR\ face/PBR_face_054.png ./out/Assets/PBR/PBR_face_054.png
cp ../images/PBR\ face/PBR_face_082.png ./out/Assets/PBR/PBR_face_082.png
cp ../images/PBR\ body/PBR_body_143.png ./out/Assets/PBR/PBR_body_143.png
cp ../images/PBR\ body/PBR_body_322.png ./out/Assets/PBR/PBR_body_322.png
cp ../images/PBR\ body/PBR_body_361.png ./out/Assets/PBR/PBR_body_361.png
cp ../images/PBR\ face/PBR_face_091.png ./out/Assets/PBR/PBR_face_091.png
cp ../images/PBR\ face/PBR_face_365.png ./out/Assets/PBR/PBR_face_365.png
cp ../images/PBR\ face/PBR_face_371.png ./out/Assets/PBR/PBR_face_371.png
cp ../images/Table\ View\ Cells/Item\ Cell.png ./out/Assets/PBR/Item\ Cell.png
cp ../images/PBR\ body/PBR_body_036.png ./out/Assets/PBR/PBR_body_036.png
cp ../images/PBR\ body/PBR_body_026.png ./out/Assets/PBR/PBR_body_026.png
cp ../images/PBR\ body/PBR_body_125.png ./out/Assets/PBR/PBR_body_125.png
cp ../images/PBR\ body/PBR_body_042.png ./out/Assets/PBR/PBR_body_042.png
cp ../images/PBR\ face/PBR_face_063.png ./out/Assets/PBR/PBR_face_063.png
cp ../images/PBR\ body/PBR_body_073.png ./out/Assets/PBR/PBR_body_073.png
cp ../images/PBR\ face/PBR_face_411.png ./out/Assets/PBR/PBR_face_411.png
cp ../images/PBR\ face/PBR_face_408.png ./out/Assets/PBR/PBR_face_408.png
cp ../images/PBR\ body/PBR_body_137.png ./out/Assets/PBR/PBR_body_137.png
cp ../images/PBR\ body/PBR_body_498.png ./out/Assets/PBR/PBR_body_498.png
cp ../images/PBR\ face/PBR_face_470.png ./out/Assets/PBR/PBR_face_470.png
cp ../images/PBR\ face/PBR_face_050.png ./out/Assets/PBR/PBR_face_050.png
cp ../images/PBR\ face/PBR_face_211.png ./out/Assets/PBR/PBR_face_211.png
cp ../images/PBR\ body/PBR_body_469.png ./out/Assets/PBR/PBR_body_469.png
cp ../images/PBR\ body/PBR_body_446.png ./out/Assets/PBR/PBR_body_446.png
cp ../images/PBR\ face/PBR_face_322.png ./out/Assets/PBR/PBR_face_322.png
cp ../images/PBR\ body/PBR_body_270.png ./out/Assets/PBR/PBR_body_270.png
cp ../images/PBR\ face/PBR_face_285.png ./out/Assets/PBR/PBR_face_285.png
cp ../images/PBR\ body/PBR_body_481.png ./out/Assets/PBR/PBR_body_481.png
cp ../images/PBR\ body/PBR_body_159.png ./out/Assets/PBR/PBR_body_159.png
cp ../images/Types/type_7.png ./out/Assets/PBR/type_7.png
cp ../images/Types/type_0.png ./out/Assets/PBR/type_0.png
cp ../images/PBR\ body/PBR_body_217.png ./out/Assets/PBR/PBR_body_217.png
cp ../images/PBR\ body/PBR_body_445.png ./out/Assets/PBR/PBR_body_445.png
cp ../images/PBR\ face/PBR_face_034.png ./out/Assets/PBR/PBR_face_034.png
cp ../images/PBR\ face/PBR_face_006.png ./out/Assets/PBR/PBR_face_006.png
cp ../images/PBR\ face/PBR_face_395.png ./out/Assets/PBR/PBR_face_395.png
cp ../images/PBR\ face/PBR_face_072.png ./out/Assets/PBR/PBR_face_072.png
cp ../images/PBR\ face/PBR_face_355.png ./out/Assets/PBR/PBR_face_355.png
cp ../images/PBR\ face/PBR_face_016.png ./out/Assets/PBR/PBR_face_016.png
cp ../images/PBR\ body/PBR_body_054.png ./out/Assets/PBR/PBR_body_054.png
cp ../images/PBR\ body/PBR_body_455.png ./out/Assets/PBR/PBR_body_455.png
cp ../images/PBR\ body/PBR_body_167.png ./out/Assets/PBR/PBR_body_167.png
cp ../images/PBR\ face/PBR_face_113.png ./out/Assets/PBR/PBR_face_113.png
cp ../images/PBR\ face/PBR_face_316.png ./out/Assets/PBR/PBR_face_316.png
cp ../images/PBR\ face/PBR_face_051.png ./out/Assets/PBR/PBR_face_051.png
cp ../images/PBR\ face/PBR_face_073.png ./out/Assets/PBR/PBR_face_073.png
cp ../images/PBR\ face/PBR_face_143.png ./out/Assets/PBR/PBR_face_143.png
cp ../images/PBR\ body/PBR_body_475.png ./out/Assets/PBR/PBR_body_475.png
cp ../images/PBR\ face/PBR_face_231.png ./out/Assets/PBR/PBR_face_231.png
cp ../images/PBR\ body/PBR_body_497.png ./out/Assets/PBR/PBR_body_497.png
cp ../images/PBR\ body/PBR_body_126.png ./out/Assets/PBR/PBR_body_126.png
cp ../images/PBR\ face/PBR_face_301.png ./out/Assets/PBR/PBR_face_301.png
cp ../images/PBR\ body/PBR_body_471.png ./out/Assets/PBR/PBR_body_471.png
cp ../images/PBR\ face/PBR_face_038.png ./out/Assets/PBR/PBR_face_038.png
cp ../images/PBR\ face/PBR_face_188.png ./out/Assets/PBR/PBR_face_188.png
cp ../images/PBR\ body/PBR_body_171.png ./out/Assets/PBR/PBR_body_171.png
cp ../images/PBR\ body/PBR_body_384.png ./out/Assets/PBR/PBR_body_384.png
cp ../images/PBR\ body/PBR_body_115.png ./out/Assets/PBR/PBR_body_115.png
cp ../images/PBR\ face/PBR_face_068.png ./out/Assets/PBR/PBR_face_068.png
cp ../images/PBR\ face/PBR_face_298.png ./out/Assets/PBR/PBR_face_298.png
cp ../images/PBR\ face/PBR_face_222.png ./out/Assets/PBR/PBR_face_222.png
cp ../images/PBR\ body/PBR_body_396.png ./out/Assets/PBR/PBR_body_396.png
cp ../images/PBR\ body/PBR_body_213.png ./out/Assets/PBR/PBR_body_213.png
cp ../images/PBR\ body/PBR_body_151.png ./out/Assets/PBR/PBR_body_151.png
cp ../images/PBR\ face/PBR_face_180.png ./out/Assets/PBR/PBR_face_180.png
cp ../images/PBR\ face/PBR_face_390.png ./out/Assets/PBR/PBR_face_390.png
cp ../images/PBR\ body/PBR_body_366.png ./out/Assets/PBR/PBR_body_366.png
cp ../images/PBR\ face/PBR_face_269.png ./out/Assets/PBR/PBR_face_269.png
cp ../images/PBR\ face/PBR_face_353.png ./out/Assets/PBR/PBR_face_353.png
cp ../images/PBR\ body/PBR_body_106.png ./out/Assets/PBR/PBR_body_106.png
cp ../images/PBR\ body/PBR_body_365.png ./out/Assets/PBR/PBR_body_365.png
cp ../images/PBR\ body/PBR_body_011.png ./out/Assets/PBR/PBR_body_011.png
cp ../images/PBR\ body/PBR_body_100.png ./out/Assets/PBR/PBR_body_100.png
cp ../images/PBR\ body/PBR_body_046.png ./out/Assets/PBR/PBR_body_046.png
cp ../images/PBR\ face/PBR_face_376.png ./out/Assets/PBR/PBR_face_376.png
cp ../images/PBR\ face/PBR_face_035.png ./out/Assets/PBR/PBR_face_035.png
cp ../images/PBR\ face/PBR_face_046.png ./out/Assets/PBR/PBR_face_046.png
cp ../images/PBR\ body/PBR_body_438.png ./out/Assets/PBR/PBR_body_438.png
cp ../images/PBR\ face/PBR_face_385.png ./out/Assets/PBR/PBR_face_385.png
cp ../images/PBR\ body/PBR_body_290.png ./out/Assets/PBR/PBR_body_290.png
cp ../images/PBR\ face/PBR_face_117.png ./out/Assets/PBR/PBR_face_117.png
cp ../images/PBR\ body/PBR_body_025.png ./out/Assets/PBR/PBR_body_025.png
cp ../images/PBR\ face/PBR_face_334.png ./out/Assets/PBR/PBR_face_334.png
cp ../images/PBR\ face/PBR_face_065.png ./out/Assets/PBR/PBR_face_065.png
cp ../images/PBR\ body/PBR_body_168.png ./out/Assets/PBR/PBR_body_168.png
cp ../images/PBR\ face/PBR_face_165.png ./out/Assets/PBR/PBR_face_165.png
cp ../images/PBR\ face/PBR_face_374.png ./out/Assets/PBR/PBR_face_374.png
cp ../images/PBR\ body/PBR_body_360.png ./out/Assets/PBR/PBR_body_360.png
cp ../images/PBR\ body/PBR_body_453.png ./out/Assets/PBR/PBR_body_453.png
cp ../images/PBR\ body/PBR_body_408.png ./out/Assets/PBR/PBR_body_408.png
cp ../images/PBR\ face/PBR_face_239.png ./out/Assets/PBR/PBR_face_239.png
cp ../images/PBR\ face/PBR_face_069.png ./out/Assets/PBR/PBR_face_069.png
cp ../images/PBR\ body/PBR_body_005.png ./out/Assets/PBR/PBR_body_005.png
cp ../images/PBR\ face/PBR_face_372.png ./out/Assets/PBR/PBR_face_372.png
cp ../images/PBR\ face/PBR_face_226.png ./out/Assets/PBR/PBR_face_226.png
cp ../images/PBR\ body/PBR_body_195.png ./out/Assets/PBR/PBR_body_195.png
cp ../images/PBR\ face/PBR_face_010.png ./out/Assets/PBR/PBR_face_010.png
cp ../images/PBR\ face/PBR_face_128.png ./out/Assets/PBR/PBR_face_128.png
cp ../images/PBR\ body/PBR_body_405.png ./out/Assets/PBR/PBR_body_405.png
cp ../images/PBR\ face/PBR_face_256.png ./out/Assets/PBR/PBR_face_256.png
cp ../images/PBR\ face/PBR_face_491.png ./out/Assets/PBR/PBR_face_491.png
cp ../images/PBR\ body/PBR_body_175.png ./out/Assets/PBR/PBR_body_175.png
cp ../images/PBR\ body/PBR_body_478.png ./out/Assets/PBR/PBR_body_478.png
cp ../images/PBR\ body/PBR_body_020.png ./out/Assets/PBR/PBR_body_020.png
cp ../images/PBR\ face/PBR_face_482.png ./out/Assets/PBR/PBR_face_482.png
cp ../images/PBR\ face/PBR_face_261.png ./out/Assets/PBR/PBR_face_261.png
cp ../images/PBR\ body/PBR_body_386.png ./out/Assets/PBR/PBR_body_386.png
cp ../images/PBR\ face/PBR_face_325.png ./out/Assets/PBR/PBR_face_325.png
cp ../images/PBR\ face/PBR_face_156.png ./out/Assets/PBR/PBR_face_156.png
cp ../images/PBR\ body/PBR_body_440.png ./out/Assets/PBR/PBR_body_440.png
cp ../images/PBR\ body/PBR_body_027.png ./out/Assets/PBR/PBR_body_027.png
cp ../images/PBR\ face/PBR_face_107.png ./out/Assets/PBR/PBR_face_107.png
cp ../images/PBR\ face/PBR_face_112.png ./out/Assets/PBR/PBR_face_112.png
cp ../images/PBR\ body/PBR_body_201.png ./out/Assets/PBR/PBR_body_201.png
cp ../images/PBR\ face/PBR_face_375.png ./out/Assets/PBR/PBR_face_375.png
cp ../images/PBR\ body/PBR_body_072.png ./out/Assets/PBR/PBR_body_072.png
cp ../images/PBR\ face/PBR_face_028.png ./out/Assets/PBR/PBR_face_028.png
cp ../images/PBR\ body/PBR_body_385.png ./out/Assets/PBR/PBR_body_385.png
cp ../images/PBR\ body/PBR_body_456.png ./out/Assets/PBR/PBR_body_456.png
cp ../images/PBR\ face/PBR_face_418.png ./out/Assets/PBR/PBR_face_418.png
cp ../images/PBR\ body/PBR_body_142.png ./out/Assets/PBR/PBR_body_142.png
cp ../images/PBR\ face/PBR_face_089.png ./out/Assets/PBR/PBR_face_089.png
cp ../images/PBR\ face/PBR_face_060.png ./out/Assets/PBR/PBR_face_060.png
cp ../images/PBR\ face/PBR_face_420.png ./out/Assets/PBR/PBR_face_420.png
cp ../images/PBR\ face/PBR_face_263.png ./out/Assets/PBR/PBR_face_263.png
cp ../images/PBR\ body/PBR_body_120.png ./out/Assets/PBR/PBR_body_120.png
cp ../images/PBR\ body/PBR_body_261.png ./out/Assets/PBR/PBR_body_261.png
cp ../images/PBR\ face/PBR_face_362.png ./out/Assets/PBR/PBR_face_362.png
cp ../images/PBR\ face/PBR_face_463.png ./out/Assets/PBR/PBR_face_463.png
cp ../images/PBR\ face/PBR_face_364.png ./out/Assets/PBR/PBR_face_364.png
cp ../images/PBR\ face/PBR_face_422.png ./out/Assets/PBR/PBR_face_422.png
cp ../images/PBR\ body/PBR_body_372.png ./out/Assets/PBR/PBR_body_372.png
cp ../images/PBR\ face/PBR_face_487.png ./out/Assets/PBR/PBR_face_487.png
cp ../images/PBR\ body/PBR_body_230.png ./out/Assets/PBR/PBR_body_230.png
cp ../images/PBR\ body/PBR_body_485.png ./out/Assets/PBR/PBR_body_485.png
cp ../images/PBR\ face/PBR_face_284.png ./out/Assets/PBR/PBR_face_284.png
cp ../images/PBR\ face/PBR_face_440.png ./out/Assets/PBR/PBR_face_440.png
cp ../images/PBR\ body/PBR_body_240.png ./out/Assets/PBR/PBR_body_240.png
cp ../images/PBR\ body/PBR_body_500.png ./out/Assets/PBR/PBR_body_500.png
cp ../images/PBR\ face/PBR_face_484.png ./out/Assets/PBR/PBR_face_484.png
cp ../images/PBR\ body/PBR_body_449.png ./out/Assets/PBR/PBR_body_449.png
cp ../images/PBR\ body/PBR_body_482.png ./out/Assets/PBR/PBR_body_482.png
cp ../images/PBR\ body/PBR_body_172.png ./out/Assets/PBR/PBR_body_172.png
cp ../images/PBR\ body/PBR_body_161.png ./out/Assets/PBR/PBR_body_161.png
cp ../images/PBR\ body/PBR_body_083.png ./out/Assets/PBR/PBR_body_083.png
cp ../images/PBR\ body/PBR_body_069.png ./out/Assets/PBR/PBR_body_069.png
cp ../images/PBR\ body/PBR_body_429.png ./out/Assets/PBR/PBR_body_429.png
cp ../images/PBR\ body/PBR_body_364.png ./out/Assets/PBR/PBR_body_364.png
cp ../images/PBR\ body/PBR_body_208.png ./out/Assets/PBR/PBR_body_208.png
cp ../images/PBR\ face/PBR_face_171.png ./out/Assets/PBR/PBR_face_171.png
cp ../images/PBR\ body/PBR_body_099.png ./out/Assets/PBR/PBR_body_099.png
cp ../images/PBR\ face/PBR_face_357.png ./out/Assets/PBR/PBR_face_357.png
cp ../tools/Linux/wiimm/* ./out/Assets/PBR/wiimm
echo "Compiling PBR Tool. This may take a while..."
swiftc -emit-executable -DENV_LINUX -o ./out/PBR\ Tool\ CLI ../extensions/LinuxExtensions.swift ../enums/XGResources.swift ../Objects/file\ formats/XGFsys.swift ../GoDToolOSX/Objects/GoDKeyCodes.swift ../Revolution\ Tool\ CL/objects/PBRType.swift ../GoDToolOSX/Objects/XGVertex.swift ../extensions/GoDImageExtensions.swift ../Revolution\ Tool\ CL/enums/PBRTMs.swift ../Revolution\ Tool\ CL/enums/PBRMoveTypes.swift ../Objects/data\ types/XGEvolution.swift ../Revolution\ Tool\ CL/objects/PBRDataTableEntry.swift ../Revolution\ Tool\ CL/objects/PBRMove.swift ../enums/XGWormadamForms.swift ../Revolution\ Tool\ CL/enums/PBRScriptOps.swift ../Revolution\ Tool\ CL/enums/PBRMoveCategory.swift ../Revolution\ Tool\ CL/enums/PBRDecks.swift ../enums/XGNatures.swift ../Revolution\ Tool\ CL/enums/PBRFiles.swift ../Revolution\ Tool\ CL/objects/PBRPokemonStats.swift ../Revolution\ Tool\ CL/enums/PBRUnicodeCharacters.swift ../Revolution\ Tool\ CL/enums/PBRTrainerModels.swift ../Revolution\ Tool\ CL/objects/PBRTypeManager.swift ../Revolution\ Tool\ CL/objects/PBRScriptInstruction.swift ../Revolution\ Tool\ CL/objects/PBRISO.swift ../enums/XGGenders.swift ../Revolution\ Tool\ CL/enums/PBRPokemonSprite.swift ../Revolution\ Tool\ CL/objects/PBRTrainer.swift ../Revolution\ Tool\ CL/enums/PBRContestAppeals.swift ../extensions/XGExtensions.swift ../extensions/PBRExtensions.swift ../Revolution\ Tool\ CL/objects/PBRScriptClass.swift ../Revolution\ Tool\ CL/enums/PBREffectivenessValues.swift ../extensions/PBRCLExtensions.swift ../Revolution\ Tool\ CL/enums/PBRFileTypes.swift ../Objects/data\ types/XGString.swift ../Revolution\ Tool\ CL/enums/PBRAbilities.swift ../enums/XGExpRate.swift ../Revolution\ Tool\ CL/enums/PBRExpr.swift ../enums/XGASM.swift ../Objects/textures/XGTextureBlock.swift ../Objects/managers/GoDShellManager.swift ../Revolution\ Tool\ CL/objects/PBRDolPatcher.swift ../enums/GoDTextureFormats.swift ../Revolution\ Tool\ CL/enums/PBRPokemon.swift ../Objects/managers/DummyThreadManager.swift ../Revolution\ Tool\ CL/enums/PBRDeckTrainer.swift ../Objects/file\ formats/XGGSWTextures.swift ../Revolution\ Tool\ CL/enums/PBRSpecialStringCharacters.swift ../Revolution\ Tool\ CL/enums/PBRMoves.swift ../enums/XGShinyValues.swift ../enums/XGWeather.swift ../Revolution\ Tool\ CL/objects/PBRScriptCompiler.swift ../enums/XGEvolutionConditionType.swift ../Objects/file\ formats/XGLZSS.swift ../Revolution\ Tool\ CL/enums/PBREvolutionMethods.swift ../enums/XGBattleStyles.swift ../Objects/data\ types/XGLevelUpMove.swift ../Objects/textures/GoDTextureImporter.swift ../Objects/textures/XGTexturePalette.swift ../enums/XGContestCategories.swift ../protocols/EnumerableDocumentable.swift ../Objects/managers/XGSettings.swift ../Revolution\ Tool\ CL/enums/PBRMoveTargets.swift ../Revolution\ Tool\ CL/enums/PBRDeckPokemon.swift ../Revolution\ Tool\ CL/objects/PBRItem.swift ../Revolution\ Tool\ CL/objects/PBRConstant.swift ../enums/XGGenderRatios.swift ../Revolution\ Tool\ CL/objects/PBRStringTable.swift ../PBR-CLI/main.swift ../Revolution\ Tool\ CL/objects/PBRTextureContainingFormats.swift ../Revolution\ Tool\ CL/objects/PBRTrainerPokemon.swift ../Objects/textures/GoDTexture.swift ../Objects/file\ formats/XGAssemblyCode.swift ../Revolution\ Tool\ CL/objects/PBRScriptClassData.swift ../Revolution\ Tool\ CL/enums/PBRItems.swift ../enums/XGDeoxysFormes.swift ../Objects/file\ formats/GoDTexturesContaining.swift ../Objects/textures/XGImage.swift ../Objects/textures/XGColour.swift ../Objects/helper\ data\ types/XGStack.swift ../Revolution\ Tool\ CL/enums/PBRMoveEffectTypes.swift ../extensions/GoDOSXExtensions.swift ../Objects/helper\ data\ types/XGMutableData.swift ../Revolution\ Tool\ CL/objects/PBRScript.swift ../Revolution\ Tool\ CL/objects/PBRDataTable.swift ../Objects/textures/XGPNGBlock.swift